import {candidate as p,type ElectricianCategory} from './electrician-catalog-types';
const m='https://www.milwaukeetool.com/',k='https://www.kleintools.com/catalog/';
export const jobsiteCategories:ElectricianCategory[]=[
{
 slug:'best-fish-tapes-for-electricians',title:'Best Fish Tapes and Fish Rods for Electricians',meta:'Compare Klein steel and fiberglass fish tapes, Milwaukee and Southwire nonconductive-tip tapes, and a fish-stick kit. Match conduit routes or open voids.',keyword:'best fish tape for electricians',secondary:['steel vs fiberglass fish tape','fish tape vs fish rods','tools for pulling wire through conduit'],cluster:'Cable Routing',
 answer:'Klein 56331 is our short-run steel-tape starting point. Compare fiberglass 56380 and polyester alternatives for different routes; use the Milwaukee 48-22-4152 rods for supported open-void access rather than treating rods as a conduit tape.',note:'A nonconductive tape body can still have conductive fittings. These tools do not authorize fishing near energized equipment. Route length, bend geometry, fill, pulling tension and the permitted work procedure determine suitability.',workflowSlugs:['electrician-residential-rewire-tool-kit','commercial-electrician-tool-kit','electrician-cable-pulling-tool-kit'],
 criteria:[{title:'Conduit or an open cavity?',body:'A coiled fish tape and a sectional rod kit address different access problems. Decide how the route will be reached before comparing lengths. Neither tool proves that a concealed path is clear or suitable for new cable.'},{title:'Read the whole construction',body:'Steel, fiberglass and polyester have different handling characteristics. Read the tip and leader specification as well as the body material. A nonconductive description is not permission to use the tool around energized parts.'},{title:'Choose useful reach',body:'The longest tape is not automatically easiest to handle on a short service job. Account for the route, bends, working space and supported pulling load. Cable and route requirements may also call for specialized pulling equipment.'}],
 faqs:[{q:'Is steel or fiberglass fish tape better?',a:'Choose by the route, handling needs and complete construction. Fiberglass bodies may have metal leaders; neither choice authorizes work near energized equipment.'},{q:'When should I use fish rods instead of tape?',a:'Rods can suit supported open cavities where a sectional tool helps reach the route. A tape is a different format for appropriate conduit runs.'},{q:'Does tape length equal pulling capacity?',a:'No. Length, pulling load and compatibility are separate specifications. Follow the cable and tool instructions.'}],
 products:[
 p('klein-56331','Klein Tools','56331 Steel Fish Tape, 50-Foot','Lead pick for short-run steel tape',k+'fish-tapes/steel-fish-tape-18-inch-x-50-foot','Users whose planned route suits a 50-foot steel fish tape.','A longer route, different tape construction or an open-void rod is required.','56331 is a 50-foot steel fish tape with a one-eighth-inch tape width. Its role here is a straightforward short-run conduit tool, rather than a claim that steel is best for every route.','Choose it when length and steel construction match the planned work. Compare the longer fiberglass and polyester tools for their specific handling requirements; do not use this purchase choice to decide whether a route is safe to fish.',['50-foot reach','Steel tape construction','Coiled conduit-fishing format'],['Conductive steel construction','Length may not cover the route'],[['Model','56331'],['Length','50 feet'],['Tape','1/8-inch steel']],[
 'The useful starting question for 56331 is whether a 50-foot coiled steel tape fits the actual conduit route. A short service run does not necessarily benefit from buying the longest possible tool. Working room, bend geometry and the access points can matter as much as length. We have not tested bend negotiation, payout effort or pulling performance against the fiberglass alternatives.',
 'Steel construction is an explicit boundary in this recommendation. Establish the permitted work conditions and isolation procedure independently of the tool purchase. The presence of a plastic case or handle does not make the steel tape nonconductive. Likewise, replacing it with a fiberglass model does not automatically remove every conductive component or authorize use beside energized parts.',
 'Klein 56380 offers a longer fiberglass format with a steel spiral leader; the Milwaukee and Southwire alternatives specify nonconductive tips. Read the entire construction before choosing. Where the problem is reaching an open cavity rather than advancing through suitable conduit, sectional fish rods may be a better format. The cable-pulling workflow also covers when route planning and specialized equipment should come before a tape purchase.'
 ]),
 p('klein-56380','Klein Tools','56380 Fiberglass Fish Tape, 100-Foot','For longer fiberglass-tape routes',k+'fish-tapes/multi-groove-fiberglass-fish-tape-spiral-steel-leader-100-foot','Users whose route suits the documented fiberglass tape and spiral steel leader.','A nonconductive tip specification or another format is required.','56380 pairs a 100-foot fiberglass tape with a spiral steel leader. That leader matters: the body material alone does not describe the electrical properties of the whole assembly.','Compare route length and handling needs with the steel option. Select it for its construction and reach, while following the permitted fishing procedure and the manufacturer’s limits.',['100-foot length','Fiberglass body','Spiral leader configuration'],['Leader is steel','Longer format may be unnecessary for short runs'],[['Model','56380'],['Length','100 feet'],['Leader','Spiral steel']]),
 p('milwaukee-48224165','Milwaukee','48-22-4165 Polyester Fish Tape, 100-Foot','For a polyester nonconductive-tip format',m+'products/details/100-polyester-fish-tape-with-nonconductive-tip/48-22-4165','Users selecting the documented polyester tape and nonconductive-tip construction.','The route, pulling limits or required reach need another tool.','48-22-4165 is a 100-foot polyester fish tape with a nonconductive tip. The exact suffix matters because other Milwaukee fish tapes use different materials and leaders.','Choose based on the route and whole-tool documentation. A nonconductive tip is a construction feature, not an authorization to fish in energized conditions.',['100-foot reach','Polyester tape','Nonconductive tip specification'],['Route compatibility still needs checking','Does not authorize energized use'],[['Model','48-22-4165'],['Length','100 feet'],['Construction','Polyester / nonconductive tip']]),
 p('southwire-ftsp45-125nct','Southwire','FTSP45-125NCT SIMpull Fish Tape','For a longer nonconductive-tip tape','https://www.southwire.com/tools-equipment/cable-pulling-fishing/ftsp45-125nct-fishtape-4-5mm-sim-125-/p/63163740','Users whose route calls for the 125-foot SIMpull format.','A shorter tool or sectional rod kit is a better access solution.','FTSP45-125NCT specifies a 4.5 mm tape and a 125-foot length with a nonconductive tip. Those details distinguish this configuration from similarly named SIMpull models.','Compare the additional reach with the working space and route. More length does not establish allowable pulling tension, and the nonconductive-tip label does not change required isolation.',['125-foot length','4.5 mm format','Nonconductive tip specification'],['Extra reach adds a larger tool to manage','Load and route limits require a separate check'],[['Model','FTSP45-125NCT'],['Length','125 feet'],['Tape size','4.5 mm']]),
 p('milwaukee-48224152','Milwaukee','48-22-4152 Mid-Flex Fish Stick Kit','For open-void rod access',m+'products/details/15-mid-flex-fish-stick-kit/48-22-4152','Users needing sectional rods for a suitable open-cavity route.','A coiled conduit tape or different flexibility is required.','48-22-4152 is a 15-foot mid-flex fish-stick kit, not a fish tape. It is included as a format alternative because cable access in an open cavity can require a different tool.','Choose rods when their sectional reach and flexibility fit the access problem. Do not compare their 15-foot assembled length directly with a 100-foot conduit tape as if they perform the same job.',['Sectional rod format','15-foot assembled reach','Mid-flex configuration'],['Different role from a conduit tape','Route and accessory suitability still matter'],[['Model','48-22-4152'],['Length','15 feet'],['Format','Mid-flex fish sticks']])
 ]
},
{
 slug:'best-work-lights-for-electricians',title:'Best Work Lights for Electricians: Service, Attic and Installation',meta:'Compare Milwaukee M12 ROVER and stick lights, DeWalt DCL050, Makita DML811 and Streamlight Siege. Choose task lighting, area coverage and power options.',keyword:'best work light for electricians',secondary:['electrician attic work light','cordless service work light','work light for electrical panel'],cluster:'Lighting & Storage',
 answer:'Milwaukee 2367-20 ROVER is our M12 service-light starting point. Compare the M12 stick light for a narrower task format, DeWalt for its battery platform, Makita for corded or cordless area lighting, and Siege for a separate-battery lantern.',note:'Light output alone does not describe glare, shadowing, mounting or runtime. We have not measured beam patterns or endurance. Confirm the power package and environmental rating of the exact model.',workflowSlugs:['electrician-service-call-tool-kit','electrician-residential-rewire-tool-kit','electrician-panel-work-tool-kit','electrician-van-tool-bag-setup'],
 criteria:[{title:'Light the task or the space',body:'A service flood, stick light and lantern present light differently. Choose the format that can be positioned without blocking the work. A larger area light may be helpful on an installation but excessive for the service bag.'},{title:'Make power independent where useful',body:'A compatible tool battery simplifies charging. A separate-battery lantern can provide another power option. Corded capability is useful only where a suitable supply is available and permitted.'},{title:'Check positioning and environment',body:'Read mounting features, ingress protection and temperature limits for the exact model. A brand family does not guarantee the same protection on every light. Visibility does not replace required electrical safety controls.'}],
 faqs:[{q:'How many lumens does an electrician need?',a:'There is no single number for every task. Beam shape, placement, shadows and the size of the work area matter alongside output.'},{q:'Should the light use my drill batteries?',a:'That can simplify charging, but a separate power option may be useful. Compare the complete kit and backup plan.'},{q:'Can a work light replace a headlamp?',a:'They serve different positioning needs. Choose both only when area lighting and hands-free personal illumination are useful for your work.'}],
 products:[
 p('milwaukee-2367-20','Milwaukee','2367-20 M12 ROVER Service & Repair Flood Light','Lead pick for an M12 service kit',m+'2367-20','M12 users needing a portable service flood-light format.','Larger area coverage, personal headlamp positioning or a different platform is required.','2367-20 is an M12 ROVER service and repair flood light with a USB charging function. It is a service-kit format rather than the same product as a large installation floodlight.','Consider it when your M12 batteries and service-light placement fit. Confirm the bare-tool power package and mounting instructions; USB charging is a secondary feature, not the main reason to choose a work light.',['M12 battery compatibility','Service flood-light format','USB charging function'],['Battery and charger separate','Not a personal headlamp'],[['Model','2367-20'],['Platform','M12'],['Advertised light output','700 lumens; manufacturer figure'],['Head adjustment','120-degree pivot'],['Ingress rating','IP54'],['USB output','2.1 A']],[
 '2367-20 fits the portable-light position in an M12 service kit. A technician moving between small work areas may value a flood format that can be set down or positioned separately from the person. That does not establish the best beam for every panel or attic. We have not measured shadowing, glare or light falloff and do not present this as a hands-on lighting test.',
 'Think about where the light will sit before comparing headline output. A light placed behind the user can leave the task in shadow, while a tool taking up the working space can obstruct access. The manufacturer’s positioning and mounting provisions should be checked against the actual location. An installation area may instead justify a larger stand-mounted or corded-capable format.',
 'Sharing M12 batteries is practical when the rest of the bag already uses them. It also means the lighting plan depends on charged compatible packs, so account for spare power and the battery allocated to the drill. The USB feature is useful only within its documented function. Compare the stick-light format for another placement option and the separate-battery Siege lantern when an independent power source is the more useful addition.'
 ]),
 p('milwaukee-2351-20','Milwaukee','2351-20 M12 Stick Light','For a narrower M12 task-light format',m+'products/details/m12-stick-light/2351-20','M12 users wanting a stick-format light for appropriate task placement.','Broad area coverage or a different power supply is required.','2351-20 takes the M12 stick-light format rather than the ROVER service flood format. It is a placement alternative within the same battery family.','Choose by how the body and documented mounting options fit the task. Do not assume that sharing batteries makes its beam or environmental protection identical to another M12 light.',['M12 platform','Stick-light format','Separate placement option'],['Different coverage from an area flood','Battery and charger separate'],[['Model','2351-20'],['Platform','M12'],['Format','Stick light']]),
 p('dewalt-dcl050','DeWalt','DCL050 20V MAX Hand-Held Area Light','For DeWalt service lighting','https://www.dewalt.com/en-us/product/dcl050/20v-max-led-hand-held-area-light-tool-only','DeWalt battery owners wanting a hand-held area-light format.','A personal headlamp, corded option or larger installation light is needed.','DCL050 is a DeWalt 20V MAX hand-held area light. Its role is portable task and area illumination using a compatible tool battery.','Compare its positioning with the working area and check the exact US model package. A listing for a regional suffix should not be assumed to have the same contents or availability.',['20V MAX platform','Hand-held area format','Tool-battery power'],['No corded power option claimed here','Tool-only package'],[['Model','DCL050'],['Platform','20V MAX'],['Format','Hand-held area light']]),
 p('makita-dml811','Makita','DML811 18V LXT Corded/Cordless Work Light','For installation area lighting','https://makitatools.com/products/details/DML811','Users needing the documented AC or LXT-powered area-light format.','A smaller service-bag light or personal illumination is sufficient.','DML811 is a corded/cordless work light supporting 18V LXT battery power or 120V AC. Makita documents IP65 protection for this model.','Consider it for a wider installation area rather than as a direct replacement for a compact stick light. Verify the power accessories and environmental instructions before using either supply option.',['Corded or cordless operation','18V LXT compatibility','Documented IP65 rating'],['Larger format for a service bag','Suitable AC supply may be unavailable'],[['Model','DML811'],['Power','18V LXT or 120V AC'],['Protection','IP65']]),
 p('streamlight-siege-44931','Streamlight','The Siege 44931 Lantern','For separate-battery area light','https://www.streamlight.com/products/detail/the-siege','Users wanting a lantern powered independently of the drill battery system.','A directional task light or personal headlamp is the priority.','The Siege is a lantern format for surrounding area illumination. The 44931 configuration should be distinguished from smaller Siege AA models and rechargeable variants.','Choose the lantern when broad surrounding light and separate-battery power fit the plan. It is not automatically a better tool for seeing into a tight device recess.',['Lantern format','Separate battery supply','Surrounding area illumination'],['Different role from a directional task light','Batteries remain a separate supply requirement'],[['SKU','44931'],['Format','Siege lantern'],['Buyer check','Exact battery type and supplied contents']])
 ]
},
{
 slug:'best-tool-backpacks-for-electricians',title:'Best Tool Backpacks for Electricians: Service Bag or Larger Kit?',meta:'Compare Veto TECH PAC, Klein 55421BP14 and 62800BP, Milwaukee 48-22-8200 and CLC 1134. Match tool access, load and service-kit organization.',keyword:'best tool backpack for electricians',secondary:['electrician tool bag setup','tool backpack for apprentice electrician','Veto vs Klein tool backpack'],cluster:'Lighting & Storage',
 answer:'Veto TECH PAC is our organization-focused lead candidate. Compare the two Klein layouts, Milwaukee’s jobsite backpack and CLC 1134 against your actual tool load; pocket count alone does not establish fit or carrying comfort.',note:'We have not loaded or carried these backpacks. Recommendations are based on documented layout and intended kit fit. Verify the exact model suffix, empty weight, dimensions and warranty before buying.',workflowSlugs:['electrician-service-call-tool-kit','commercial-electrician-tool-kit','electrician-apprentice-starter-kit','electrician-van-tool-bag-setup'],
 criteria:[{title:'Pack a real service list',body:'Start with the tools that leave the van on ordinary calls. Check the longest drivers, meter cases and consumables against the bag dimensions. Buying a larger bag can encourage an unnecessarily heavy load.'},{title:'Count usable positions',body:'Pocket totals combine different sizes and purposes. A layout with fewer suitable pockets can be more useful than a larger number of shallow slots. Think about access without emptying the bag on each call.'},{title:'Separate storage from protection',body:'A molded base or robust fabric does not establish waterproof storage or protection for every meter. Keep sensitive tools in appropriate cases and check the manufacturer’s care instructions and warranty terms.'}],
 faqs:[{q:'How many pockets does an electrician need?',a:'Enough suitable positions for the actual carried kit. Pocket size, access and load organization matter more than the total alone.'},{q:'Should an apprentice buy a premium backpack first?',a:'Confirm the employer’s required tools and a practical carrying method first. Upgrade storage when the daily load and access needs justify it.'},{q:'Is a tool backpack waterproof?',a:'Do not assume so from fabric or base construction. Check the exact model’s claims and protect meters appropriately.'}],
 products:[
 p('veto-tech-pac','Veto Pro Pac','TECH PAC Tool Backpack','Lead pick for a structured service kit','https://vetopropac.com/product/tech-pac/','Users whose regular carried kit benefits from a structured tool-backpack layout.','A smaller carried load, different dimensions or a simpler bag fits better.','TECH PAC is a tool backpack designed around organized trade-tool storage. Its buying case is the layout and fit of a real service kit, rather than a promise of better carrying comfort for every user.','Shortlist it after measuring the tools you carry and checking the bag dimensions and empty weight. Compare the Klein, Milwaukee and CLC layouts before paying for storage capacity you may not use.',['Trade-tool backpack format','Structured organization','Hands-free carrying role'],['10 lb before adding tools','Comfort is not tested here'],[['Model','TECH PAC'],['Pockets','46 interior/exterior'],['Dimensions (H × W × D)','19 × 13 × 10 inches'],['Empty weight','10 lb; manufacturer figure'],['Internal volume','24 L']],[
 'TECH PAC should be evaluated against a written service-tool list. The useful question is whether its organization puts your meters, drivers and everyday hand tools where they can be accessed without unloading everything. We have not packed the bag or tested carrying comfort. This is a research-led layout recommendation, not evidence that a particular user can comfortably carry a heavier kit.',
 'Start with the longest tools and the bulkier protective cases, then account for consumables and the working room needed to remove them. A pocket count does not tell you whether your meter case fits or whether a driver tip catches during removal. Check the manufacturer dimensions and current layout, and compare them with the two Klein configurations rather than treating every trades backpack as the same size.',
 'The van setup workflow separates the service bag from stock and specialist tools that can stay in the vehicle until needed. That is relevant to the purchase: a backpack should not become a reason to carry every tool on every call. Compare simpler storage if the regular load is small. Verify the exact TECH PAC model, warranty terms and seller configuration; other Veto backpacks can have different layouts and purposes.'
 ]),
 p('klein-55421bp14','Klein Tools','55421BP14 Tradesman Pro Backpack','For a 39-pocket service layout',k+'tool-backpacks/tradesman-pro-tool-bag-backpack-39-pockets-black-14-inch','Users whose tools fit the documented 39-pocket Tradesman Pro layout.','The larger XL layout or a different carrying format is needed.','55421BP14 is the specific 39-pocket backpack configuration. It should be compared with the XL model by dimensions and usable tool positions, not pocket count alone.','Check meter-case and long-driver fit before choosing. The model suffix is part of the purchase identity, and a similarly named Tradesman Pro bag may have a different layout.',['39-pocket layout','Trade-tool backpack format','Specific BP14 configuration'],['Actual case fit requires checking','Loaded carrying comfort not tested'],[['Model','55421BP14'],['Pockets','39'],['Format','Tradesman Pro backpack']]),
 p('klein-62800bp','Klein Tools','62800BP Tradesman Pro XL Backpack','For a larger Klein layout',k+'tool-backpacks/tradesman-pro-xl-tool-bag-backpack-40-pockets','Users whose carried kit needs the XL backpack layout.','A smaller bag already holds the everyday kit.','62800BP is the 40-pocket Tradesman Pro XL backpack. XL is a layout and size decision; the single additional counted pocket does not explain its practical difference from the BP14.','Compare the dimensions and actual tools with the smaller Klein option. Keep specialist van equipment separate instead of assuming a bigger backpack should carry everything.',['XL configuration','40-pocket layout','Trade-tool backpack format'],['May encourage a heavier load','Exact tool fit still needs checking'],[['Model','62800BP'],['Pockets','40'],['Format','Tradesman Pro XL backpack']]),
 p('milwaukee-48228200','Milwaukee','48-22-8200 Jobsite Backpack','For tools and a laptop compartment',m+'products/details/jobsite-backpack/48-22-8200','Users needing the documented tool layout and up-to-15.6-inch laptop compartment.','A smaller tool-only bag or another organizational layout suits better.','48-22-8200 is a 35-pocket jobsite backpack with 1680D construction and a documented laptop compartment. Those features distinguish its layout without proving comfort or waterproof storage.','Choose when tools and laptop storage are genuinely part of the carried load. Check the device dimensions and its protective needs rather than relying only on screen diagonal.',['35-pocket layout','Laptop compartment','Molded base format'],['Device protection needs a separate assessment','Loaded weight and comfort not tested'],[['Model','48-22-8200'],['Pockets','35'],['Laptop provision','Up to 15.6 inches; verify device fit']]),
 p('clc-1134','CLC','1134 Deluxe Tool Backpack','For a two-compartment tool layout','https://goclc.com/product/44-pocket-deluxe-tool-backpack/','Users whose tool list fits the documented 44-pocket two-compartment format.','Another layout or a smaller carried load is preferable.','CLC 1134 is a 44-pocket backpack with two main zippered compartments. It offers another organizational approach rather than a guaranteed value winner without a current price comparison.','Check the sizes of usable pockets and the tools you carry. More pockets alone do not establish a better service layout, and we have not tested loaded comfort or durability.',['44-pocket layout','Two main compartments','Tool-backpack carrying format'],['Fit depends on pocket dimensions','No hands-on durability assessment'],[['Model','1134'],['Pockets','44'],['Layout','Two main zippered compartments']])
 ]
}
];
