import {candidate as p,type ElectricianCategory} from './electrician-catalog-types';
const k='https://www.kleintools.com/catalog/';
const f='https://www.fluke.com/en-us/product/';
export const identificationCategories:ElectricianCategory[]=[
{
 slug:'best-circuit-tracers-for-electricians',title:'Best Circuit Tracers for Electricians: Beyond Breaker Finding',meta:'Compare Klein ET450, Fluke 2052 and 2062, and Amprobe AT-6020 and AT-6030 for energized and de-energized tracing. Check receiver modes and kit connections.',keyword:'best circuit tracer for electricians',secondary:['wire tracer for electricians','trace de energized electrical wire','circuit tracer vs breaker finder'],cluster:'Testing & Measurement',
 answer:'Klein ET450 is our lead shortlist option for a dedicated advanced tracing kit. Fluke 2052 and 2062 offer different receiver interfaces and induction accessories; Amprobe AT-6020 and AT-6030 are other kit configurations to compare. Start with connection methods and permitted circuit conditions.',note:'Advanced tracers are a different category from plug-in breaker finders. Published depth, range and accuracy depend on conditions; we have not independently tested concealed-wire performance.',workflowSlugs:['commercial-electrician-tool-kit','electrician-cable-pulling-tool-kit','electrician-residential-rewire-tool-kit'],
 criteria:[{title:'Trace the problem you actually have',body:'Breaker identification, concealed routing and finding an open are distinct tasks. Confirm that the exact transmitter and receiver support the intended circuit condition. An energized tracing specification does not authorize exposure or connection outside a permitted work procedure.'},{title:'Compare the connection kit',body:'Direct leads, plug adapters and induction clamps solve different access problems. Fluke’s listed i400 accessory and Amprobe’s kit differences deserve attention. A receiver-only offer is not a complete tracer; confirm all components before comparing prices.'},{title:'Budget for learning the instrument',body:'Signal coupling and surrounding conductors can complicate interpretation. An intuitive display may help, but it does not remove the need to understand the manufacturer’s modes and limitations. If all you need is outlet-to-breaker identification, start with the simpler finder guide.'}],
 faqs:[{q:'Is a circuit tracer the same as a breaker finder?',a:'No. A basic finder associates an accessible outlet with a supply breaker. Advanced tracers support broader routing and diagnostic tasks, depending on their exact modes and accessories.'},{q:'Can these trace de-energized wires?',a:'The selected kits advertise energized and de-energized tracing. Check their model-specific connection instructions and limitations for the intended task.'},{q:'Does a tracer indication prove the cable location?',a:'Treat it as information to confirm. Signal coupling, construction and wiring layout affect interpretation; follow the manufacturer’s instructions and appropriate verification.'}],
 products:[
 p('klein-et450','Klein Tools','ET450 Advanced Circuit Tracer Kit','Lead pick for broader tracing',k+'electrical-testers/advanced-electrical-circuit-breaker-finder-and-wire-tracer-kit-and-case','Electricians who regularly need more than receptacle-to-breaker identification.','A basic breaker finder would solve your actual jobs.','ET450 is an advanced transmitter-and-receiver kit for energized and non-energized breakers, fuses and wires. The reason to consider it is the broader tracing role, not a promise that concealed circuits become effortless to locate.','Shortlist it for recurring route or identification work where its connection kit fits. Compare the manual and supplied accessories with Fluke and Amprobe before purchasing; receiver features alone do not establish which kit solves your access problem.',['Energized and non-energized tracing','Breaker, fuse and wire roles','Dedicated case-and-kit format'],['More learning and equipment than a plug-in finder','Conditions affect signal interpretation'],[['Model','ET450'],['Circuit condition','Energized and non-energized modes'],['Package','Advanced tracer kit and case']],[
 'A service electrician can identify a breaker with a much simpler tool when the source is an accessible receptacle. ET450 becomes relevant when the question extends to the circuit route, a fuse, or wiring that is not conveniently reached through that plug-in connection. Write down those recurring situations before paying for an advanced kit. More capability is valuable only if it corresponds to work you actually encounter.',
 'The practical comparison is the complete signal path: how the transmitter connects, what the receiver reports and what the operator must interpret. Adapter options and accessories may matter more than a claimed detection distance. Check the exact kit contents against the current instructions. We have not measured tracer response through different walls or compared it with the Fluke kits in the same installation.',
 'For a rewire assessment or commercial diagnostic visit, the tracer belongs with documentation tools and appropriate test instruments. It can provide a lead about a route or association, but it does not certify the wiring or establish safe isolation. Its user needs to distinguish genuine route information from coupling to nearby conductors. The manufacturer’s manual defines the permitted connections and circuit conditions.'
 ]),
 p('fluke-2052','Fluke','2052 Advanced Wire Tracer Kit','For a tracing kit with induction clamp',f+'building-infrastructure/wire-tracers/2052','Users who value the listed i400 induction accessory and a dedicated advanced tracing kit.','You only need basic breaker finding or a more advanced receiver interface is required.','2052 supports energized and de-energized tracing and includes an i400 accessory for inducing a tracing signal where direct conductor access is unavailable. That connection option is a concrete reason to compare the kit.','Choose by connection requirements and the receiver modes you will use. Compare 2062 before assuming the two Fluke kits have identical interfaces, and verify the supplied package rather than purchasing from a family-name search alone.',['Energized and de-energized tracing','Listed i400 induction accessory','CAT IV 600 V manufacturer rating'],['Advanced kit complexity','Not a substitute for locating verification'],[['Safety','CAT IV 600 V'],['Included accessory','i400 clamp in listed kit'],['Tasks','Wire, breaker and fault tracing']]),
 p('fluke-2062','Fluke','2062 Advanced Pro Wire Tracer Kit','For a more guided receiver interface',f+'building-infrastructure/wire-tracers/2062','Technicians who want the Pro receiver’s documented tracing interface and kit.','A simpler receiver meets the requirement or tracing is infrequent.','2062 is Fluke’s Advanced Pro kit. The receiver interface is the comparison point to investigate against 2052; the Pro label is not itself evidence of faster or more accurate field diagnosis.','Review its receiver modes and the exact induction accessories against the jobs you perform. We have not tested the claimed interface advantages, so choose on documented capability and a demonstrated fit with your work.',['Advanced Pro receiver format','Energized and de-energized tracing','Manufacturer-supported kit ecosystem'],['Extra interface features may be unnecessary','No independent route-performance comparison'],[['Model','2062 Advanced Pro'],['Format','Transmitter and receiver kit'],['Circuit modes','Energized and de-energized']]),
 p('amprobe-at6020','Amprobe','AT-6020 Advanced Wire Tracer Kit','For a focused Amprobe kit','https://www.amprobe.com/product/at-6020/','Users evaluating an Amprobe transmitter/receiver configuration for regular tracing.','The added receiver guidance or accessories of another package are needed.','AT-6020 is an advanced tracing kit rather than a plug-in-only breaker finder. Its value depends on its receiver modes and supported transmitter connections matching the job.','Compare its documented package directly with AT-6030. Shared branding does not make the included components or interface interchangeable. Check current supply and software-independent operating requirements before committing.',['Advanced transmitter/receiver format','Manufacturer documentation','Separate kit configuration to compare'],['Accessory differences need checking','Field depth and accuracy are not independently verified'],[['Model','AT-6020'],['Format','Advanced wire tracer kit'],['Buyer check','Receiver modes and kit accessories']]),
 p('amprobe-at6030','Amprobe','AT-6030 Advanced Wire Tracer Kit','For Amprobe’s guided tracing kit','https://www.amprobe.com/product/at-6030/','Technicians wanting the AT-6030 receiver and complete accessory configuration.','A basic finder or smaller tracer configuration is enough.','AT-6030 is a higher-function Amprobe tracing package. Evaluate the exact receiver and accessory list; a promotional demonstration is not a guarantee that every construction type or route will produce the same result.','Compare the package with AT-6020 and Fluke’s kits, including any induction connection needed by your work. Check the current manufacturer instructions and seller’s contents instead of treating the model family as a single offer.',['Advanced kit configuration','Broader tracing purpose than a plug-in finder','Manufacturer training resources'],['Kit complexity and bulk','Confirm current availability and exact accessories'],[['Model','AT-6030'],['Format','Advanced wire tracer kit'],['Purchase check','Complete receiver/transmitter/accessory package']])
 ]
},
{
 slug:'best-receptacle-testers-for-electricians',title:'Best Receptacle and GFCI Testers for Electricians',meta:'Compare Klein RT250, RT210 and RT390, Fluke ST120 and IDEAL 61-501 for outlet wiring indications, GFCI tests and service-call verification.',keyword:'best outlet tester for electricians',secondary:['best GFCI receptacle tester','outlet tester with voltage display','Klein RT250 vs RT210'],cluster:'Testing & Measurement',
 answer:'Klein RT250 is the lead pick when a voltage display and GFCI trip-time indication are useful. RT210 and IDEAL 61-501 cover simpler outlet checks, Fluke ST120 offers a dedicated socket-tester format, and RT390 adds a more involved circuit-analysis role.',note:'Plug-in testers indicate specified conditions. They do not identify every wiring fault, prove the quality of a grounding path or certify an installation.',workflowSlugs:['electrician-service-call-tool-kit','electrician-residential-rewire-tool-kit','electrician-lighting-controls-tool-kit','electrician-apprentice-starter-kit'],
 criteria:[{title:'Indicator, display or analyzer?',body:'A simple indicator can suit frequent basic checks. A numeric display adds context, while an analyzer such as RT390 has a broader load-test role. Choose the level needed rather than expecting a small plug-in tester to answer every diagnostic question.'},{title:'Match US receptacles and ratings',body:'Check the stated voltage and receptacle format. These selections are for compatible North American applications. Manufacturer instructions govern supported circuits and GFCI testing; adapters do not automatically extend a tester’s approved use.'},{title:'Know what a reassuring light omits',body:'A correct-looking pattern is not a complete safety assessment. Multiple faults and grounding/neutral arrangements can defeat simple indications. Investigate symptoms with appropriate instruments and follow the required verification procedures.'}],
 faqs:[{q:'Can an outlet tester detect every wiring problem?',a:'No. Each tester detects a defined set of conditions and has limitations. A reassuring indication does not certify the circuit.'},{q:'Does RT250 add more than RT210?',a:'RT250 adds an LCD with voltage and GFCI trip-time information. RT210 is a simpler indicator-style tester. Choose on the information you need.'},{q:'Do these replace a multimeter?',a:'No. They offer a specific outlet-side check. A meter and other instruments serve different measurement and diagnostic tasks.'}],
 products:[
 p('klein-rt250','Klein Tools','RT250 GFCI Receptacle Tester with LCD','Lead pick for displayed outlet checks',k+'electrical-testers/gfci-receptacle-tester-lcd','Service electricians who value displayed voltage and GFCI trip-time information.','A simple light indication is sufficient or broader circuit analysis is needed.','RT250 combines outlet wiring-condition indications with an LCD and GFCI testing. It is useful when you want more visible information than a basic three-light tester gives, while retaining a small plug-in format.','Choose it for the displayed context, not as a complete installation tester. The LCD does not remove the limitations of outlet-side checks. Compare RT390 for the broader analysis role rather than expecting RT250 to provide it.',['LCD voltage information','GFCI trip-time display','Dedicated plug-in format'],['Does not diagnose every wiring condition','Not a load-analysis substitute'],[['Format','Plug-in GFCI receptacle tester'],['Display','LCD'],['Reported information','Voltage and GFCI trip time']],[
 'RT250 is most relevant near the verification end of a service call, where the electrician wants a clear outlet-side indication and a displayed reading to document. The display may be easier to explain than a legend of colored lights, but interpretation still depends on knowing the tester’s limitations. We have not timed trip measurements against a reference instrument or compared display readability in field conditions.',
 'RT210 is the comparison when simplicity and a basic wiring indication are enough. RT390 is the comparison when the intended job includes its more involved analysis and voltage-drop functions. Those choices avoid buying a device because it appears to be the middle price tier. The useful question is what information would change a decision during your actual work.',
 'A socket tester should be stored so its pins and housing remain protected, and used only within its documented connection requirements. It cannot establish every grounding condition or identify every combination of faults. Preserve that distinction in customer explanations: the tester provides specified indications, while the electrician performs the wider assessment. Follow its manual rather than translating a reassuring display into a certification claim.'
 ]),
 p('klein-rt210','Klein Tools','RT210 GFCI Outlet Tester','For simple indicator checks',k+'electrical-testers/gfci-outlet-tester','Users wanting basic wiring indications plus a GFCI test button.','Displayed voltage, trip timing or circuit-load analysis is required.','RT210 is the compact indicator-style choice with GFCI testing. It gives common outlet conditions a quick display pattern without the LCD information offered by RT250.','A sensible basic kit option when its specified indications are enough. Keep a meter available for measurement questions that the lights do not answer, and do not infer complete fault coverage from a correct pattern.',['Basic wiring indications','GFCI test','Small plug-in format'],['No LCD voltage readout','Defined fault coverage only'],[['Nominal supply','110/125 V AC, 50/60 Hz'],['Display','Indicator pattern'],['GFCI test','Yes']]),
 p('klein-rt390','Klein Tools','RT390 Circuit Analyzer','For more detailed outlet analysis',k+'electrical-testers/circuit-analyzer','Users who need the documented voltage-drop and protective-device testing functions.','A compact basic indicator covers the work or load testing is outside the intended procedure.','RT390 has a broader role than the small outlet testers. Klein lists AC line voltage, AFCI/GFCI checks and voltage-drop tests at specified loads. That capability belongs in a considered diagnostic workflow.','Choose it when its additional information is needed and you are trained to interpret the results. The broader analyzer role adds size and complexity; it should not be treated as a premium version of a three-light tester.',['Voltage-drop test functions','AFCI/GFCI testing roles','AC line-voltage display'],['More involved operation','Not needed for every routine outlet check'],[['Model','RT390'],['Voltage-drop loads','12 A, 15 A and 20 A'],['Protective-device roles','AFCI and GFCI']]),
 p('fluke-st120','Fluke','ST120 GFCI Socket Tester','For a dedicated Fluke socket tester',f+'electrical-testing/basic-testers/fluke-st120','Users preferring Fluke’s dedicated North American socket-tester format.','A numeric display, load analysis or the beeper variant is needed.','ST120 is a dedicated GFCI socket tester for compatible North American outlets. The exact model matters: ST120+ is a distinct beeper version rather than an interchangeable suffix.','Compare its specified indications and physical format with RT210. Select the plus version only if its documented extra function is wanted; do not assume every product photograph or listing represents the same unit.',['Dedicated socket-test role','GFCI test format','North American version'],['ST120 and ST120+ differ','Not a complete circuit analyzer'],[['Model','ST120'],['Role','GFCI socket tester'],['Variant check','ST120 versus ST120+']]),
 p('ideal-61-501','IDEAL','61-501 GFCI Receptacle Tester','For a basic GFCI check','https://www.idealind.com/content/dam/ideal-electrical-dotcom/product-assets/test-measurement/receptacle-testers/resources/ReceptacleTester_CompChart.pdf','Users wanting a basic 120 V receptacle indication and GFI trip function.','LCD information or more advanced analysis is needed.','IDEAL lists 61-501 as a 120 V AC receptacle tester with polarity indication and GFI trip. It is the focused indicator option in the manufacturer’s comparison chart, rather than its LCD model.','Compare the exact model number with IDEAL’s newer display-equipped alternatives. If basic indications fit the work, extra display functions may add little; the tester still has defined detection limits.',['120 V receptacle role','GFI trip function','Polarity indication'],['No LCD','Not every fault is detectable'],[['Supply','120 V AC'],['GFI trip','Yes'],['Display','Indicator lamps']])
 ]
}
];
