export const electricianReviewContext:Record<string,{heading:string;body:string}>={
'fluke-323':{heading:'A buying example: current checks without duplicating the whole meter',body:'Suppose your regular service kit already contains a multimeter that covers the measurements you use, but load-related calls repeatedly require a suitable AC clamp. In that case the 323 has a defined addition to make. If the work also involves DC current, the same purchase logic points away from it and toward 325 or CL390. Do not buy a simpler jaw and hope another dial position changes its current capability. The comparison should include the actual current ranges and published accuracy conditions as well as the required instrument and lead ratings. We have not independently established an accuracy advantage over the alternatives.'},
'klein-ncvt-3p':{heading:'Why the lower indication range is a purchase decision',body:'A lower AC indication band can be useful when the intended screening task falls outside a standard-range pen. It does not make NCVT-3P a universal low-voltage controls instrument: the electrical field, connection, shielding and manufacturer limitations still matter. If the question calls for a numeric voltage reading, a contact instrument is the relevant comparison. Consider the integrated flashlight as a carrying convenience, not a replacement for task lighting or as evidence of improved detection. A person who only needs the documented standard AC screening role may reasonably choose the simpler NCVT-1P. The guide separates those jobs instead of ranking every voltage tester as one interchangeable tool.'},
'klein-et310':{heading:'When a basic finder is the right level of tool',body:'Consider a recurring call where the starting point is an accessible compatible receptacle and the immediate question is which breaker supplies it. That is the buying scenario to evaluate for ET310. A different question—such as identifying a concealed route or tracing wiring without that receptacle access—does not become the same task by adding a cheap adapter. Check the permitted connections and documented accessories first. If the broader tracing requirement is routine, compare an advanced transmitter-and-receiver kit instead. We have not measured identification success across different panel layouts, so this recommendation does not promise a particular signal result in your installation.'},
'klein-et450':{heading:'Before upgrading from a plug-in breaker finder',body:'Write down the tracing situations a simple finder cannot address in your work. Then compare the ET450 connection options and receiver modes with those situations one at a time. A more advanced kit is easier to justify for recurring supported diagnostic work than for an occasional task that a shared site instrument already covers. Also budget for learning signal interpretation and keeping transmitter, receiver and accessories together. The value of a complete kit can disappear if the required adapter is missing on the call. Detection distance, route certainty and wall penetration have not been independently tested here; the case for this upgrade is documented capability fitting a real requirement.'},
'klein-rt250':{heading:'Document the reading without overstating the result',body:'The LCD can give a service record more context than a remembered indicator pattern. Keep the actual outlet location, test conditions and limitation with that record. A displayed voltage or GFCI trip indication answers a defined question; it does not certify every conductor, protective arrangement or possible fault combination. If a complaint requires voltage-drop analysis, compare the documented RT390 functions rather than expecting a clearer display on RT250 to add that measurement. If the job only needs the supported basic indication, RT210 may be sufficient. We do not assign a value winner without a current offer comparison for the exact models and contents.'},
'klein-11055':{heading:'Choose preparation tools by the wires you actually use',body:'For a mixed service bag, write down the solid and stranded copper gauges that recur in repairs and compare each against the documented range. If the normal work falls outside either range, a familiar brand is not a reason to buy an unsuitable tool. A repeated compatible-wire task may point toward an automatic stripper, while constrained access can favor a smaller manual format. Check material and insulation limitations before treating one tool as a universal solution. We have not tested conductor nicking or compared preparation speed, so no claim is made that manual control necessarily produces a better result than every automatic alternative.'},
'klein-j2000-9ne':{heading:'Keep the everyday plier separate from specialty connections',body:'A regular gripping and cutting tool earns its place when those tasks recur in the permitted work. For a particular crimp connection, cable size or material, check whether a separate specified tool is required. The purchase should not be stretched into an unsupported role because the plier feels substantial. Likewise, a covered handle is a comfort feature unless the exact tool is documented as insulated. Compare head size and the documented functions with your access needs before choosing the heavier-duty format. We have not measured grip force, cut effort or long-term edge condition against KNIPEX, Milwaukee or Channellock.'},
'klein-32288':{heading:'Check the profiles before choosing a compact system',body:'An interchangeable insulated system is appealing only if its supplied tips fit the equipment you work on. List the common profiles and sizes and compare them with the exact 32288 contents, then consider blade access and how replacements will be kept available. A fixed-blade set can be preferable when the same profiles are used continuously or changing blades interrupts the work. Conversely, carrying separate drivers for every rarely used profile can add unnecessary bulk. This is a format decision, not a tested speed comparison. Keep a specified calibrated torque tool in the connection kit when required; the insulated handle does not add torque measurement.'},
'milwaukee-2505-20':{heading:'What the four attachments add—and what they do not',body:'Milwaukee lists a three-eighth-inch chuck, offset driver, quarter-inch hex attachment and right-angle attachment for this configuration. That is the concrete access feature to compare with a conventional drill. The manufacturer’s maximum 300 in-lb figure does not describe every accessory capacity or prove the tool is suitable for larger rough-in holes. Read those limits separately. A user who rarely needs the attachment formats may get more practical use from a conventional drill on an existing battery platform. We have not tested attachment clearance or output under load, and the included heads do not turn the tool into a calibrated terminal-torque instrument.'},
'milwaukee-3453-20':{heading:'Compact body and operating modes need context',body:'Milwaukee lists a five-inch body length and four operating modes, including a self-tapping screw mode. Those are useful configuration facts, but the working envelope still includes the fitted bit and battery. The mode selected must fit the permitted fastener and method; it is not a way to certify electrical connection torque. Compare the complete assembly with the access problem and check compatible accessories. If your daily drilling kit already uses M18, DeWalt or Makita batteries, another compact format may avoid a second charging system. We have not measured fastening speed or mode behavior against the alternatives in this guide.'},
'klein-56331':{heading:'Buy the route format before buying extra length',body:'A 50-foot tape can be a sensible choice when that reach covers the planned supported route and the steel construction is appropriate. A longer reel is not automatically an upgrade for short work; it is more equipment to store and manage. Conversely, inadequate reach can make the shorter purchase pointless. Check the route and access points before comparing tools. If the task is reaching across an open cavity, compare sectional rods instead of merely increasing tape length. Required pulling grips, load limits and cable protection remain separate decisions. No pulling-force, bend-negotiation or electrical-isolation performance has been measured for this review.'},
'milwaukee-2367-20':{heading:'Read output, pivot and protection as separate facts',body:'Milwaukee specifies 700 lumens, a 120-degree pivoting head and an IP54 rating for 2367-20. Those facts help define the model without proving the beam will illuminate every work area well. Position and shadows can still determine usefulness. Runtime claims also depend on the selected output mode and battery, so do not transfer the manufacturer’s maximum figure to every service setup. The USB output is listed at 2.1 A; check compatibility with the intended device rather than assuming every charging function is supported. We have not measured light output, ingress resistance or runtime, and a larger installation area can justify a different light format.'},
'veto-tech-pac':{heading:'The ten-pound empty weight changes the carrying decision',body:'Veto lists TECH PAC at ten pounds empty, with 46 pockets and a 24-liter internal volume. The listed body dimensions are 19 inches high, 13 inches wide and 10 inches deep. That makes the weight budget a material buying consideration before tools are added. If your actual daily kit is small, a lighter or simpler bag can be the more useful choice even when this layout has room to spare. The capacity and dimensions do not establish personal comfort or guarantee that a particular meter case fits a pocket. We have not conducted a loaded carrying trial, so assess fit and compare the alternatives against your own load.'}
};
export const electricianProductQuestions:Record<string,{q:string;a:string}[]>={
'fluke-323':[{q:'Does Fluke 323 measure DC current?',a:'No. Its clamp measures AC current up to 400 A. DC voltage measurement through leads is a different function. Compare Fluke 325 if DC clamp current is required.'},{q:'Fluke 323 or 325 for an electrician?',a:'Choose 323 for its focused AC-current role. Compare 325 when its DC-current and supplementary functions match the work; neither is universally the better service choice.'}],
'klein-ncvt-3p':[{q:'What voltage range does Klein NCVT-3P indicate?',a:'Klein documents dual-range AC indication across 12–1000 V. Read the mode instructions and detection limitations; the pen does not provide a numeric voltage measurement.'},{q:'Does NCVT-3P replace a multimeter?',a:'No. It is a screening indicator with a flashlight. Use appropriate contact equipment for the required measurements and absence-of-voltage verification procedure.'}],
'klein-et310':[{q:'Klein ET310 or ET450 for circuit identification?',a:'ET310 serves supported plug-in receptacle-to-breaker identification. ET450 has a broader advanced tracing role. Choose based on the connection and diagnostic task.'},{q:'Does Klein ET310 work on every circuit?',a:'Do not assume so. Check its documented connection, voltage and accessory limits. A plug-in finder is not a universal wire tracer.'}],
'klein-et450':[{q:'Can Klein ET450 trace de-energized wires?',a:'Klein documents energized and non-energized tracing modes. Follow the model-specific connection instructions and limitations; the capability does not authorize live work.'},{q:'Is ET450 necessary for simple breaker finding?',a:'A simpler finder may meet a supported outlet-to-breaker task. ET450 is worth considering when recurring broader tracing work justifies its kit and learning requirements.'}],
'klein-rt250':[{q:'What does Klein RT250 display?',a:'It provides LCD information including voltage and GFCI trip time alongside its documented wiring indications. It does not diagnose every possible wiring condition.'},{q:'Klein RT250 or RT210?',a:'RT250 adds displayed voltage and GFCI trip-time information. RT210 is a simpler indicator format. Choose according to the information needed rather than assuming a display certifies the circuit.'}],
'klein-11055':[{q:'What wire sizes does Klein 11055 strip?',a:'Klein lists 10–18 AWG solid copper and 12–20 AWG stranded copper. Check material and construction separately; one range does not apply to both.'},{q:'Is Klein 11055 an automatic stripper?',a:'No. It is a manual gauge-hole stripper/cutter. Compare 11061 or Katapult 11063W for their supported mechanism-driven preparation roles.'}],
'klein-j2000-9ne':[{q:'Are Klein J2000-9NE pliers insulated?',a:'The standard Journeyman comfort grips are not an insulated-tool selection. Choose an explicitly rated model if the required task calls for insulation.'},{q:'J2000-9NE or a crimping plier?',a:'Choose by the documented task. A required crimp connection may need its specified tool; do not assume the everyday gripping/cutting model covers every connection.'}],
'klein-32288':[{q:'What comes with Klein 32288?',a:'Klein lists an insulated handle and five interchangeable blades in its 8-in-1 system. Check the exact supplied profiles and sizes against the equipment.'},{q:'Does Klein 32288 measure terminal torque?',a:'No. Its insulation and interchangeable profiles do not add calibrated torque measurement. Use the specified suitable torque tool where required.'}],
'milwaukee-2505-20':[{q:'What heads come with Milwaukee 2505-20?',a:'Milwaukee lists a 3/8-inch chuck, offset driver, 1/4-inch hex and right-angle attachment. Check the exact listing contents before ordering.'},{q:'Does Milwaukee 2505-20 include a battery?',a:'The -20 tool-only configuration does not include a battery or charger. Compare the full kit requirements if you are starting an M12 platform.'}],
'milwaukee-3453-20':[{q:'What battery platform does Milwaukee 3453-20 use?',a:'It uses M12 batteries. The -20 bare-tool package needs a compatible battery and charger.'},{q:'Can Milwaukee 3453-20 establish electrical terminal torque?',a:'No. Its impact action and four operating modes do not measure specified terminal torque. Follow the equipment’s fastening method and use the required torque instrument.'}],
'klein-56331':[{q:'How long is Klein 56331 fish tape?',a:'Klein specifies 50 feet of 1/8-inch steel tape. Check whether that reach and construction fit the planned route.'},{q:'Is Klein 56331 nonconductive?',a:'No. It uses steel tape. A plastic case does not change that construction or authorize use near energized equipment.'}],
'milwaukee-2367-20':[{q:'How bright is Milwaukee 2367-20?',a:'Milwaukee advertises 700 lumens. This is a manufacturer figure; we have not measured output, beam pattern or runtime.'},{q:'Does Milwaukee 2367-20 have USB output?',a:'Milwaukee lists a 2.1 A USB output. Verify compatibility with the intended device and the documented operating instructions.'}],
'veto-tech-pac':[{q:'How much does Veto TECH PAC weigh empty?',a:'Veto lists 10 lb empty. Add the actual tools to assess the complete carried load; this review does not claim tested comfort.'},{q:'How many pockets does TECH PAC have?',a:'Veto lists 46 interior and exterior pockets and a 24 L internal volume. Check useful pocket dimensions and case fit rather than choosing by the total alone.'}]
};
