import {candidate as p,type ElectricianCategory} from './electrician-catalog-types';
const m='https://www.milwaukeetool.com/';
export const powerCategories:ElectricianCategory[]=[
{
 slug:'best-cordless-drills-for-electricians',title:'Best Cordless Drills for Electricians: Access or Heavy Drilling?',meta:'Compare Milwaukee M12 installation, M12 and M18 hammer drills, DeWalt DCD805 and Makita XPH14Z. Choose by access, hole-making and battery platform.',keyword:'best cordless drill for electricians',secondary:['drill for electrical installation','compact drill for electrician service calls','electrician hammer drill'],cluster:'Drilling & Fastening',
 answer:'Milwaukee 2505-20 is our access-focused service pick. For a conventional hammer drill, compare M12 3404-20, M18 2904-20, DeWalt DCD805B and Makita XPH14Z against your existing batteries and approved bit sizes.',note:'An installation driver, hammer drill and rotary hammer are different tools. This shortlist does not cover every large-hole, concrete or repetitive rough-in requirement. These listings are tool-only configurations; budget for compatible batteries and a charger.',workflowSlugs:['electrician-service-call-tool-kit','electrician-residential-rewire-tool-kit','commercial-electrician-tool-kit','electrician-lighting-controls-tool-kit'],
 criteria:[{title:'Buy for the limiting task',body:'For cabinet and device access, head configuration may matter more than maximum torque. For repetitive hole-making, check the exact bit and material capacity in the manual. A compact installation drill does not replace every rough-in tool.'},{title:'Account for the complete kit',body:'A bare tool is attractive when compatible batteries are already available. Starting a new platform adds battery and charger costs. Also compare the weight and clearance with the actual battery you intend to use.'},{title:'Distinguish hammer mechanisms',body:'A hammer drill can suit supported masonry drilling, but does not perform the same job as an SDS rotary hammer. Match the drilling method, dust control and accessories to the material and employer requirements.'}],
 faqs:[{q:'Is a 12V drill enough for an electrician?',a:'It can suit supported service and installation tasks. Large holes, repetitive rough-in or concrete work may require a different tool. Check material and bit capacities rather than voltage alone.'},{q:'Should I buy a bare tool or a kit?',a:'Choose a bare tool when you already own suitable batteries and a charger. Otherwise compare the complete kit cost and contents.'},{q:'Does a hammer drill replace a rotary hammer?',a:'No. They use different mechanisms and accessories. Select the tool documented for the material and drilling task.'}],
 products:[
 p('milwaukee-2505-20','Milwaukee','2505-20 M12 FUEL Installation Drill/Driver','Lead pick for access-focused service',m+'2505-20','Service and installation work where interchangeable heads help reach the fastener.','Heavy rough-in or concrete drilling is the main purchase reason.','2505-20 is an M12 installation drill/driver with four supplied head configurations. Its appeal is access and versatility around cabinets and devices, rather than being the largest drill in the van.','Choose it for its installation format when the supported tasks fit your work. Keep a separate heavier drilling tool where the bit size or material requires it. The -20 configuration does not include the battery or charger.',['Four head configurations','M12 battery platform','Access-focused drill/driver format'],['Not a universal rough-in drill','Battery and charger sold separately'],[['Model','2505-20'],['Platform','M12'],['Heads','3/8-inch chuck, offset, 1/4-inch hex, right angle'],['Advertised maximum torque','300 in-lb; manufacturer figure']],[
 'The four-head installation format is the reason to shortlist 2505-20. It offers different ways to present the bit to the work, which is relevant when cabinetry, a device recess or an adjacent surface limits a conventional drill body. We have not measured access clearances or tested the attachment retention; treat this recommendation as a fit assessment from the documented configuration.',
 'It is best considered part of a service kit, alongside hand drivers and the appropriate test equipment. A small power tool can help with suitable mounting and assembly tasks, but the permitted fastening procedure still governs. Electrical terminals that require controlled torque need the specified torque tool. The installation driver is not a substitute for that instrument or for a heavier tool selected for large holes.',
 'Compare 3404-20 when you want a conventional M12 hammer-drill format, and the M18, DeWalt or Makita choices when the drilling requirement points toward their platforms. Battery ownership can be a sensible tie-breaker once capacity is established. Verify the listing suffix: 2505-20 is a bare-tool configuration, and a similarly named kit can have a different battery, charger and carrying-case package.'
 ]),
 p('milwaukee-3404-20','Milwaukee','3404-20 M12 FUEL Hammer Drill/Driver','For a conventional compact hammer drill',m+'3404-20','M12 users wanting a conventional drill/driver with a hammer mode.','Interchangeable installation heads or heavier drilling capacity are the priority.','3404-20 uses a conventional half-inch chuck and M12 platform. It fills a different role from the four-head installation driver, even though both use the same battery family.','Compare the supported bit and material capacities with your common holes. It is a compact-platform option, not proof that every electrician can retire a larger drill.',['M12 platform','Half-inch chuck','Hammer-drill mode'],['No installation-head system','Tool-only package'],[['Model','3404-20'],['Chuck','1/2 inch'],['Platform','M12']]),
 p('milwaukee-2904-20','Milwaukee','2904-20 M18 FUEL Hammer Drill/Driver','For M18 drilling kits',m+'2904-20','M18 users selecting a conventional half-inch hammer drill.','A smaller access tool is sufficient or you use another battery platform.','2904-20 is an M18 hammer drill/driver, positioned here for a drilling-oriented kit. The complete working size depends on the fitted battery as well as the body.','Check the manual against your hole sizes and accessories before buying for rough-in. Do not treat headline torque as a substitute for supported applications or proper control.',['M18 platform','Half-inch chuck','Hammer-drill format'],['Larger-kit commitment than an access driver','Battery and charger separate'],[['Model','2904-20'],['Chuck','1/2 inch'],['Platform','M18']]),
 p('dewalt-dcd805b','DeWalt','DCD805B 20V MAX XR Hammer Drill/Driver','For DeWalt drilling kits','https://www.dewalt.com/en-us/product/dcd805b/20v-max-xr-brushless-cordless-12-hammer-drilldriver-tool-only','DeWalt battery owners wanting a brushless hammer drill/driver.','A rotary hammer, installation-head system or different battery platform is required.','DCD805B is a brushless half-inch hammer drill in the DeWalt 20V MAX family. The B suffix identifies the tool-only package used in this shortlist.','Choose after checking application capacity and battery compatibility. Buying into this platform solely for a general service task should include the charger and battery cost in the comparison.',['Brushless design','Half-inch chuck','20V MAX platform'],['Tool-only configuration','Not an SDS rotary hammer'],[['Model','DCD805B'],['Chuck','1/2 inch'],['Platform','DeWalt 20V MAX']]),
 p('makita-xph14z','Makita','XPH14Z 18V LXT Hammer Driver-Drill','For Makita LXT drilling kits','https://makitatools.com/products/details/XPH14Z','LXT users selecting a brushless half-inch hammer driver-drill.','An access-focused installation tool or another battery platform fits better.','XPH14Z is an 18V LXT brushless hammer driver-drill. It belongs in a capacity and platform comparison, rather than being treated as interchangeable with a small installation driver.','Verify the exact drilling task and complete kit requirements. The Z bare-tool configuration differs from packages that include batteries, so compare the listing contents carefully.',['18V LXT platform','Brushless design','Half-inch chuck'],['Bare tool needs compatible power equipment','Conventional head limits some access tasks'],[['Model','XPH14Z'],['Chuck','1/2 inch'],['Platform','Makita 18V LXT']])
 ]
},
{
 slug:'best-impact-drivers-for-electricians',title:'Best Impact Drivers for Electricians: Compact Service or Installation?',meta:'Compare Milwaukee 3453-20 and 2953-20, DeWalt DCF850B and DCF860B, and Makita XDT19Z. Match battery ownership, access and approved fastening work.',keyword:'best impact driver for electricians',secondary:['compact impact driver electrician','M12 vs M18 impact driver electrical work','impact driver for electrical installation'],cluster:'Drilling & Fastening',
 answer:'Milwaukee 3453-20 is our compact-platform starting point. Compare 2953-20 for M18, DCF850B or DCF860B for DeWalt, and XDT19Z for Makita LXT when the platform and fastening task fit your kit.',note:'Impact drivers are for suitable fastening tasks. They do not establish specified electrical terminal torque. Every model here is a quarter-inch hex driver in a tool-only configuration; bits, batteries and chargers require separate checks.',workflowSlugs:['electrician-residential-rewire-tool-kit','commercial-electrician-tool-kit','electrician-lighting-controls-tool-kit','electrician-van-tool-bag-setup'],
 criteria:[{title:'Start with the fastening work',body:'Mounting hardware and suitable construction screws can justify an impact driver. Delicate devices and specified-torque terminals may require other tools. Identify the task before selecting by maximum torque.'},{title:'Check access with the battery fitted',body:'Body length is only part of the working envelope. The bit, socket adapter and battery also consume room. We have not conducted access or fastening-speed comparisons among these models.'},{title:'Compare control and platform cost',body:'Mode selection can help adapt the tool to a suitable task, but does not make it a calibrated torque instrument. Existing compatible batteries can reduce the purchase cost; a new platform requires a complete-kit budget.'}],
 faqs:[{q:'Can I tighten panel terminals with an impact driver?',a:'Do not assume that is permitted. Follow the equipment instructions and use the specified torque tool and procedure.'},{q:'Do electricians need both a drill and an impact driver?',a:'They perform different roles. Buy both only when your drilling and suitable fastening tasks justify separate tools.'},{q:'Does a selectable mode guarantee torque?',a:'No. Operating modes are not a calibrated terminal-torque measurement.'}],
 products:[
 p('milwaukee-3453-20','Milwaukee','3453-20 M12 FUEL 1/4-inch Hex Impact Driver','Lead pick for an M12 service kit',m+'3453-20','M12 users adding a compact-platform tool for suitable service fastening.','The fastening task requires another tool or you already standardize on another platform.','3453-20 is an M12 quarter-inch hex impact driver. Its purchase case is keeping suitable fastening work on a small battery platform, not replacing hand drivers or torque-controlled terminal tools.','Start here when your M12 batteries and approved fastening jobs fit. Compare M18 or other platforms when those are already part of the van, and verify the bare-tool package before ordering.',['M12 battery platform','Quarter-inch hex format','Separate fastening tool from a drill'],['Not a calibrated torque instrument','Bare tool requires a battery and charger'],[['Model','3453-20'],['Holder','1/4-inch hex'],['Platform','M12'],['Body length','5 inches; manufacturer figure'],['Operating control','Four modes, including self-tapping screw mode']],[
 'An electrician who already carries M12 tools may find 3453-20 a coherent addition for suitable mounting and construction fastening. Sharing a battery family reduces the number of chargers and spare packs to manage. That practical benefit should follow task suitability, not replace it. We have not timed fastening speed, measured working torque or compared endurance with the larger alternatives.',
 'The access question includes the fitted bit and battery. A small-platform driver can still be inconvenient with a long socket adapter or a fastener tucked beside a surface. Before buying for a specific installation, consider how the assembled tool approaches the screw and whether a hand or right-angle tool is more appropriate. Maximum torque does not explain that clearance problem.',
 '2953-20 serves the M18 platform, while DeWalt and Makita choices can make more sense for their battery owners. Keep the electrical-connection role separate: impact action is not a measurement of terminal torque. Check the permitted method and use the specified calibrated tool where required. The -20 listing is tool-only; confirm batteries, charger and compatible impact accessories in the total purchase budget.'
 ]),
 p('milwaukee-2953-20','Milwaukee','2953-20 M18 FUEL 1/4-inch Hex Impact Driver','For M18 fastening kits',m+'2953-20','M18 users wanting a dedicated quarter-inch hex impact driver.','A smaller kit or another established battery platform is preferable.','2953-20 fits the M18 fastening-tool role. It should be compared with the M12 model on task, platform and working size, rather than assuming larger voltage always means a better service tool.','Consider it when M18 already powers the rest of your drilling kit. Read the operating modes and accessories documentation; none of that establishes required terminal torque.',['M18 platform','Quarter-inch hex holder','Dedicated impact fastening role'],['Not a terminal torque instrument','Battery and charger separate'],[['Model','2953-20'],['Holder','1/4-inch hex'],['Platform','M18']]),
 p('dewalt-dcf850b','DeWalt','DCF850B ATOMIC 3-Speed Impact Driver','For compact DeWalt fastening','https://www.dewalt.com/en-us/product/dcf850b/atomic-20v-max-14-3-speed-brushless-impact-driver-tool-only','DeWalt users prioritizing the compact ATOMIC format for appropriate fastening.','A different tool is needed for the connection or the complete kit does not fit your budget.','DCF850B is a brushless three-speed quarter-inch hex impact driver in the ATOMIC range. Its format is the relevant reason to compare it with the XR alternative.','Check access with your chosen battery and accessory fitted. Three speeds provide operating choices, not a calibrated torque setting for an electrical terminal.',['ATOMIC compact format','Three-speed selection','20V MAX platform'],['Tool-only package','No calibrated terminal torque'],[['Model','DCF850B'],['Holder','1/4-inch hex'],['Selection','Three speeds']]),
 p('dewalt-dcf860b','DeWalt','DCF860B XR 3-Speed Impact Driver','For DeWalt XR installation kits','https://www.dewalt.com/en-us/product/dcf860b/20v-max-xr-brushless-cordless-3-speed-high-torque-14-impact-driver-tool-only','DeWalt users selecting the XR high-torque fastening format.','Small access work is the main concern or impact fastening is inappropriate.','DCF860B is a brushless XR three-speed impact driver. Its high-torque positioning is useful only when the fastening task calls for that tool class.','Compare the actual task with the compact DCF850B. More advertised torque does not improve every service job and must not be used as a proxy for controlled electrical-terminal tightening.',['XR platform configuration','Three-speed selection','Brushless design'],['High torque is not universally useful','Bare-tool power equipment separate'],[['Model','DCF860B'],['Holder','1/4-inch hex'],['Platform','20V MAX XR']]),
 p('makita-xdt19z','Makita','XDT19Z 18V LXT 4-Speed Impact Driver','For Makita LXT fastening kits','https://makitatools.com/products/details/XDT19Z/','LXT users who want the documented four-speed and Quick-Shift format.','Another platform or a non-impact tool is more appropriate.','XDT19Z is a brushless four-speed LXT impact driver with Quick-Shift modes. Those operating choices distinguish it within this shortlist without turning the tool into a torque measuring instrument.','Select it when your LXT kit and suitable fasteners fit. Read the mode instructions and confirm the Z bare-tool contents rather than borrowing battery assumptions from XDT19T kits.',['Four-speed format','Quick-Shift modes','18V LXT platform'],['Modes require correct use','Battery and charger separate'],[['Model','XDT19Z'],['Holder','1/4-inch hex'],['Selection','Four speeds']])
 ]
}
];
