import type { Guide } from './data';
import type { ProductReview } from './reviews';
import { candidate, type ElectricianCandidate } from './electrician-catalog-types';
import { plumberCategories } from './plumber-catalog';

export const hvacJobs = {
  service: 'hvac-residential-service-call-tool-kit',
  commission: 'hvac-heat-pump-commissioning-tool-kit',
  evacuation: 'hvac-evacuation-tool-kit',
  recovery: 'hvac-refrigerant-recovery-tool-kit',
  leak: 'hvac-refrigerant-leak-detection-tool-kit',
  airflow: 'hvac-airflow-and-static-pressure-tool-kit',
  apprentice: 'hvac-apprentice-starter-tool-kit',
  van: 'hvac-service-bag-and-van-setup',
};
type Category = {
  slug: string; title: string; cluster: string; answer: string; note: string;
  criteria: {title:string;body:string}[]; faqs:{q:string;a:string}[];
  workflowSlugs:string[]; products:ElectricianCandidate[];
  sections:{heading:string;body:string}[];
};
const fp = 'https://www.fieldpiece.com/product/';
function tool(id:string,brand:string,model:string,role:string,sourceUrl:string,fit:string,limit:string,features:[string,string][],why:string):ElectricianCandidate {
  return candidate(id,brand,model,role,sourceUrl,fit,limit,why,
    `${role}: ${features[0][1]}. ${limit} Compare this configuration with the alternatives below and price the accessories needed for your actual jobs.`,
    features.slice(0,3).map(([label,value])=>`${label}: ${value}`),[limit,'Confirm the seller, package and current manufacturer instructions'],features);
}
const f = (id:string,model:string,role:string,path:string,fit:string,limit:string,features:[string,string][],why:string) => tool(`fieldpiece-${id}`,'Fieldpiece',model,role,fp+path,fit,limit,features,why);
function group(slug:string,title:string,cluster:string,answer:string,note:string,criteria:[string,string][],faqs:[string,string][],jobs:string[],products:ElectricianCandidate[],sections:[string,string][]):Category {
  return {slug,title,cluster,answer,note,criteria:criteria.map(([title,body])=>({title,body})),faqs:faqs.map(([q,a])=>({q,a})),workflowSlugs:jobs,products,sections:sections.map(([heading,body])=>({heading,body}))};
}
const j=hvacJobs;
const pumps = [
  f('vp87','VP87 8 CFM Vacuum Pump','DC-motor evacuation choice','vp87-8cfm-vacuum-pump/','Qualified technicians who want an 8 CFM corded evacuation pump with accessible oil changes.','A vacuum pump does not recover refrigerant or independently verify system dehydration.',[['Capacity','8 CFM'],['Motor','DC'],['Oil system','RunQuick']], 'VP87 pairs an 8 CFM pump with a DC motor and Fieldpiece’s oil-change arrangement. It is a practical comparison for a regularly used evacuation setup; hose restrictions and oil condition still affect the whole system.'),
  f('vp67','VP67 6 CFM Vacuum Pump','Smaller Fieldpiece alternative','vp67-6cfm-vacuum-pump/','Technicians comparing the smaller pump in the RunQuick family.','Its lower nominal capacity is not evidence of a slower or faster completed job without a controlled comparison.',[['Capacity','6 CFM'],['Power','Corded'],['Oil system','RunQuick']], 'VP67 keeps the family’s oil-change approach in the 6 CFM format. Choose by the work, transport and total evacuation setup rather than assuming the biggest pump is necessary.'),
  f('vpx7','VPX7 10 CFM Vacuum Pump','Higher-capacity Fieldpiece option','vpx7-10cfm-vacuum-pump/','Businesses comparing higher pump capacity for recurring evacuation work.','More pump capacity cannot remove a restrictive connection elsewhere in the setup.',[['Capacity','10 CFM'],['Motor','DC'],['Oil system','RunQuick']], 'VPX7 is the 10 CFM choice in this comparison. The upgrade only makes sense after considering the actual hose, service-port and system workload.'),
  f('vp833','VP833 8 CFM A3 Vacuum Pump','For the documented A3 application','vp833-8cfm-vacuum-pump/','Qualified technicians whose refrigerant application requires this model’s documented A3 compatibility.','Do not transfer its A3 compatibility to VP87, VP67 or another similarly named pump.',[['Capacity','8 CFM'],['Compatibility','Manufacturer lists A3'],['Oil system','RunQuick']], 'VP833 is included because refrigerant compatibility can change the equipment choice. It is an application-specific alternative, not a claim that every technician should work on flammable refrigerants.'),
  tool('jb-dv200n','JB Industries','DV-200N PLATINUM FORCE 8 CFM Vacuum Pump','Conventional US corded alternative','https://www.jbind.com/product/platinum-7/','Technicians comparing a current 8 CFM PLATINUM FORCE pump.','The manufacturer now lists an 8 CFM PLATINUM FORCE model; older 7 CFM stock and suffix variants differ.',[['Capacity','8 CFM'],['Series','PLATINUM FORCE'],['Model','DV-200N']], 'JB’s DV-200N provides a different manufacturer and pump arrangement for the same evacuation role. Match the complete part number before comparing a seller’s voltage or refrigerant claims.'),
];
const recovery = [
  f('mr45','MR45 Digital Recovery Machine','Digital recovery choice','mr45-digital-recovery-machine/','Qualified technicians handling recurring refrigerant recovery with a separate appropriate cylinder and scale.','Requires the correct cylinder, hoses, refrigerant compatibility and recovery procedure.',[['Display','Digital'],['Motor','Variable-speed DC'],['Role','Refrigerant recovery']], 'MR45 emphasizes a digital interface and variable-speed motor in a dedicated recovery machine. That serves a different role from an evacuation pump: recovered refrigerant needs an appropriate container and weight monitoring.'),
  tool('appion-g5twin','Appion','G5Twin Refrigerant Recovery Machine','Twin-cylinder alternative','https://appiontools.com/g5twin/','Technicians who prefer the documented liquid-and-vapor recovery machine and its service support.','Appion states Amazon and eBay are not approved distributors; confirm warranty eligibility with Appion before choosing a seller.',[['Compressor','Twin cylinders'],['Power','115 VAC / 60 Hz'],['Weight','24 lb']], 'G5Twin is a dedicated twin-cylinder recovery alternative. Its manufacturer documentation includes supported refrigerants, service parts and safety bulletins. Appion also specifically excludes Amazon and eBay from approved distributors, which matters when choosing where to buy.'),
  tool('navac-nrdd','NAVAC','NRDD Brushless DC Recovery Unit','Digital NAVAC alternative','https://navacglobal.com/product/compact-recovery-unit-nrdd/','Technicians comparing a twin-cylinder recovery machine with a digital interface.','NRDD and the flammable-refrigerant NRDDF are distinct models; confirm compatibility for the exact unit.',[['Motor','Brushless DC'],['Compressor','Twin cylinder'],['Interface','Digital']], 'NRDD combines a brushless DC motor with a twin-cylinder compressor. Select it by the exact refrigerant application and the support available for the machine, not by similar NAVAC model names.'),
  tool('robinair-rg6','Robinair','RG6 Portable Recovery Machine','Established portable alternative','https://www.robinair.com/products/rg6-portable-refrigerant-recovery-machine','Technicians comparing portable liquid-and-vapor recovery equipment.','Do not assume an older RG6 listing supports every newer refrigerant or application.',[['Role','Liquid and vapor recovery'],['Design','Portable'],['Model','RG6']], 'RG6 is Robinair’s portable recovery option in this comparison. Current machine documentation and the refrigerant in the system decide suitability; a general retailer compatibility claim is not enough.'),
  tool('jb-f6dp','JB Industries','F6-DP Refrigerant Recovery Unit','JB dual-piston alternative','https://www.jbind.com/product/refrigerant-recovery-unit/','Technicians comparing JB’s US 115 V recovery configuration.','Confirm F6-DP rather than a 230 V regional suffix, and check the current approved refrigerant list.',[['Power','115 V'],['Compressor','Dual piston'],['Motor','1 HP']], 'F6-DP is the US-voltage JB alternative. Its manufacturer lists A2L compatibility, but that does not make it universal equipment for all flammable refrigerants.'),
];
const detectors = [
  f('dr82','DR82 Infrared Refrigerant Leak Detector','Infrared pinpointing choice','dr82-infrared-refrigerant-leak-detector/','Qualified technicians comparing infrared refrigerant detection with heated-diode tools.','Refrigerant detection is not a combustible-gas safety survey; check its exact approved application.',[['Sensor','Infrared'],['Indication','LCD and audible'],['Wand','Flexible']], 'DR82 offers an infrared sensing approach for locating supported refrigerant leaks. Sensor type, maintenance and the way indications are handled are more useful buying distinctions than a generic claim that it finds every leak.'),
  f('dr58','DR58 Heated Diode Leak Detector','Heated-diode alternative','dr58-heated-diode-refrigerant-leak-detector/','Technicians who prefer the documented heated-diode sensing approach.','Sensor and filter maintenance affect the tool; verify the supported refrigerant and operating conditions.',[['Sensor','Heated diode'],['Indication','Digital'],['Wand','Flexible']], 'DR58 gives a different sensing technology from DR82. Compare its maintenance requirements and approved refrigerants before treating it as an interchangeable lower-cost version.'),
  f('drx3','DRX3 Refrigerant & Combustible Gas Leak Detector','Broader documented gas support','drx3-all-in-one-refrigerant-leak-detector/','Qualified users whose documented gas application calls for this all-in-one detector.','Its hazardous-location approvals and gas support do not transfer to DR58 or DR82.',[['Sensor','Heated diode'],['Scope','Refrigerant and combustible gas'],['Compatibility','Manufacturer lists A1 / A2L / A3']], 'DRX3 adds a broader documented application than the two older detectors. Confirm the actual gas and operating environment instead of assuming that a refrigerant detector is automatically suitable for combustible gas.'),
  tool('inficon-dtek-stratus','INFICON','D-TEK Stratus Leak Detector','Cloud hunting and pinpointing','https://www.inficon.com/en/products/leak-detectors/d-tek-stratus','Technicians investigating refrigerant concentration and then narrowing the leak location.','Different gas sensors and packages have different applications; confirm the fitted sensor.',[['Functions','Cloud hunting and pinpointing'],['Sensor','Infrared'],['Format','Handheld']], 'D-TEK Stratus adds concentration-based cloud hunting to a handheld leak detector. That is a different diagnostic workflow from choosing a basic pinpoint-only instrument.'),
  tool('inficon-dtek3','INFICON','D-TEK 3 Refrigerant Leak Detector','Focused INFICON alternative','https://www.inficon.com/en/products/leak-detectors/d-tek-3','Technicians comparing a focused handheld infrared detector.','Do not assume Stratus concentration-display features or alternative gas sensors are included.',[['Sensor','Infrared'],['Role','Leak pinpointing'],['Format','Handheld']], 'D-TEK 3 is the narrower INFICON comparison when pinpointing is the priority. Select the actual sensor and kit; its similar family name does not make it the same package as Stratus.'),
];
const gauges = [
  f('mg44','MG44 Wireless Vacuum Gauge','Standalone Job Link gauge','mg44-wireless-micron-vacuum-gauge/','Technicians who want a local vacuum display plus compatible remote viewing.','A pump rating or manifold pressure display does not replace a suitable micron measurement.',[['Role','Micron / vacuum measurement'],['Viewing','Local display and wireless'],['System','Job Link']], 'MG44 separates system vacuum measurement from the pump. Its local display is useful when a phone is inconvenient, while connected viewing can support a record of the evacuation and decay assessment.'),
  tool('testo-552i','Testo','552i Wireless Vacuum Probe','Testo connected-probe option','https://www.testo.com/en-US/p/0564-2552-01','Testo users who want a compatible app or manifold to display vacuum measurements.','No standalone numerical screen; confirm the receiving device and kit contents.',[['Role','Vacuum probe'],['Viewing','App / compatible manifold'],['Connection','Wireless']], '552i is a connected vacuum probe, not another manifold. It is a good comparison when the technician already has a supported receiving device and does not need a numerical screen on the probe.'),
  tool('accutools-bluvac-lte','AccuTools','BluVac+ LTE Wireless Vacuum Gauge','Connected dedicated gauge','https://accutools.com/product/bluvac-lte-wireless-digital-vacuum-gauge','Technicians comparing a dedicated vacuum instrument with wireless viewing.','LTE, Pro and Micro are distinct feature configurations.',[['Role','Dedicated vacuum gauge'],['Viewing','Local and wireless'],['Family','BluVac+ LTE']], 'BluVac+ LTE sits between the Micro and Pro configurations. Compare the documentation functions you actually need rather than treating all BluVac models as the same product.'),
  tool('accutools-bluvac-pro','AccuTools','BluVac+ Pro Wireless Vacuum Gauge','More detailed evacuation records','https://accutools.com/product/bluvac-pro-wireless-digital-vacuum-gauge','Technicians who need the Pro model’s documented evacuation and recording functions.','Extra recording functions may be unnecessary for a simpler measurement workflow.',[['Role','Dedicated vacuum gauge'],['Viewing','Local and wireless'],['Family','BluVac+ Pro']], 'BluVac+ Pro is the feature-oriented alternative in this family. The upgrade should follow a requirement for its documented test and record workflow, not a presumption that any smaller gauge cannot measure vacuum.'),
  tool('accutools-bluvac-micro','AccuTools','BluVac+ Micro Wireless Micron Gauge','Compact dedicated alternative','https://accutools.com/product/bluvac-micro-wireless-digital-micron-gauge','Technicians prioritizing a compact vacuum gauge.','Check the Micro’s controls and record features rather than assuming the full Pro workflow.',[['Role','Micron gauge'],['Viewing','Local and wireless'],['Family','BluVac+ Micro']], 'BluVac+ Micro emphasizes a compact measurement tool. That can be preferable when instrument size matters more than the broader Pro configuration.'),
];
const scales = [
  f('sr47','SR47 Wireless Refrigerant Scale','Job Link weight monitoring','sr47-refrigerant-scale-250-lb-capacity-wireless/','Technicians who want tank-weight measurements within a compatible connected workflow.','A scale does not by itself provide an automatic charging valve or prevent cylinder overfill.',[['Role','Refrigerant weighing'],['Viewing','Wireless'],['System','Job Link']], 'SR47 connects refrigerant weight with the Fieldpiece measurement workflow. Select it for that organization of readings, while keeping cylinder limits and charging decisions separate from the display.'),
  f('srs1','SRS1 Refrigerant Scale','Simpler local weighing','srs1-residential-light-commercial-refrigerant-scale/','Residential and light-commercial users needing local weight measurements.','Its 110 lb capacity must cover the actual cylinder and contents.',[['Capacity','110 lb'],['Role','Refrigerant weighing'],['Viewing','Local']], 'SRS1 is the simpler weighing alternative when remote viewing is unnecessary. Required cylinder weight and measurement resolution decide whether that simpler arrangement is sufficient.'),
  tool('testo-560i','Testo','560i Digital Refrigerant Scale','Connected Testo alternative','https://www.testo.com/en-US/testo-560i/p/0564-1560','Testo users comparing connected refrigerant weighing.','Automatic charging requires the appropriate separate valve and supported configuration.',[['Role','Refrigerant weighing'],['Connection','Bluetooth'],['System','Testo Smart']], '560i is a connected scale within Testo’s system. Its automatic charging use case depends on the intelligent valve and receiving instruments; do not assume a scale-only offer includes those components.'),
  tool('navac-nrs2a','NAVAC','NRS2A Smart Refrigerant Scale','Connected NAVAC alternative','https://navacglobal.com/wp-content/uploads/2025/01/NRS2A-Single-Sheet-Black.pdf','NAVAC users who want the documented scale and handheld arrangement.','Automatic charging functions depend on compatible additional equipment.',[['Capacity','220 lb / 100 kg'],['Connection','Bluetooth / myNAVAC'],['Format','Platform and handheld']], 'NRS2A offers a connected weighing arrangement with a separate handheld device. Compare the complete offer and compatible valve equipment if automation is part of the purchase.'),
  tool('cps-cc220','CPS','CC220 Compute-a-Charge Scale','Corded display alternative','https://www.cpsproducts.com/product-details/cc220/','Technicians preferring a platform with a physically connected handheld display.','CC220 is not the programmable solenoid-control configuration.',[['Capacity','220 lb / 100 kg'],['Display','Corded handheld'],['Resolution','0.25 oz / 10 g']], 'CC220 is a straightforward weighing alternative without relying on a phone. Its physical display connection can be useful when dependable local viewing matters more than integrating an app.'),
];
const clamps = [
  f('sc680','SC680 Wireless Power Clamp Meter','Broad HVAC electrical functions','sc680-wireless-power-clamp-meter/','Qualified HVAC technicians needing the documented AC/DC-current and electrical diagnostic functions.','The larger instrument needs access and a suitable category rating for the actual measurement.',[['Jaw current','AC/DC to 600 A'],['Head','Swiveling clamp'],['Connection','Wireless']], 'SC680 is the broad-function clamp in this comparison. Its swivel head, DC-current capability and connected workflow are concrete reasons to consider the larger tool.'),
  f('sc480','SC480 Wireless Power Clamp Meter','Fixed-head connected alternative','sc480-wireless-power-clamp-meter/','Technicians who want the power-meter workflow without every SC680 feature.','Do not transfer SC680 DC jaw-current or swivel-head features to SC480.',[['Jaw current','AC to 600 A'],['Head','Fixed'],['Connection','Wireless']], 'SC480 is the connected fixed-head alternative. It should be compared by the measurements needed on your systems, especially where DC current or head access changes the choice.'),
  f('sc260','SC260 Compact Clamp Meter','Smaller daily or backup meter','sc260-compact-clamp-meter-with-true-rms/','Technicians needing a smaller instrument for its supported electrical and temperature measurements.','Confirm the required functions and rating; it is not the SC680 in a smaller housing.',[['Jaw current','AC to 400 A'],['Format','Compact'],['Measurement','True-RMS']], 'SC260 prioritizes a compact instrument. It is useful when carrying space matters, but a backup role does not excuse choosing a rating or measurement function below the job requirement.'),
  f('sc440','SC440 Essential Clamp Meter','Dual-display and inrush option','sc440-essential-clamp-meter/','Technicians who want the documented dual-display and inrush feature set.','No assumption of the SC480 wireless power workflow or SC680 DC clamp capability.',[['Jaw current','AC to 400 A'],['Display','Dual'],['Function','Inrush']], 'SC440 provides a middle comparison centered on a dual display and inrush measurement. Choose those functions when they answer a recurring diagnostic question.'),
  f('sc640','SC640 Loaded Clamp Meter','Swivel-head AC alternative','sc640-loaded-clamp-meter/','Technicians wanting a swivel head with the documented AC-current and inrush functions.','SC640 and SC680 have different current and connectivity configurations.',[['Jaw current','AC to 400 A'],['Head','Swiveling clamp'],['Function','Inrush']], 'SC640 emphasizes access through its swivel head without being the full SC680 configuration. That matters more than a similar-looking housing when reaching a suitable conductor.'),
];
const manometers = [
  f('sdmn6','SDMN6 Dual Port Manometer & Pressure Switch Tester','Pressure and switch-test comparison','sdmn6-dual-port-manometer-and-pressure-switch-tester/','Qualified technicians needing the documented manometer and pressure-switch test functions.','Pressure testing is not combustion analysis or proof that a furnace is safe.',[['Ports','Dual pressure ports'],['Extra function','Pressure-switch tester'],['Viewing','Local display']], 'SDMN6 combines pressure measurement with a dedicated pressure-switch testing role. It deserves consideration when that extra function is used, rather than because a larger tool list looks more complete.'),
  f('sdmn5','SDMN5 Dual Port Manometer','Focused differential measurements','dual-port-manometer-sdmn5/','Technicians needing local static, gas and differential pressure measurements within its stated range.','Does not include SDMN6’s pressure-switch pump/testing arrangement.',[['Ports','Dual'],['Range','-60 to +60 inWC'],['Resolution','0.01 inWC mode']], 'SDMN5 is the simpler local-display comparison for two pressure points and their difference. Its range and fine-resolution mode support different measurement tasks; choose the appropriate mode and probes.'),
  f('jl3km2','JL3KM2 Wireless Manometer Probe Kit','Paired connected pressure probes','jl3km2-job-link-system-dual-port-manometer-probe-kit/','Job Link users wanting the documented paired probe kit for remote differential readings.','Requires compatible app viewing; confirm both probes and accessories in the kit.',[['Format','Paired probe kit'],['Connection','Wireless'],['System','Job Link']], 'JL3KM2 moves the readings to a connected workflow. The kit distinction matters: buying one single-port probe is not buying the complete paired measurement arrangement.'),
  f('jl3mn','JL3MN Wireless Manometer Probe','Single-probe system addition','jl3mn-job-link-system-manometer/','Users adding one documented pressure probe to an existing compatible setup.','A single probe is not the two-probe JL3KM2 kit.',[['Ports','Single'],['Connection','Wireless'],['System','Job Link']], 'JL3MN is included as an expansion component, not an equivalent complete kit. It is a sensible purchase when another appropriate probe and a receiving device are already owned.'),
  tool('testo-510i','Testo','510i Wireless Differential Pressure Probe','Testo pressure alternative','https://www.testo.com/en-UK/testo-510-i/p/0560-1510','Testo Smart users who prefer the documented differential-pressure probe.','Requires a supported mobile device; confirm US package and accessories.',[['Role','Differential pressure'],['Viewing','App'],['Connection','Wireless']], '510i offers a connected differential-pressure arrangement within Testo’s app. The linked international manufacturer documentation describes the instrument; confirm the exact US retail package before purchase.'),
];
const psychrometers = [
  f('jl3rh','JL3RH Flex Psychrometer Probe','Remote air-condition readings','jl3rh-job-link-system-flex-psychrometer-probe/','Job Link users measuring air temperature and humidity at suitable locations.','One probe is not a complete paired air-measurement kit, and humidity does not measure airflow.',[['Readings','Dry bulb / wet bulb / RH'],['Format','Flexible probe'],['Connection','Job Link wireless']], 'JL3RH measures air conditions as part of a connected diagnosis. Place it where the actual measurement is required; a temperature split alone does not establish delivered airflow or equipment capacity.'),
  tool('testo-605i','Testo','605i Wireless Thermohygrometer','Testo connected air probe','https://www.testo.com/en-US/testo-605i/p/0560-2605-03','Testo users needing app-based air-temperature and humidity readings.','Requires supported app viewing; paired measurements may need a second instrument.',[['Readings','Temperature and RH'],['Head','Bendable probe'],['Viewing','Testo Smart app']], '605i is a compact connected air-condition probe. Its app workflow can fit an existing Testo kit, while its measuring role remains separate from an airflow instrument.'),
  tool('testo-625','Testo','625 Digital Thermohygrometer (0563 1625)','Standalone-display alternative','https://www.testo.com/en-UK/p/0563-1625','Technicians who prefer a local display with the documented newer 625 configuration.','625 part numbers identify different generations; match 0563 1625 and confirm the US offer.',[['Readings','Temperature and RH'],['Viewing','Local display'],['Connection','App capable']], 'The newer 625 provides a local-display alternative to app-only probes. Compare its generation and complete part number, since older 625 listings describe another instrument configuration.'),
];
const airflow = [
  f('sta2','STA2 In-Duct Hot-Wire Anemometer','Local-display duct measurements','sta2-in-duct-hot-wire-anemometer/','Technicians measuring suitable in-duct air velocity and temperature.','A point velocity reading is not automatically total system airflow; measurement method and duct dimensions matter.',[['Sensor','Hot wire'],['Role','In-duct air velocity'],['Viewing','Local display']], 'STA2 is a dedicated in-duct instrument with a local readout. Use it when probe access and the documented measurement method suit the duct, rather than treating every supply register as the same measurement location.'),
  tool('testo-405i','Testo','405i Hot-Wire Anemometer','Connected duct-probe option','https://www.testo.com/en-US/testo-405i/p/0560-1405','Testo users wanting app-based duct velocity measurements and dimension-based volume calculations.','Calculated volume depends on correct duct dimensions and a representative measurement.',[['Sensor','Hot wire'],['Probe','Telescopic'],['Viewing','Testo Smart app']], '405i provides a connected telescopic probe for duct measurements. Its calculation functions are useful when the input dimensions and measurement method are appropriate.'),
  tool('testo-410i','Testo','410i Vane Anemometer','Connected outlet-velocity option','https://www.testo.com/en-MY/testo-410i/p/0560-1410','Technicians comparing a small-vane connected instrument for suitable outlet readings.','A small vane is not a capture hood; confirm the measurement method and US package.',[['Sensor','Vane'],['Role','Air velocity and temperature'],['Viewing','App']], '410i offers a vane-based alternative to hot-wire duct probes. The linked manufacturer specification describes the model internationally; accessories and local package need confirming.'),
  tool('testo-416','Testo','416 Vane Anemometer (0563 0416)','Small-vane duct alternative','https://www.testo.com/en-UK/testo-416/p/0563-0416','Technicians who prefer a cable-connected telescopic small vane and local display.','New and older 416 part numbers differ; confirm 0563 0416 and the local package.',[['Sensor','16 mm vane'],['Probe','Telescopic'],['Viewing','Local and app']], 'The newer 416 uses a small vane on a telescopic probe. This is a distinct access and sensor choice from a large vane for a grille.'),
  tool('testo-417','Testo','417 Large Vane Anemometer','Large-vane outlet comparison','https://www.testo.com/en-UK/testo-417/p/0560-4170','Technicians measuring at suitable grilles or comparing compatible funnel accessories.','Funnel and flow-straightener accessories must be checked separately; match the generation and US package.',[['Sensor','Large vane'],['Role','Outlet measurements'],['Viewing','Local display']], '417 is the larger-vane alternative for an outlet-oriented measurement workflow. Its accessories and the geometry of the outlet affect which measurement approach is appropriate.'),
];
const temperatures = [
  f('st4','ST4 Dual Temperature Meter','Two-channel contact measurements','st4-dual-temperature-meter/','Technicians comparing two K-type contact-temperature measurements.','Pipe clamps or application-specific probes may need purchasing separately.',[['Inputs','Two K-type thermocouples'],['Readings','T1 / T2 / difference'],['Viewing','Local display']], 'ST4 is a two-channel temperature instrument rather than a pressure manifold. Select the probes for the actual surface or air measurement; its included bead probes do not make every pipe-clamp accessory redundant.'),
  f('spk1','SPK1 Pocket Thermometer','Compact contact-temperature tool','spk1-pocket-knife-style-thermometer/','Technicians needing a small folding contact probe for supported readings.','Not a two-channel temperature instrument or wireless pipe-clamp kit.',[['Method','Contact probe'],['Format','Folding pocket tool'],['Viewing','Local display']], 'SPK1 fills a compact spot-measurement role. It can be convenient for a daily bag when comparison of two simultaneous channels is not required.'),
  f('spk2','SPK2 Folding In-Duct Thermometer','Pocket in-duct comparison','spk2-folding-pocket-in-duct-thermometer/','Technicians needing the documented folding in-duct probe arrangement.','A temperature reading alone cannot establish total airflow or system performance.',[['Method','In-duct contact probe'],['Format','Folding'],['Viewing','Local display']], 'SPK2 is the in-duct pocket alternative. Its value is convenient appropriate placement rather than a claim that it replaces humidity and airflow instruments.'),
  f('spk3','SPK3 Rod & IR Thermometer','Contact and infrared spot readings','spk3-rod-and-ir-temperature-pocket-style-tool/','Technicians needing the documented contact and infrared measurement options in one pocket tool.','IR readings depend on surface properties and spot geometry; they are not air or internal-fluid temperatures.',[['Methods','Rod probe and infrared'],['Format','Pocket tool'],['Power','Two AAA batteries']], 'SPK3 combines two distinct measurement methods. Use the contact probe and infrared function for the applications described by the manufacturer, not as interchangeable readings of every material.'),
  f('sig1','SIG1 Infrared Thermometer','Separate IR spot-check tool','sig1-gun-style-ir-thermometer/','Technicians comparing a separate gun-style surface-temperature instrument.','Cannot see through panels or replace contact temperature and combustion tests.',[['Method','Infrared surface reading'],['Format','Gun style'],['Viewing','Local display']], 'SIG1 is the dedicated infrared alternative. Spot size, emissivity and surface access determine whether the indication is useful for the question being investigated.'),
];
const cores = [
  f('vc1g','VC1G Valve Core Removal Tool','Sight-glass core handling','vc1g-valve-core-removal-tool-with-sight-glass/','Qualified technicians wanting to see core engagement at a compatible service port.','Match port size, refrigerant approval, pressure rating and the documented handling procedure.',[['Service fitting','1/4 inch'],['Feature','Sight glass'],['Role','Valve core removal']], 'VC1G adds a sight glass for the documented core-handling task. It is a connection tool within a complete refrigerant setup, not an automatic leak-prevention or safety device.'),
  f('vc1','VC1 Valve Core Removal Tool','Simpler core-removal option','vc1-valve-core-removal-tool/','Technicians who want the simpler compatible core-tool configuration.','Does not add the sight-glass feature of VC1G.',[['Service fitting','1/4 inch'],['Role','Valve core removal'],['Design','Single ball valve']], 'VC1 covers the simpler core-removal arrangement. Choose it when the basic configuration fits the service port and you do not need the added observation feature.'),
  f('vc2g','VC2G Dual Valve Core Removal Tool','Additional gauge isolation','vc2g-valve-core-removal-tool-with-dual-ball-valves-and-sight-glass/','Technicians needing the documented dual-valve arrangement and sight glass.','Extra valves change the arrangement; follow the exact tool instructions.',[['Service fitting','1/4 inch'],['Feature','Sight glass'],['Valves','Dual ball valves']], 'VC2G adds a second valve to the sight-glass configuration. That is useful when its isolation arrangement fits the gauge setup, rather than because more fittings are always better.'),
  tool('appion-mgavct','Appion','MGAVCT 1/4-Inch Valve Core Removal Tool','Appion 1/4-inch alternative','https://appiontools.com/mgavct/','Qualified technicians selecting a compatible 1/4-inch core-removal tool.','Confirm the actual port and tool instructions; MGAVCR is the different 5/16-inch version.',[['Service fitting','1/4 inch'],['Role','Valve core removal'],['Model','MGAVCT']], 'MGAVCT is Appion’s 1/4-inch alternative. Exact port fit matters more than brand preference when adding a core tool to evacuation or recovery equipment.'),
  tool('appion-mgavcr','Appion','MGAVCR 5/16-Inch Valve Core Removal Tool','For a compatible 5/16-inch port','https://appiontools.com/mgavcr/','Qualified technicians whose documented service connection is 5/16 inch.','Not interchangeable with a 1/4-inch tool simply because the bodies look similar.',[['Service fitting','5/16 inch'],['Role','Valve core removal'],['Model','MGAVCR']], 'MGAVCR exists for a different service fitting from MGAVCT. Choose it only when the connection, rating and approved refrigerant application match.'),
];
const plumbingTools=(slug:string)=>plumberCategories.find(c=>c.slug===slug)!.products.map(p=>({...p,assessment:{...p.assessment}}));

export const hvacCategories:Category[] = [
  group('best-vacuum-pumps-for-hvac','Best Vacuum Pumps for HVAC: Capacity, Oil Changes and Refrigerant Fit','Evacuation & Recovery','Compare VP87 for a DC-motor 8 CFM setup, VP67 for a smaller Fieldpiece option, VPX7 for higher nominal capacity, VP833 for its documented A3 role, and JB DV-200N for a conventional alternative.','These are documented-capability comparisons, not timed evacuation results.',[['Compare the whole evacuation path','The pump, hose diameter, connections, restrictions, oil condition and system volume work together. Nominal CFM is not a promised completion time.'],['Keep compatibility model-specific','A3 compatibility on VP833 does not apply to all Fieldpiece pumps. The exact refrigerant and current machine instructions decide suitability.'],['Budget for measurement and maintenance','Choose a suitable standalone vacuum gauge and the required hoses. Oil maintenance and an appropriate decay assessment are part of the equipment plan.']],[['Is a bigger pump always better?','No. A restrictive connection can limit the setup. Compare capacity after confirming the intended system, hoses and service access.'],['Does a vacuum pump recover refrigerant?','No. Recovery equipment and an appropriate recovery cylinder serve a different purpose.']], [j.evacuation,j.commission,j.van],pumps,[['Choose VP87 for the arrangement, not a speed promise','The DC motor and RunQuick oil-change arrangement are reasons to compare VP87 for recurring work. We have not timed it against these alternatives. System volume, port access, hose choice and oil condition prevent a nominal pump-capacity figure from describing a completed evacuation.'],['Know when a different model is required','VP833 is the application-specific A3 comparison. JB suffixes can change electrical and compatibility details. Match the complete model and the current documentation before committing to a job or a purchase.'],['Plan a complete setup','The pump-only price omits a suitable gauge, hoses, compatible fittings and maintenance supplies. Choose equipment around the actual work and required measurement method; do not buy a larger pump to compensate for an unsuitable setup.']]),
  group('best-refrigerant-recovery-machines-for-hvac','Best Refrigerant Recovery Machines for HVAC: Digital and Twin-Cylinder Options','Evacuation & Recovery','Compare Fieldpiece MR45, Appion G5Twin, NAVAC NRDD, Robinair RG6 and JB F6-DP by the approved refrigerants, interface and complete recovery setup.','No recovery speeds were independently measured. Amazon availability and manufacturer-approved seller status are separate checks.',[['Check the actual refrigerant','Confirm current manufacturer approval for the exact unit and refrigerant; similar suffixes can describe a different machine.'],['Include the container and weight monitoring','Recovery requires suitable cylinders, hoses and weight monitoring. A machine’s stop function does not replace cylinder limits and the required procedure.'],['Compare maintenance and support','Consider service parts, authorized distribution, local repair options and the work volume that justifies owning the equipment.']],[['Can I use a vacuum pump instead?','No. An evacuation pump is not a recovery machine.'],['Is an Amazon offer automatically an authorized seller?','No. Appion specifically states Amazon and eBay are not approved distributors. Confirm eligibility directly with the manufacturer.']], [j.recovery,j.commission,j.van],recovery,[['When MR45 fits the business','The digital interface and variable-speed DC motor make MR45 a useful comparison for recurring recovery work. The decision depends on approved refrigerants, available service and the complete setup rather than an unmeasured fastest-machine claim.'],['Choose the exact regional model','US power requirements and refrigerant compatibility need checking against the actual part number. NRDD, NRDDF and JB regional suffixes are not interchangeable offers.'],['Include everything around the machine','The machine is one business purchase. The correct cylinder, scale, hoses, filters, maintenance and required qualified-work procedure are separate parts of the equipment plan.']]),
  group('best-refrigerant-leak-detectors-for-hvac','Best Refrigerant Leak Detectors for HVAC: Infrared, Heated Diode and Gas Scope','Refrigeration & Diagnostics','Start with DR82 for an infrared pinpointing comparison, DR58 for heated diode, DRX3 for its broader documented gas scope, or the INFICON D-TEK instruments for a different sensing workflow.','Leak indications require appropriate confirmation. Refrigerant approval and hazardous-location suitability must stay specific to each model.',[['Choose by gas and environment','Match the actual refrigerant or tracer gas and permitted environment, not just the words leak detector.'],['Compare sensing and maintenance','Infrared and heated-diode instruments differ in sensor care and operating behavior. Read the specified checks, filters and replacement requirements.'],['Separate hunting from pinpointing','Stratus offers cloud hunting as well as pinpointing. That is a different workflow from choosing an instrument for a known small suspect area.']],[['Can DR82 replace a combustible-gas detector?','Do not assume that. Use only its documented gas applications and operating environment.'],['Should I pick only by advertised sensitivity?','No. Approved gas, sensor maintenance, operating method and the kind of investigation matter too.']], [j.leak,j.service,j.commission],detectors,[['Why DR82 is a useful first comparison','Its infrared sensing approach provides a clear alternative to DR58’s heated diode. We have not compared detection speed, false indications or sensitivity in field conditions; the choice is based on documented design and application.'],['Broader gas support changes the purchase','DRX3’s broader listed scope is specific to DRX3. A similar brand name or housing is not permission to use another detector in a combustible environment. Read the current manual for the gas and conditions involved.'],['Keep the original feedback in context','Owner reports can explain handling and maintenance preferences, but a successful anecdote does not establish that a detector will identify every leak. Match the source to the model and use the documented confirmation method.']]),
  group('best-micron-gauges-for-hvac','Best Micron Gauges for HVAC: Standalone and Connected Vacuum Measurement','Evacuation & Recovery','Compare MG44 for local and Job Link viewing, Testo 552i for a connected probe, and BluVac+ LTE, Pro or Micro for different dedicated-gauge configurations.','The measurement location and setup matter; an ultimate pump vacuum is not the same thing as the system’s verified condition.',[['Decide where readings will be viewed','A local screen works without app viewing. A screenless probe needs a compatible receiving device.'],['Choose the record workflow','Compare trend, hold-test and report functions in the exact version. Similar family names do not guarantee identical features.'],['Keep the gauge suitable and maintained','Follow cleaning and connection instructions, protect the sensor and record measurement location with the result.']],[['Does my pump need a separate micron gauge?','A suitable gauge measures the system’s vacuum. A pump’s advertised capability does not prove the system reached it.'],['Is Testo 552i a standalone-screen instrument?','No. Its readings need a compatible app or receiving instrument.']], [j.evacuation,j.commission],gauges,[['MG44 separates measurement from the pump','A local display and compatible connected viewing are reasons to compare MG44. The instrument supports a measurement workflow; it does not select the correct evacuation target or decide whether a system is ready.'],['Choose the receiving device deliberately','For 552i, include a supported phone or manifold in the plan. If app access is inconvenient, a local-display gauge may be a better practical fit.'],['Compare BluVac versions by the required record','LTE, Pro and Micro deserve separate assessments. A business needing detailed repeatable records may value Pro functions; a smaller instrument may be appropriate for simpler work.']]),
  group('best-refrigerant-scales-for-hvac','Best Refrigerant Scales for HVAC: Local Displays and Connected Weighing','Refrigeration & Diagnostics','Choose SR47 for a Job Link weighing workflow, SRS1 for a simpler smaller-capacity scale, Testo 560i or NAVAC NRS2A for their connected systems, or CPS CC220 for a corded handheld readout.','Displayed weight and automatic valve control are different capabilities. Check every scale-only and valve-inclusive package separately.',[['Match capacity and resolution','Consider the complete cylinder weight, the required charge measurement and the published resolution.'],['Choose a reliable viewing arrangement','Decide between a corded handheld, wireless display and app integration according to actual access on the job.'],['Confirm automation components','A connected scale alone is not an automatic charging kit. Compatible valves, receiving devices and instructions are additional requirements.']],[['Does a scale prevent recovery-cylinder overfill?','No. Weight monitoring supports the required cylinder limits and procedure; it does not replace them.'],['Does a Testo 560i offer always include a valve?','No. Confirm the exact scale and valve package in the listing.']], [j.recovery,j.commission,j.service],scales,[['SR47 fits a connected measurement plan','Its useful distinction is organizing weight measurements with compatible instruments. That can improve documentation convenience without changing the requirement to choose and monitor the cylinder correctly.'],['Buy the complete configuration','An automatic charging workflow requires more than the platform. Compare the actual valve, receiving devices, supported functions and package number before comparing prices.'],['Simpler scales remain valid alternatives','A locally viewed SRS1 or corded CC220 can be appropriate when its capacity and resolution cover the work. Connectivity is useful only when it improves the workflow the technician actually uses.']]),
  group('best-clamp-meters-for-hvac','Best Clamp Meters for HVAC: Compact, Inrush and Connected Functions','Electrical & Airside','Compare SC680 for its broad AC/DC-current and connected functions, SC480 for fixed-head connected measurements, SC260 for compact carrying, SC440 for dual display and inrush, or SC640 for swivel access.','These five Fieldpiece models have different capabilities. We have not tested accuracy, head clearance or durability.',[['List the actual measurements','Separate AC jaw current, DC jaw current, inrush, capacitance and other functions. A meter reading DC voltage does not necessarily measure DC jaw current.'],['Check category and access','The complete meter-and-lead arrangement must meet the work environment. Head size and swivel access matter after rating and function requirements.'],['Do not buy for feature count','A larger connected instrument is useful when those functions are recurring. A compact tool can be sufficient only when it meets the same job requirements.']],[['Are SC480 and SC680 the same meter?','No. Compare current type, head design and documented functions separately.'],['Does owning a clamp authorize electrical work?','No. Use the required training, controls, procedure and suitable instrument for the specific measurement.']], [j.service,j.commission,j.apprentice],clamps,[['Why start the comparison with SC680','DC jaw-current measurement and a swivel head distinguish SC680 from narrower models. Those features are worthwhile when the systems and access conditions call for them, not because the broadest specification is always best.'],['Read smaller models on their own terms','SC260, SC440 and SC640 cover different carrying and measurement choices. Use the actual documented inrush and current capabilities rather than treating similar model names as interchangeable.'],['Keep measurement and authorization separate','Choose the instrument and leads for the electrical environment and follow the required qualified-work process. A clamp meter is not a universal substitute for isolation verification or another instrument required by the job.']]),
  group('best-manometers-for-hvac','Best Manometers for HVAC: Static Pressure, Differential and Probe Kits','Electrical & Airside','Compare SDMN6 when its pressure-switch tester is useful, SDMN5 for local differential pressure, JL3KM2 for a paired connected kit, JL3MN for one additional probe, or Testo 510i for a different app workflow.','Pressure measurements are not a complete furnace safety or combustion assessment.',[['Choose one or two measurement points','A single-port probe is an expansion component. A differential kit and its correct tubing/probes cover a different setup.'],['Separate pressure from combustion','A manometer measures pressure. Combustion analysis, CO assessment and appliance safety checks require their own appropriate instruments and procedures.'],['Confirm range and resolution','Gas and static-pressure tasks may need different ranges and fine resolution. Check the actual mode and approved test application.']],[['Does JL3MN equal the JL3KM2 kit?','No. JL3MN is a single probe; JL3KM2 is the documented paired kit.'],['Can a manometer replace a combustion analyzer?','No. They measure different things.']], [j.airflow,j.service,j.commission],manometers,[['SDMN6 adds a specific testing role','Compare it when its pressure-switch testing functions are part of trained recurring work. If the requirement is only static or differential pressure, a simpler instrument may be a better purchase.'],['Local and connected arrangements differ','A paired connected kit can support remote readings. A local dual-port instrument keeps the result at the tool. Consider placement and documentation before choosing the viewing method.'],['Pressure needs context','Keep the test location, mode and appliance or duct requirements with the reading. Neither a pressure result nor an app calculation independently establishes safe combustion or total delivered airflow.']]),
  group('best-psychrometers-for-hvac','Best Psychrometers for HVAC: Air Temperature and Humidity','Electrical & Airside','Compare JL3RH and Testo 605i for connected air-condition readings, or the newer Testo 625 for a local display. These three cover distinct viewing and placement choices without padding the list.','Temperature, humidity and derived wet-bulb values are different from a direct airflow measurement.',[['Match measurement location','Room conditions and in-duct conditions can differ. Choose a probe that can be placed at the required location.'],['Plan paired measurements','A single probe may not cover simultaneous supply and return measurements. Check kit contents and the planned receiving device.'],['Keep derived readings in context','Document dry bulb, humidity and measurement locations. A temperature split alone does not diagnose every fault.']],[['Is a psychrometer an airflow meter?','No. Air conditions and air velocity are separate measurements.'],['Are all Testo 625 listings the same?','No. The comparison identifies the newer 0563 1625 configuration; verify the exact part number and US package.']], [j.service,j.airflow,j.commission],psychrometers,[['JL3RH fits a connected diagnosis','The flexible probe and supported readings are reasons to compare it for air-condition measurements. Its connected range does not tell you where the probe should be placed or establish total airflow.'],['Choose the screen arrangement','An app probe can fit an existing kit, while a local-display instrument can reduce phone dependence. Both still need appropriate placement and current calibration and maintenance practices.'],['Avoid diagnosing from one number','Record conditions with other relevant measurements and the equipment requirements. A single temperature split, humidity percentage or derived wet-bulb reading is not a complete performance diagnosis.']]),
  group('best-anemometers-for-hvac','Best Anemometers for HVAC: Duct Probes and Outlet Measurements','Electrical & Airside','Compare STA2 and 405i for hot-wire duct access, 410i for a connected small vane, the newer 416 for a telescopic 16 mm vane, or 417 for a larger outlet-oriented vane.','These are velocity instruments and calculated-flow arrangements, not substitutes for every capture-hood or balancing task.',[['Choose by access geometry','A narrow duct probe and a large vane at a grille do not take the same measurement. Match the sensor and available approach.'],['Use representative measurements','A single point can misrepresent a non-uniform flow. Follow the instrument method and enter dimensions correctly for a calculated volume.'],['Match accessory and generation','Funnel accessories, telescopes and current app-connected generations change the setup. Compare the complete part number.']],[['Is one register reading total system airflow?','No. Measurement geometry, method and system layout matter.'],['Do I need a capture hood instead?','Some tasks require one. Select the measurement method and equipment required for the actual commissioning or balancing scope.']], [j.airflow,j.commission],airflow,[['STA2 provides a local duct-probe arrangement','Its hot-wire probe and local display make it a useful first comparison for suitable duct measurements. We have not independently compared its accuracy or usability in different duct geometries.'],['Vane size changes the application','The 416’s small telescopic vane and the 417’s larger outlet-oriented vane serve different access conditions. Choose the location and method first, then the instrument.'],['Calculated volume needs sound inputs','An app can calculate a result using entered dimensions, but it cannot make an unrepresentative velocity reading representative. Keep the measurement location, geometry and method with the record.']]),
  group('best-temperature-tools-for-hvac','Best Temperature Tools for HVAC: Contact Probes and Infrared Spot Checks','Electrical & Airside','Start with ST4 for two contact-temperature channels, choose SPK1 or SPK2 for a pocket probe, SPK3 for combined rod and IR readings, or SIG1 for a separate infrared tool.','Contact and infrared measurements answer different questions. None of these is a thermal camera or combustion analyzer.',[['Choose the measurement method','Contact probes and infrared surface readings are not interchangeable. Match the sensor to air, pipe or surface requirements.'],['Check the actual probes','A meter accepting K-type inputs still needs suitable probes for the work. Confirm included bead probes versus separately required pipe clamps.'],['Understand infrared limits','Emissivity, reflections and the spot’s size affect surface readings. Infrared tools do not measure through panels.']],[['Can an IR thermometer measure air temperature?','It measures radiation from surfaces in its field of view, not a direct air-temperature reading.'],['Does ST4 include every application probe?','No. Confirm the supplied probes and budget for suitable accessories.']], [j.service,j.apprentice,j.commission],temperatures,[['ST4 is a dedicated two-channel comparison','It provides contact-temperature channels without requiring a refrigerant manifold. That can suit diagnostic work where temperature difference is the relevant question and the probes are correctly chosen.'],['Pocket tools have a narrower purpose','A small folding instrument can earn daily bag space for supported spot readings. It does not become a full paired measurement kit just because it is convenient.'],['Treat infrared as a surface indication','SPK3 and SIG1 serve documented surface-measurement roles. Compare spot geometry and surface properties before drawing conclusions, and confirm with another appropriate method when the question requires it.']]),
  group('best-valve-core-removal-tools-for-hvac','Best Valve Core Removal Tools for HVAC: Port Size and Gauge Isolation','Evacuation & Recovery','Compare VC1G for visible core engagement, VC1 for a simpler arrangement, VC2G for its second valve, or Appion MGAVCT and MGAVCR for their different service-port sizes.','These are components in a trained refrigerant-handling workflow. Port, pressure and refrigerant compatibility require exact-model checks.',[['Start with the service fitting','1/4-inch and 5/16-inch fittings are different. An adapter or similarly shaped tool is not automatic compatibility.'],['Choose the valve arrangement','Sight glasses and additional valves change handling and gauge isolation. Follow the instructions for the specific tool.'],['Keep the complete setup suitable','Core tools, gauges, hoses and equipment each have their own ratings and handling requirements.']],[['Are MGAVCT and MGAVCR interchangeable?','No. They are listed for different service fitting sizes.'],['Does a sight glass guarantee safe core removal?','No. It is an observation feature within the documented procedure.']], [j.evacuation,j.recovery,j.commission],cores,[['VC1G adds an observation feature','The sight glass is a meaningful difference when observing core engagement is useful. It does not eliminate the need for correct fit, a suitable refrigerant setup and the tool’s handling instructions.'],['Avoid buying by appearance','The Appion alternatives have similar bodies but different fittings. Fieldpiece offers separate port fittings and valve arrangements. Check the actual service connection before comparing the price of a tool.'],['Choose components as a system','A core tool is one connection in a larger evacuation, recovery or charging arrangement. Plan the gauge isolation and hose configuration using the manuals for each component.']]),
  group('best-tubing-cutters-for-hvac','Best Tubing Cutters for HVAC: Tight Access and Copper Preparation','Installation & Carry','Compare RIDGID 101 and 118 for close access, RIDGID 151 or KNIPEX TubiX for a larger adjustable cutter, or Milwaukee 2471-20 for its documented powered copper application.','These are cutting comparisons, not a complete refrigerant-tube preparation kit. Nominal plumbing sizes and actual outside diameter can differ.',[['Use actual outside diameter','Match the cutter capacity and wheel to the material and actual tube OD. Do not assume a nominal pipe size equals the refrigerant tube measurement.'],['Check rotation clearance','A larger cutter or powered tool may not fit even when the tube is within its capacity.'],['Plan the preparation that follows','The required deburring, cleanliness, joining method and inspection depend on the installed system. A cutter is not the whole process.']],[['Will a powered plumbing cutter fit every refrigerant tube?','No. Check its documented material and exact size support, including nominal-size versus OD distinctions.'],['Is cutting the whole preparation process?','No. Follow the installed system’s preparation, joining and verification requirements.']], [j.commission,j.van,j.apprentice],plumbingTools('best-tubing-cutters-for-plumbers'),[['Close-quarters tools solve an access problem','RIDGID 101 is a compact alternative when available rotation space is limited. Larger quick-adjust cutters may be easier on an open installation but need their own working clearance.'],['Keep the size convention visible','Refrigeration work commonly specifies tube outside diameter. A powered cutter marketed by nominal plumbing sizes needs careful checking before it is treated as a refrigeration-tube purchase.'],['Keep clean preparation equipment separate','Choose the joining and preparation method required for the actual system. Tool storage, clean handling and appropriate inspection matter alongside selecting a cutter.']]),
  group('best-tool-bags-for-hvac','Best Tool Bags for HVAC: Daily Diagnosis and Van Organization','Installation & Carry','Choose TP-XL for a compact daily kit, TECH-MCT for a structured enclosed bag, Klein’s smaller tote or CLC 1539 for other pocket arrangements, or PACKOUT 15-inch for an existing modular setup.','A carrying plan is not a recommendation to buy every bag. Keep bulky refrigerant machines and contamination-prone equipment separately organized.',[['Choose the daily load first','Fit the actual meter, leads, hand tools and lighting before choosing a bag by pocket count.'],['Protect measuring equipment','Cases, lead storage and contamination separation matter more than carrying every tool in one open compartment.'],['Plan the van separately','Recovery machines, pumps, hoses and cylinders need their own suitable transport and storage arrangements.']],[['Should pumps and all instruments go in one bag?','Usually they need different carrying and protection arrangements. Choose a daily diagnosis bag and suitable separate machine storage.'],['Is PACKOUT necessary?','No. It is useful only if that modular transport arrangement fits an existing setup.']], [j.van,j.apprentice,j.service],plumbingTools('best-tool-bags-for-plumbers'),[['TP-XL keeps the daily selection deliberate','A compact pouch encourages choosing the tools used on a typical call. That can reduce repeated searching, but it should not force a meter or fragile probe into unsuitable protection.'],['Separate instruments from dirty equipment','Keep sensors, leads and measurement accessories protected. Hoses, machines and workpieces can bring oil or debris that does not belong against delicate instruments.'],['Choose a system that fits the route','A tote, enclosed bag and modular van system each make different carrying tradeoffs. Compare the actual load, access and transport method before buying for branding or pocket count.']]),
];

export const hvacManifoldAdditions = [
  f('sm482v','SM482V SMAN 4-Port Digital Manifold','Current four-port Job Link option','sm482v-sman-wireless-refrigerant-4-port-manifold/','Job Link users comparing the current four-port manifold with the older SM480V.','Confirm probes, hoses and the exact approved refrigerants; do not transfer new-model features to SM480V.',[['Ports','Four'],['Vacuum port','3/8 inch'],['System','Job Link']], 'SM482V is the current four-port model listed by Fieldpiece. It is the starting comparison for a new Job Link-centered purchase; the preserved SM480V review remains an older-generation reference.'),
  f('sm382v','SM382V SMAN 3-Port Digital Manifold','Current three-port Job Link option','sm382v-sman-wireless-refrigerant-3-port-manifold/','Job Link users preferring the current three-port arrangement.','The three-port layout is not the SM482V four-port evacuation arrangement.',[['Ports','Three'],['Vacuum reading','Built-in micron measurement'],['System','Job Link']], 'SM382V provides the current three-port comparison. Choose the connection arrangement and complete accessory package required for your work rather than assuming every service kit needs four ports.'),
];
const affiliate=(p:ElectricianCandidate)=>`https://www.amazon.com/s?k=${encodeURIComponent(`${p.brand} ${p.model}`)}&tag=robbieom0e-20`;
export const hvacCatalogGuides:Guide[]=hvacCategories.map(c=>({trade:'hvac',tradeName:'HVAC Technicians',slug:c.slug,title:c.title,cluster:c.cluster,keyword:c.slug.replace(/-/g,' '),meta:`${c.title.split(':')[0]}: compare ${c.products.map(p=>p.model.split(' ')[0]).join(', ')} by application, configuration and limitations.`,workflowSlugs:c.workflowSlugs,products:c.products.map((p,i)=>({brand:p.brand,model:p.model,role:p.role,productId:p.id,assessment:p.assessment,reviewSlug:i===0?`hvac-${p.id}-review`:undefined,url:affiliate(p)}))}));
export function manifoldProducts(){return hvacManifoldAdditions.map(p=>({brand:p.brand,model:p.model,role:p.role,productId:p.id,assessment:p.assessment,reviewSlug:`${p.id}-review`,url:affiliate(p)}));}
const review=(p:ElectricianCandidate,slug:string,guideSlug:string,guideTitle:string,sections:Category['sections'],faqs:Category['faqs']):ProductReview=>({slug,trade:'hvac',tradeName:'HVAC Technicians',guideSlug,guideTitle,brand:p.brand,model:p.model,role:p.role,title:`${p.brand} ${p.model} Review: HVAC Job Fit and Alternatives`,meta:`${p.brand} ${p.model.split(' ')[0]} HVAC buying assessment: documented features, job fit, package checks and limitations. Research-based review.`,amazonUrl:affiliate(p),...p.assessment,sections,faqs:[...faqs,{q:'Was this tool independently tested?',a:'No. This is a research-based buying assessment using manufacturer documentation, not a claim of hands-on testing or measured comparative performance.'}]});
export const hvacCatalogReviews:ProductReview[]=[...hvacCategories.map(c=>review(c.products[0],`hvac-${c.products[0].id}-review`,c.slug,c.title,c.sections,c.faqs)),...hvacManifoldAdditions.map(p=>review(p,`${p.id}-review`,'best-digital-manifolds-for-hvac','Best Digital Manifolds for HVAC',[
  {heading:'Current model versus the preserved older review',body:`${p.model} is listed in Fieldpiece’s current manifold range. The original SM480V route is preserved for an older-generation comparison. Match the exact model rather than transferring specifications between the two generations.`},
  {heading:'Buy the connection arrangement you need',body:'Compare three and four ports by the evacuation and service setup you actually use. Temperature probes, hoses and other accessories still need checking in the complete offer.'},
  {heading:'Keep the documented application with the readings',body:'A refrigerant list, pressure rating and instrument calculation do not authorize a service procedure. Use the actual equipment instructions, appropriate qualified-work controls and required verification.'},
],[{q:'Is this the same tool as SM480V?',a:'No. This is a different current-generation model. The older product retains its own page and specifications.'}]))];
