import { guides, hubs } from './data';
import { hvacJobs } from './hvac-catalog';
import type { Workflow, WorkflowTool } from './workflows';
type Pick = [string,string,string,WorkflowTool['priority']];
function kit(slug:string,title:string,summary:string,stages:[string,string][],picks:Pick[],notes:string[],question:string,answer:string):Workflow {
  const tools=picks.map(([id,stage,why,priority])=>{
    const guide=guides.find(g=>g.trade==='hvac'&&g.products.some(p=>p.productId===id));
    const product=guide?.products.find(p=>p.productId===id);
    if(!guide||!product)throw new Error(`Missing HVAC kit product: ${id}`);
    return {stage,type:guide.title.replace(/^Best /,'').split(' for HVAC')[0],name:`${product.brand} ${product.model}`,why,priority,amazonUrl:product.url,guideUrl:`/hvac/${guide.slug}/`,reviewUrl:product.reviewSlug?`/reviews/${product.reviewSlug}/`:undefined};
  });
  return {trade:'hvac',tradeName:'HVAC Technicians',slug,title,meta:summary,summary,keyword:slug.replace(/-/g,' '),heroImage:hubs.find(h=>h.slug==='hvac')!.image,stages:stages.map(([name,description])=>({name,description})),tools,notes,
    faqs:[{q:question,a:answer},{q:'Do I need every item before starting?',a:'No. Buy the core equipment required by your employer and the work you are trained and authorized to do. Useful and upgrade tools are conditional choices, not an instruction to buy the whole shortlist.'},{q:'Are these complete retail kits?',a:'No. These are job-based buying plans. Confirm power equipment, probes, hoses, fittings and other separately required items in the exact retail packages.'},{q:'Were these tools field-tested by TradeGear HQ?',a:'No. Recommendations use documented capabilities and job-fit analysis. Owner-feedback drafts are separately attributed and are not our own test results.'}]};
}
const j=hvacJobs;
export const hvacWorkflows:Workflow[]=[
  kit(j.service,'HVAC Residential Service Call Tool Kit: Electrical, Airside and Refrigerant Decisions','Plan the daily diagnosis bag first: electrical measurements, air conditions and appropriate pressure checks. Bring refrigerant equipment only when the identified job requires it.',
    [['1. Establish the complaint','Record equipment, operating conditions and the reported symptom before choosing a diagnostic path.'],['2. Check the relevant systems','Use the appropriate qualified-work process and instruments for electrical and airside measurements.'],['3. Investigate the refrigerant circuit when justified','Confirm the diagnostic need, refrigerant and permitted equipment before adding connections.'],['4. Verify and document','Complete the equipment-specified checks and record the conditions with the results.']],
    [['fieldpiece-sc680','Electrical diagnosis','Broad electrical functions when the complete instrument and lead arrangement meets the measurement environment.','Core'],['fieldpiece-jl3rh','Air conditions','Temperature and humidity readings at appropriate locations; a paired setup may require another probe.','Useful'],['fieldpiece-sdmn5','Pressure checks','Local static and differential pressure where the correct probes and method are available.','Useful'],['fieldpiece-st4','Temperature checks','Two contact-temperature channels with probes suitable for the actual measurement.','Core'],['fieldpiece-sm482v','Conditional circuit checks','Current four-port manifold when the diagnosis calls for supported refrigerant-side measurements.','Useful'],['fieldpiece-dr82','Leak investigation','Infrared detector only for its documented gases and operating conditions.','Useful'],['veto-tpxl','Daily carry','Keep the selected hand tools and instruments accessible and separately protected.','Useful']],
    ['Employer-required PPE, isolation equipment, hand tools, lighting, consumables and appliance-specific instruments are additional requirements.','Furnace work may require a suitable combustion analyzer and CO assessment equipment. A manometer or temperature tool cannot replace them.'],
    'Should I connect a manifold on every visit?','Choose measurements according to the diagnostic need and equipment requirements. This kit does not recommend opening the refrigerant circuit on every service visit.'),
  kit(j.commission,'HVAC Heat Pump Commissioning Tool Kit: Prepare, Evacuate, Measure and Record','Build a commissioning equipment plan around the installed system and refrigerant: clean tube preparation, suitable evacuation equipment, separate vacuum measurement and documented operating checks.',
    [['1. Match the system requirements','Identify refrigerant, approved connections, required checks and equipment compatibility.'],['2. Prepare the installation','Use suitable clean cutting and joining equipment for the actual tube and installed system.'],['3. Complete the specified evacuation and charge work','Use the required trained procedure with compatible pump, gauge, scale and connection equipment.'],['4. Check operation and record','Record relevant electrical, airside and refrigerant results with operating conditions.']],
    [['ridgid-40617','Tube preparation','Compact cutter for supported material and actual tube outside diameter; preparation and joining need their own tools.','Core'],['fieldpiece-vp87','Evacuation equipment','8 CFM pump only when its documented refrigerant application fits the installed system.','Core'],['fieldpiece-mg44','Vacuum measurement','Separate system vacuum measurement and the specified decay assessment.','Core'],['fieldpiece-vc1g','Compatible connection','Sight-glass core tool when port, rating and the equipment procedure permit it.','Useful'],['fieldpiece-sm482v','Operating measurements','Current manifold with the appropriate temperature probes and hoses checked in the offer.','Core'],['fieldpiece-sr47','Weight monitoring','Connected refrigerant weighing with cylinder limits and charging requirements separately observed.','Core'],['fieldpiece-sc680','Electrical checks','Appropriate rated electrical measurements according to the commissioning scope.','Core'],['fieldpiece-jl3rh','Airside conditions','Air temperature and humidity measurements alongside the required airflow assessment.','Useful']],
    ['Confirm additional pressure-test equipment, appropriate regulator and gas, joining tools, torque tools, required detectors and commissioning paperwork.','These are purchasing roles, not a charging procedure or target-value guide. The installed equipment instructions decide the required checks.'],
    'Can I use this same equipment for every heat pump?','No. Refrigerant, service connections, required ratings and equipment approvals vary. Confirm the exact setup for the installed system.'),
  kit(j.evacuation,'HVAC Evacuation Tool Kit: Pump, Micron Gauge and Connection Plan','Compare the complete evacuation path rather than the largest pump figure. Combine a suitable pump, dedicated vacuum gauge and compatible low-restriction connections with the required verification method.',
    [['1. Confirm readiness','Establish that the system and work are ready for the equipment-specified evacuation stage.'],['2. Build a suitable measurement path','Select pump, gauge, hoses and compatible connection components.'],['3. Maintain measurement quality','Follow oil, gauge cleaning and instrument setup instructions.'],['4. Assess and record the result','Use the specified assessment and retain measurement location and conditions.']],
    [['fieldpiece-vp87','Pump','DC-motor 8 CFM option for the documented application, not a promised completion time.','Core'],['fieldpiece-mg44','Measure','Local and connected vacuum readings separate from the pump rating.','Core'],['fieldpiece-vc1g','Connect','Conditional core-handling tool matched to the service fitting and procedure.','Useful'],['fieldpiece-vc2g','Alternative isolation arrangement','Choose instead when the dual-valve setup is required; owning both is not necessary.','Upgrade'],['fieldpiece-vp833','Different refrigerant requirement','An alternative pump only where its documented A3 application is required.','Upgrade']],
    ['Suitable vacuum hoses, adapters, oil and gauge-maintenance supplies are additional purchases; verify the ratings of every component.','Recovery and pressure testing are separate equipment roles. Pump nominal capacity and ultimate vacuum do not prove the system’s verified condition.'],
    'Should I buy both VP87 and VP833?','Choose the suitable pump for the required refrigerant application. They are alternatives with different documented compatibility, not a default two-pump kit.'),
  kit(j.recovery,'HVAC Refrigerant Recovery Tool Kit: Machine, Cylinder and Weight Monitoring','Choose a compatible recovery machine and plan the equipment around it: appropriate cylinders, scale, hoses, filters and the required refrigerant-handling controls.',
    [['1. Identify and plan','Confirm refrigerant, recovery requirements and suitable equipment before connecting.'],['2. Assemble the complete arrangement','Match machine, cylinder, hoses and weight-monitoring equipment.'],['3. Monitor the required work','Observe the equipment instructions and cylinder limits using the appropriate qualified procedure.'],['4. Record and transport','Keep the required refrigerant records and use suitable cylinder and machine transport arrangements.']],
    [['fieldpiece-mr45','Recover','Digital-interface recovery machine for its current approved refrigerants.','Core'],['fieldpiece-sr47','Monitor weight','Weigh the appropriate cylinder; the scale is not an overfill prevention system.','Core'],['fieldpiece-vc1g','Conditional connection','Use only where the fitting and prescribed setup call for a core-removal arrangement.','Useful'],['appion-g5twin','Alternative machine','Compare as a replacement choice, including Appion’s authorized-distributor policy.','Useful'],['navac-nrdd','Alternative machine','Another recovery configuration; exact refrigerant and model compatibility decide suitability.','Useful']],
    ['Choose one suitable machine. Alternative machines are not extra items required to complete the kit.','Appropriate cylinders, filters, hoses, protective equipment and refrigerant identification and record requirements are outside this product shortlist.'],
    'Does machine automatic shutoff replace a scale?','No. Use the required cylinder limits, weight monitoring and prescribed procedure rather than treating a machine feature as universal overfill protection.'),
  kit(j.leak,'HVAC Refrigerant Leak Detection Tool Kit: Locate, Confirm and Document','Choose a detector for the actual refrigerant and environment, then support its indications with the appropriate confirmation method and a clear record of the investigated area.',
    [['1. Define the investigation','Confirm the equipment, refrigerant, reported history and permitted detector application.'],['2. Choose the detection method','Use a suitable sensor, current filters and the manufacturer’s prescribed checks.'],['3. Narrow and confirm','Investigate indications with an appropriate confirmation method for the system.'],['4. Record and reassess','Record location, conditions and the checks required after any approved repair.']],
    [['fieldpiece-dr82','Pinpoint','Infrared option for its approved refrigerants and conditions.','Core'],['fieldpiece-dr58','Alternative sensing','Heated-diode choice when that maintenance and sensing approach suits the work.','Useful'],['inficon-dtek-stratus','Broader investigation','Conditional cloud-hunting and pinpointing alternative for the documented sensor setup.','Upgrade'],['fieldpiece-drx3','Different gas application','Choose only when its documented broader gas scope and environment approval are required.','Upgrade'],['veto-techmct','Protect instruments','Keep sensors and measurement gear separately protected from oily hoses and work debris.','Useful']],
    ['The detectors are alternatives. Do not buy all four as an assumed minimum kit.','An indication alone does not establish every leak location or replace the system’s prescribed leak-test and confirmation process.'],
    'Can I use any refrigerant detector for combustible gas?','No. Gas support and permitted operating environment must be confirmed for the exact detector, sensor and current instructions.'),
  kit(j.airflow,'HVAC Airflow and Static Pressure Tool Kit: Measure Conditions Before Blaming Charge','Plan complementary airside measurements: static or differential pressure, appropriate velocity measurements, temperature and humidity. Keep each reading tied to its location and method.',
    [['1. Establish conditions','Record equipment, filter and duct observations and the operating state.'],['2. Measure pressure appropriately','Use the required locations, probes, tubing and instrument modes.'],['3. Measure air conditions and velocity','Choose access and method suitable for the sensor and the scope of assessment.'],['4. Compare and document','Compare against the installed equipment requirements and retain measurement locations.']],
    [['fieldpiece-sdmn5','Pressure','Local dual-port instrument for documented static and differential measurements.','Core'],['fieldpiece-sta2','Velocity','Hot-wire duct probe with the appropriate representative measurement method.','Useful'],['fieldpiece-jl3rh','Air conditions','Temperature and humidity; paired locations may need more than one probe.','Core'],['fieldpiece-st4','Contact temperatures','Two channels with suitable probes for the actual task.','Useful'],['testo-417','Alternative outlet measurement','Large-vane arrangement for suitable outlets, with accessories and generation checked.','Upgrade']],
    ['A spot velocity, temperature split or static reading does not automatically establish total delivered airflow. Some scopes require suitable capture or balancing equipment.','Do not infer a refrigerant-charge correction from one airside number; follow the diagnostic and equipment requirements.'],
    'Are a psychrometer and an anemometer interchangeable?','No. One measures air temperature and humidity; the other measures air velocity. Calculated volume also depends on dimensions and a sound measurement method.'),
  kit(j.apprentice,'HVAC Apprentice Starter Tool Kit: Daily Basics Before Specialist Machines','Start with employer-approved daily tools and a suitable electrical instrument. Add airside and refrigerant equipment as training, responsibility and recurring work justify the purchase.',
    [['1. Confirm employer requirements','Ask which tools, instruments, protective equipment and qualifications the role requires.'],['2. Build the daily basics','Choose practical storage and suitable small hand and temperature tools.'],['3. Add instruments by the work','Choose a rated meter and relevant measurement functions before buying larger specialist systems.'],['4. Upgrade deliberately','Add recovery, evacuation and connected systems when trained recurring work requires them.']],
    [['fieldpiece-sc260','Electrical instrument','Compact option only when its rating and functions meet the employer’s actual requirements.','Core'],['fieldpiece-spk2','Temperature tool','Pocket in-duct temperature role within its documented application.','Useful'],['ridgid-40617','Tube preparation','Supported copper-tube cutting with material and actual OD checked.','Useful'],['veto-tpxl','Daily carry','A deliberate smaller kit rather than every specialist instrument at once.','Useful'],['fieldpiece-sdmn5','Next measurement role','Add pressure measurement when trained work requires it.','Upgrade'],['fieldpiece-jl3rh','Connected airside expansion','Add when its readings and app setup support the actual diagnostic responsibility.','Upgrade']],
    ['This shortlist omits employer-specific hand tools, lighting, isolation equipment, PPE and consumables. Obtain that list before spending.','Owning refrigerant equipment does not authorize refrigerant handling or electrical work. Start with training and employer requirements.'],
    'Do I need my own recovery machine immediately?','Not by default. Ask what the employer supplies and what the role requires, then buy specialist equipment when responsibility and workload justify it.'),
  kit(j.van,'HVAC Service Bag and Van Setup: Separate Daily Instruments from Refrigerant Equipment','Keep the daily diagnosis bag accessible, protect measuring instruments and organize pumps, recovery equipment, hoses and cylinders in suitable separate transport arrangements.',
    [['1. Select the daily load','Choose the instruments and small tools needed on ordinary visits.'],['2. Protect measurement gear','Use appropriate cases and separation for sensors, leads and probes.'],['3. Organize specialist equipment','Provide suitable independent carrying and storage for machines, hoses and cylinders.'],['4. Maintain and replenish','Plan instrument care, oil, filters, batteries and the consumables required for the route.']],
    [['veto-tpxl','Compact daily carry','For a smaller selected diagnosis kit.','Useful'],['veto-techmct','Enclosed alternative','Choose instead where an enclosed structured bag better fits the instruments.','Useful'],['milwaukee-48228321','Modular alternative','Choose for an existing compatible PACKOUT carrying system.','Useful'],['fieldpiece-sc680','Protect measurement gear','A larger electrical instrument needs suitable space and protected lead storage.','Core'],['fieldpiece-mr45','Separate machine role','Keep the recovery equipment and its accessories in a suitable separate arrangement.','Useful'],['fieldpiece-vp87','Separate evacuation role','Plan pump transport and oil maintenance away from delicate instrument storage.','Useful']],
    ['Bag alternatives are carrying choices, not a recommendation to buy three daily bags.','Cylinder transport and storage must follow the applicable requirements and cylinder documentation; a tool-bag recommendation does not cover them.'],
    'Should the daily bag hold every specialist tool?','No. Select the ordinary diagnosis load and keep bulky or contamination-prone equipment separately organized and appropriately secured.'),
];
