import { guides, hubs } from './data';
import { inspectorJobs } from './inspector-catalog';
import type { Workflow, WorkflowTool } from './workflows';
type Pick=[string,string,string,WorkflowTool['priority']];
function kit(slug:string,title:string,summary:string,stages:[string,string][],picks:Pick[],notes:string[]):Workflow {
  const tools=picks.map(([id,stage,why,priority])=>{
    const guide=guides.find(g=>g.trade==='home-inspectors'&&g.products.some(p=>(p.productId||p.reviewSlug?.replace(/-review$/,''))===id));
    const product=guide?.products.find(p=>(p.productId||p.reviewSlug?.replace(/-review$/,''))===id);
    if(!guide||!product)throw new Error(`Missing inspector kit product: ${id}`);
    return {stage,type:guide.title.replace(/^Best /,'').split(' for Home Inspectors')[0],name:`${product.brand} ${product.model}`,why,priority,amazonUrl:product.url,guideUrl:`/home-inspectors/${guide.slug}/`,reviewUrl:product.reviewSlug?`/reviews/${product.reviewSlug}/`:undefined};
  });
  return {trade:'home-inspectors',tradeName:'Home Inspectors',slug,title,summary,meta:summary,keyword:slug.replace(/-/g,' '),heroImage:hubs.find(h=>h.slug==='home-inspectors')!.image,stages:stages.map(([name,description])=>({name,description})),tools,notes,
    faqs:[{q:'Is every item required for every inspection?',a:'No. Match the agreed scope, competence and actual access. Core items cover this buying plan; useful and upgrade items are conditional additions.'},{q:'Is this a complete retail bundle?',a:'No. Check batteries, chargers, probes, cases, report devices and any other separately required equipment in the exact offers.'},{q:'What happens when an area is inaccessible?',a:'Use an appropriate observation method within the scope and record the limitation. Owning a camera, light or ladder does not make an area safe to enter.'},{q:'Were these tools field-tested by TradeGear HQ?',a:'No. These buying plans use documented capabilities and inspection-fit analysis. External feedback is separately attributed.'}]};
}
const j=inspectorJobs;
export const inspectorWorkflows:Workflow[]=[
  kit(j.purchase,'Home Inspector Pre-Purchase Tool Kit: Observe, Screen and Record','Build a deliberate daily kit for a defined residential inspection: accessible observations, appropriate screening instruments and report-ready location records.',
    [['1. Agree the scope','Confirm property, included systems, access and reporting requirements.'],['2. Organize the observations','Carry the daily instruments and record location with each finding.'],['3. Investigate supported concerns','Add moisture or thermal observations where the agreed scope and conditions justify them.'],['4. Complete the record','Document findings, access limitations and recommended specialist follow-up.']],
    [['klein-rt250','Outlet screening','Readable plug-in indication at appropriate accessible receptacles; no whole-installation safety claim.','Core'],['klein-et140','Moisture screening','Comparative readings on suitable materials with context recorded.','Useful'],['klein-56062','Close lighting','Hands-free illumination for suitable accessible areas.','Core'],['bosch-glm16527cg','Dimensions','Supported dimensions and compatible transfer for the actual report routine.','Useful'],['veto-tech-pac','Carry','Organize a selected daily load with separate protection for delicate instruments.','Useful'],['flir-c5','Thermal observations','Conditional surface-pattern documentation with independent investigation of suspected causes.','Upgrade']],
    ['Report device, ordinary-photo camera, suitable measuring tape, charging equipment and required protective equipment are additional requirements.','This is a buying plan for a defined inspection, not an assurance that every system or concealed area can be inspected.']),
  kit(j.listing,'Home Inspector Pre-Listing Tool Kit: Document Conditions Before Marketing','Organize repeatable observations, clear photographs and bounded findings for a pre-listing inspection. Keep follow-up repairs and verification separate from the report.',
    [['1. Confirm the brief','Define the inspection coverage and report recipient.'],['2. Record locations clearly','Pair ordinary photographs and dimensions with each observation.'],['3. Check concerns within scope','Use appropriate screening tools and record measurement context.'],['4. Explain follow-up','Identify access limits and the appropriate specialist assessment where required.']],
    [['bosch-glm10023','Dimensions','Simpler direct-distance alternative when connected transfer is unnecessary.','Useful'],['klein-rt210','Outlets','Limited plug-in indications rather than a blanket wiring pass.','Core'],['extech-mo55','Moisture','Pin and pinless modes with material and mode distinguished in the report.','Useful'],['milwaukee-2367-20','Photograph lighting','Place an area light to reveal detail without misleading glare.','Useful'],['klein-55421bp14','Carry','A manageable daily instrument load with suitable cases.','Useful'],['klein-et110','Conditional ambient measurement','Only for an agreed ambient-CO scope and appropriate response plan.','Upgrade']],
    ['An inspection report does not certify future occupancy conditions or replace required installed alarms.','Do not describe a seller’s repair as verified merely because an earlier screening concern is no longer indicated.']),
  kit(j.moisture,'Home Inspector Moisture Investigation Tool Kit: Pattern, Material and Context','Combine the distinct roles of thermal surface patterns, building-material indications and air conditions. Record what each instrument measures and what remains unconfirmed.',
    [['1. Record the concern','Photograph the location, material and relevant surrounding observations.'],['2. Screen the visible surface','Use appropriate non-invasive observations and record reference areas where meaningful.'],['3. Confirm through the permitted scope','Select appropriate material measurements or recommend a specialist assessment.'],['4. Explain the limits','Keep an observed pattern separate from an asserted leak source or mold diagnosis.']],
    [['protimeter-bld5375','Material indications','Two measurement approaches, interpreted separately for the material.','Core'],['flir-c5','Surface pattern','Thermal images complement ordinary photographs and location notes.','Useful'],['testo-625','Air conditions','Local temperature and RH readings tied to location and time.','Useful'],['klein-et20','Local observation','Only through existing permitted access; save identifiable images with supported software.','Useful'],['wagner-orion910','Wood-specific extension','Alternative instrument where recurring appropriate wood measurements justify it.','Upgrade']],
    ['Thermal anomalies, relative scan readings and air humidity are different observations. None alone proves mold or a hidden leak source.','Pins may mark a surface. Keep contact and any additional access within the agreed inspection scope.']),
  kit(j.attic,'Home Inspector Attic and Roof Observation Tool Kit: Access, Light and Limitations','Plan suitable access and illumination before selecting additional instruments. Use roof and attic observation methods that fit the property and record inaccessible areas.',
    [['1. Assess the available view','Establish access and an appropriate observation method before setting up equipment.'],['2. Select suitable access equipment','Match the ladder’s actual permitted configuration and complete load to the location.'],['3. Light and document','Record accessible conditions with identifiable photographs.'],['4. Report inaccessible areas','Explain viewing limitations and further assessment required.']],
    [['werner-6006s','Short interior access','Only for suitable stepladder access within its exact configuration and load limit.','Useful'],['little-giant-15417001','Alternative access configuration','Choose instead when the documented articulated arrangement suits the access; not a default second ladder.','Useful'],['klein-56062','Close illumination','Hands-free viewing in appropriate accessible areas.','Core'],['coast-xph30r','Alternative beam choice','Select the required beam rather than assuming both headlamps are needed.','Useful'],['flir-c5','Conditional thermal observation','Visible surface patterns with environmental conditions and limits documented.','Upgrade']],
    ['A ladder recommendation does not require walking a roof or entering an unsafe attic. Record the actual limitation.','Roof-viewing devices, required protective equipment and other property-specific access equipment are outside this shortlist.']),
  kit(j.crawl,'Home Inspector Crawlspace and Basement Tool Kit: Lighting and Building Conditions','Prioritize an appropriate accessible observation, clear lighting and material-specific readings. Record areas that cannot be viewed rather than expanding access to use a tool.',
    [['1. Establish access limits','Assess the agreed scope and suitable observation position.'],['2. Illuminate the area','Choose hands-free and placed lighting appropriate to the visible area.'],['3. Record supported conditions','Pair observations with location, material and instrument mode.'],['4. Explain further investigation','Record restricted views and concerns requiring an appropriate specialist.']],
    [['klein-56062','Hands-free viewing','Appropriate close illumination.','Core'],['milwaukee-2367-20','Area lighting','Placed illumination with the complete M12 power equipment checked.','Useful'],['klein-et140','Material screening','Comparative pinless readings on suitable materials.','Useful'],['testo-605i','Air conditions','Compatible app-based air temperature and humidity observations.','Useful'],['teslong-nts300','Local camera view','Existing permitted openings with exact probe configuration checked.','Useful']],
    ['Lighting and a camera do not make a confined, contaminated or otherwise unsuitable area safe to enter. Record limitations.','A borescope view cannot establish the condition of every concealed structural element.']),
  kit(j.electrical,'Home Inspector Electrical Screening Tool Kit: Observe and Refer','Organize limited accessible electrical observations and instrument indications. Keep qualified contact measurements distinct from an ordinary visual screening scope.',
    [['1. Confirm the permitted scope','Identify the accessible observations and any agreed functional checks.'],['2. Record the specific indication','Associate a supported plug-in result with the actual receptacle location.'],['3. Keep indication and measurement separate','Use instruments only for their documented role within competence and scope.'],['4. Refer concerns appropriately','Describe the observation and recommend qualified investigation where required.']],
    [['klein-rt250','Receptacle indication','Readable limited plug-in screening at supported outlets.','Core'],['klein-ncvt-3p','Non-contact indication','An indication only; not proof of absence of voltage or permission to touch parts.','Useful'],['klein-56062','Illumination','Hands-free light for accessible observations.','Useful'],['klein-rt390','Conditional additional functions','Alternative analyzer only when its measurements fit scope and competence.','Upgrade'],['fluke-t5-600','Separate qualified measurement role','Contact measurement instrument only for users with the required competence and controls.','Upgrade']],
    ['Plug-in testers cannot identify every wiring defect. Record the limited observation rather than certifying the whole circuit.','A non-contact pen cannot establish a safe isolation. Tool ownership does not authorize exposed electrical work.']),
  kit(j.systems,'Home Inspector HVAC and Plumbing Observation Tool Kit: Accessible Conditions and Follow-Up','Use appropriate accessible observations, bounded temperature readings and conditional gas instruments. Refrigerant service, combustion analysis and repairs are separate specialist work.',
    [['1. Identify equipment and scope','Record visible equipment and the permitted observations.'],['2. Record accessible operating conditions','Tie measurements to the actual mode, location and time.'],['3. Investigate only the agreed role','Use a specific appropriate instrument without extending into unsupported service diagnosis.'],['4. Explain concerns and limits','Recommend further specialist assessment where observations or access require it.']],
    [['fieldpiece-spk3','Temperature observation','Distinguish rod contact and IR surface methods in the record.','Useful'],['testo-625','Air conditions','Local temperature and RH rather than a whole-system airflow determination.','Useful'],['klein-et140','Plumbing-area moisture','Suitable material screening with the source of an indication left for appropriate confirmation.','Useful'],['ridgid-micro-ca25','Local camera observation','View-only camera for existing permitted short-range access.','Useful'],['klein-et120','Conditional combustible-gas role','Use only for the documented application and agreed scope; not a personal safety alarm.','Upgrade'],['klein-et110','Conditional ambient-CO role','Ambient observation does not replace an installed alarm or combustion assessment.','Upgrade']],
    ['Suspected gas or CO hazards require the applicable response, not continued investigation prompted by this buying plan.','These tools do not provide a refrigerant-service kit, combustion-efficiency analysis or appliance safety certificate.']),
  kit(j.starter,'Home Inspector Starter Kit and Reporting Setup: Buy the Daily Roles First','Start with a defined inspection scope and a practical reporting routine. Add thermal, specialist moisture and gas instruments when training and recurring work justify them.',
    [['1. Define the daily scope','Choose training, report requirements and the initial property types.'],['2. Build the basic record','Plan ordinary photographs, notes, dimensions and suitable report-device power.'],['3. Choose the daily instruments','Buy the supported screening and lighting roles before specialist upgrades.'],['4. Add equipment deliberately','Expand only for an identified recurring measurement or access requirement.']],
    [['klein-rt210','Outlet screening','Simple supported plug-in indications with limitations understood.','Core'],['general-mmd4e','Conditional material measurement','Compact pin instrument only where the contact and material interpretation are appropriate.','Useful'],['klein-56062','Lighting','Hands-free close observation with a practical charging routine.','Core'],['klein-93ldm100c','Dimensions','Compact direct-distance measurement.','Useful'],['clc-1134','Organize carry','Conventional backpack with suitable separate cases for instruments.','Useful'],['flir-c5','Later thermal role','Add for a defined thermal observation and report-image workflow.','Upgrade']],
    ['Suitable measuring tape, ordinary-photo and report devices, chargers, cases and required protective equipment are additional purchases.','A larger tool inventory does not replace training, a defined scope or clear reporting of inspection limitations.']),
];
