import {category as c,tool as t} from './plumber-category-builder';
import {job} from './plumber-catalog-types';
const sb='https://www.sharkbite.com/us/en/pex-pipe-connectors/pex-cutters-accessories/pex-crimp-tool',m='https://www.milwaukeetool.com/';
export const plumberJoiningCategories=[
c('best-pex-crimp-tools-for-plumbers','Best PEX Crimp Tools for Plumbers: Copper Rings and Stainless Clamps','Pipe Cutting & Joining',
'IWISS IWS-1234W is the compact two-size copper-ring choice. SharkBite 23251 offers another 1/2- and 3/4-inch option; its 23100 and Apollo kits add interchangeable sizes. SharkBite 23081 belongs to the stainless-clamp method and is included as a separate system choice.',
'Copper crimp rings, stainless cinch clamps and PEX-A expansion fittings use different tools. Confirm the approved tube, fitting and ring combination; these tools are not for press fittings on copper.',
[{title:'Choose the connection system first',body:'Start with the tubing and fitting manufacturer’s approved connection method. A copper-ring crimper and a stainless-clamp cincher are different tools. A kit that covers the right nominal sizes can still be wrong for the chosen system.'},{title:'Access and size coverage',body:'A dual-size tool is useful for repeated 1/2- and 3/4-inch service work. Interchangeable dies cover more sizes but require the correct installed die and space to close the handles. Check clearance before relying on a manual tool behind a fixture.'},{title:'Gauges and adjustment',body:'Follow the fitting and tool instructions for ring position, adjustment and the prescribed go/no-go check. Count the gauge and dies as part of the purchase; do not compare a complete kit with a bare tool as though the packages were identical.'}],
[{q:'Is a PEX clamp tool the same as a crimp tool?',a:'No. A clamp tool closes the ear on an approved stainless clamp. A copper-ring crimper forms a different ring and typically uses a corresponding inspection gauge.'},{q:'Do these expand PEX-A?',a:'No. Expansion connections require an approved expander, heads and rings. See the separate PEX expansion guide.'},{q:'Which sizes should a first service kit cover?',a:'Choose from the jobs and system your employer actually uses. A 1/2- and 3/4-inch dual-size tool is useful for common residential work; other sizes need the appropriate dies or tool.'}],
[job.pipe,job.bath,job.heater,job.apprentice],[
t('iwiss-iws1234w','IWISS','IWS-1234W Angled PEX Crimp Tool','Two-size copper-ring service pick','https://www.iwiss.com/products/iws-1234w-1-2-3-4-angel-combo-pex-pipe-crimping-tool-single-tool','manual copper-ring work on 1/2- and 3/4-inch PEX.','Do not buy it for stainless cinch clamps or PEX-A expansion.',[['Sizes','1/2 and 3/4 in'],['Method','Copper-ring crimp'],['Format','Angled manual dual-size']],['Two common sizes in one tool','Angled head layout'],['No interchangeable 1-inch head','Handle closure needs clearance']),
t('sharkbite-23251','SharkBite','23251 Dual-Size PEX Crimp Tool','Alternative fixed two-size crimper',sb,'approved 1/2- and 3/4-inch copper-ring connections.','Choose another size or method when this fixed pair does not fit.',[['Sizes','1/2 and 3/4 in'],['Method','Copper-ring crimp']],['Dual-size jaws','Published system instructions'],['Fixed size coverage','Not a clamp cincher']),
t('sharkbite-23100','SharkBite','23100 Multi-Head PEX Crimp Tool Kit','Interchangeable-size kit',sb,'buyers who need several nominal copper-ring sizes.','Changing dies adds a setup step and does not solve restricted handle access.',[['Format','Interchangeable heads'],['Method','Copper-ring crimp']],['Broader size coverage','Kit format for gauge and heads'],['Verify every included die','Larger kit to carry']),
t('sharkbite-23081','SharkBite','23081 PEX Clamp Tool','Stainless-clamp system option','https://www.sharkbite.com/sites/default/files/files/sharkbite-pex-clamp-tool-install-guide-23081-%20UC961.pdf','approved stainless PEX clamp connections.','This does not crimp copper rings or expand tubing.',[['Method','Stainless-clamp cinch'],['Published sizes','3/8, 1/2, 5/8, 3/4 and 1 in']],['One clamp method across several sizes','Manufacturer adjustment guidance'],['Requires approved clamp system','Different inspection method from copper rings']),
t('apollo-69ptkh0015k','Apollo','69PTKH0015K PEX Crimp Tool Kit','Multi-size copper-ring kit','https://apolloflow.com/apollo-pex-crimp-tools/','manual copper-ring jobs that justify interchangeable dies.','Do not confuse this PEX-B crimp tool family with Apollo PEX-A expanders.',[['Method','Copper-ring crimp'],['Format','Interchangeable dies']],['Multiple-size kit','Manufacturer tool and gauge instructions'],['Check exact kit contents','Manual handle clearance required'])],
[{heading:'Why a two-size crimper is a useful starting point',body:'IWS-1234W keeps the purchase centered on two recurring residential sizes instead of filling a bag with dies that may never be used. The angled format changes the approach to the ring, but it still needs enough room to position the jaws squarely and close the handles. Measure the working space and check the system approval before choosing it for a repair.'},{heading:'Crimp, clamp and expansion are separate buying decisions',body:'The cheaper-looking tool is not better value if it uses the wrong connection method. Select the fitting system first, then choose the tool. The 23081 clamp tool is an alternative method rather than an interchangeable IWS-1234W substitute. Expansion tools are covered separately because expanding tubing and forming a copper ring are different operations.'},{heading:'Keep the inspection gauge with the tool',body:'A complete service purchase includes the correct gauge and the manufacturer’s adjustment procedure. Ring placement, fitting insertion and the prescribed inspection checks determine whether the tool has performed the intended operation. This is a documentation-based buying assessment; we have not tested joint strength or measured crimp consistency.'}]),
c('best-pex-expansion-tools-for-plumbers','Best PEX Expansion Tools for Plumbers: Powered and Manual Options','Pipe Cutting & Joining',
'Milwaukee 2532-20 is the M12 FUEL choice for a compatible ProPEX workflow. Compare original 2432-20 for the older M12 format, DeWalt DCE400D2 for a 20V kit, RIDGID RPE100 for its own powered package, and Apollo EPXTOOL for manual expansion.',
'Expansion is a system-specific connection method. Tool, expansion head, tubing, ring and fitting must be approved together. A powered bare tool is not a complete starter kit.',
[{title:'Approved system and head',body:'Verify the exact fitting system and head sizes. The same nominal pipe size does not establish tool approval. Expansion heads, including rotating designs, have their own care and use requirements.'},{title:'Existing battery platform',body:'M12 and DeWalt 20V MAX equipment use different batteries. Compare a complete kit with heads, battery and charger against a bare tool only after accounting for the equipment you already own.'},{title:'Frequency justifies power',body:'Manual expansion can suit occasional work. Repeated installation makes the powered format worth considering. We have not timed joint cycles, so compare documented mechanism and kit contents rather than an invented speed ranking.'}],
[{q:'Will an expander work with every PEX pipe?',a:'No. Verify the tube, ring and fitting system approval and the correct head with its manufacturer.'},{q:'Does 2532-20 include batteries and heads?',a:'Milwaukee lists 1/2-, 3/4- and 1-inch RAPID SEAL heads with 2532-20. Battery and charger are separate. Confirm that the retailer offer matches that equipment list.'},{q:'Can I replace a copper-ring crimper with this?',a:'Only by using a different, approved connection system. It is not a tool substitution for the same copper-ring joint.'}],
[job.pipe,job.bath,job.heater],[
t('milwaukee-2532-20','Milwaukee','2532-20 M12 FUEL ProPEX Expander','Powered M12 expansion pick',m+'2532-20','repeated approved ProPEX expansion on an M12 platform.','Milwaukee lists 1/2-, 3/4- and 1-inch RAPID SEAL heads with 2532-20; battery and charger are separate.',[['Platform','M12'],['Included heads','1/2, 3/4 and 1 in RAPID SEAL'],['Power equipment','Battery and charger separate']],['Powered expansion mechanism','M12 battery platform'],['Heads and power equipment must be checked','System-specific approval']),
t('milwaukee-2432-20','Milwaukee','2432-20 M12 ProPEX Expander','Original M12 format',m+'2432-20','buyers comparing the original M12 expander with FUEL.','Do not assume it has the newer 2532 mechanism or package.',[['Platform','M12'],['Configuration','Tool only']],['Established M12 format','Powered expansion'],['Older design than 2532','Verify head compatibility']),
t('dewalt-dce400d2','DeWalt','DCE400D2 20V MAX PEX Expander Kit','20V MAX kit alternative','https://www.dewalt.com/en-us/product/dce400d2/20v-max-1-cordless-pex-expander','approved expansion jobs for a DeWalt battery user.','Do not compare this kit price with a bare M12 tool without accounting for included equipment.',[['Platform','20V MAX'],['Configuration','DCE400D2 kit']],['Kit purchase format','DeWalt battery ecosystem'],['Bulkier system purchase for an M12 owner','Verify included head sizes']),
t('ridgid-rpe100','RIDGID','RPE100 PEX Expander 80703 Kit','RIDGID powered kit alternative','https://www.ridgid.com/us/en/rpe100-pex-expander','buyers wanting the RPE100 complete head-and-power package.','80763 is a different tool-only configuration; confirm catalog 80703.',[['Catalog','80703 kit'],['Included head sizes','1/2, 3/4 and 1 in']],['Complete kit option','Published package breakdown'],['Different battery system to account for','Kit number matters']),
t('apollo-epxtool','Apollo','EPXTOOL PEX-A Expansion Tool Kit','Manual occasional-use option','https://apolloflow.com/apollo-pex-a-tools/','approved PEX-A expansion when occasional use justifies a manual kit.','Repeated installation may justify a powered tool; follow the prescribed rotation procedure.',[['Method','Manual expansion'],['System','Approved PEX-A fittings']],['No battery or charger','Manual kit format'],['More manual work per connection','Not the EPXTOOLAR rotating variant'])],
[{heading:'Where M12 FUEL earns its place',body:'2532-20 makes sense when expansion is a recurring part of the work and the buyer already uses M12 batteries. Its case is the powered mechanism and compatibility with the approved ProPEX setup. It is an expensive purchase to make for one unfamiliar repair, especially when battery and charger must also be bought. Milwaukee lists three RAPID SEAL heads with this tool; any additional sizes or replacement heads are a separate check.'},{heading:'Budget for the complete connection system',body:'A bare tool title can hide a much larger initial purchase. Price the heads required for your pipe sizes, suitable batteries and charger, and the fitting system itself. DeWalt and RIDGID kit configurations provide useful package comparisons; the relevant question is the complete equipment cost for the same approved jobs.'},{heading:'Choose manual expansion deliberately',body:'Apollo’s manual format is relevant when volume is low and the approved system allows it. It requires the documented operating and rotation procedure and sufficient access. We have not measured joint-making speed or ease of use. This shortlist distinguishes mechanism, package and platform, leaving those handling judgments to a buyer evaluating the actual tools.'}]),
c('best-press-tools-for-plumbers','Best Press Tools for Plumbers: Compact Service Tools and Larger Platforms','Pipe Cutting & Joining',
'Milwaukee 2473-20 is the compact M12 service candidate. RIDGID RP 251 is a current compact alternative; RP 115 is the smaller Mini platform. DeWalt DCE200M2K and Milwaukee 2922-20 are larger-platform comparisons for broader work.',
'Jaw profile, fitting approval, size and tool class govern compatibility. Mini, compact and standard jaws are not interchangeable merely because the press tool has enough advertised force.',
[{title:'Start with the approved fittings',body:'Check the fitting manufacturer’s approved tool and jaw list for the exact material and size. Copper, stainless, PEX and other press systems have different requirements. A battery platform is a secondary decision after that compatibility check.'},{title:'Mini, compact or standard',body:'Different tool classes cover different jobs and accessories. A smaller tool can be more useful inside a cabinet; a larger platform can support a broader approved range. Neither automatically wins on value without the actual fitting schedule.'},{title:'Lifecycle and kit contents',body:'Include jaws, batteries, charger, case and required service in the purchase. A bare tool and a full jaw kit are not equivalent offers. Follow the manufacturer’s inspection and service requirements for the tool and attachments.'}],
[{q:'Can I use any jaw on any press tool?',a:'No. Tool class, attachment interface, profile, size and fitting-system approval must all match.'},{q:'RP 251 or RP 241?',a:'This shortlist uses the current RP 251 compact platform. Compare the manufacturer’s current ordering information rather than assuming an older RP 241 package is the same.'},{q:'Is the smallest press tool best for all service work?',a:'Only if its approved fittings and sizes cover the work. A small form factor cannot compensate for an unsupported connection.'}],
[job.pipe,job.bath,job.heater,job.van],[
t('milwaukee-2473-20','Milwaukee','2473-20 M12 FORCE LOGIC Press Tool','Compact M12 service candidate',m+'2473-20','approved compact pressing where access and an existing M12 battery kit matter.','Buy the correct approved jaws separately if the offer is tool only.',[['Platform','M12'],['Configuration','Tool only'],['Class','Compact press']],['Compact service format','M12 platform'],['Jaw package must be budgeted','Approved size range depends on fitting and jaw']),
t('ridgid-rp251','RIDGID','RP 251 Compact Press Tool','Current RIDGID compact platform','https://www.ridgid.com/us/en/press-tools','service buyers selecting a current RIDGID compact press setup.','Do not buy standard or Mini jaws assuming they fit a compact tool.',[['Class','Compact'],['Model','RP 251']],['Current compact platform','Manufacturer fitting and jaw guidance'],['Exact jaw kit matters','Separate attachment class']),
t('ridgid-rp115','RIDGID','RP 115 Mini Press Tool','Small Mini-class alternative','https://www.ridgid.com/us/en/press-tools','approved small-size service pressing with Mini attachments.','Choose a compact or standard system if the required fitting sizes exceed the Mini range.',[['Class','Mini'],['Model','RP 115']],['Small tool class','Dedicated Mini accessories'],['Narrower application range','Mini attachments are system specific']),
t('dewalt-dce200m2k','DeWalt','DCE200M2K 20V MAX Press Tool Kit','DeWalt full-kit comparison','https://www.dewalt.com/en-us/product/dce200m2k/20v-max-cordless-press-tool-jaws','approved pressing for a DeWalt user considering a larger kit.','Check the supplied jaw profiles and sizes rather than assuming every DCE200 offer is complete.',[['Platform','20V MAX'],['Configuration','DCE200M2K kit']],['Full kit configuration','DeWalt platform'],['Larger package than a small service tool','Accessory approval still required']),
t('milwaukee-2922-20','Milwaukee','2922-20 M18 FORCE LOGIC Press Tool','Larger M18 platform',m+'products/details/m18-force-logic-press-tool-w-one-key/2922-20','approved work that calls for the larger M18 press platform.','A larger tool may be unnecessary or awkward for small cabinet repairs.',[['Platform','M18'],['Configuration','Tool only']],['Larger-platform accessory coverage','M18 battery ecosystem'],['Budget for correct attachments','More tool than some service jobs require'])],
[{heading:'The reason to consider a compact press tool',body:'2473-20 is relevant to a service plumber whose approved fitting range is covered by the compact system and who already carries M12 batteries. Its place is in repeated repairs and alterations, where a dedicated tool can justify space in the van. The recommendation is conditional on fitting and jaw approval; it is not a general endorsement for every press connection.'},{heading:'Compare the tool and the jaw package together',body:'A press tool without the correct jaws cannot complete the planned job. List the materials and nominal fitting sizes you use, check the fitting maker’s compatibility chart, then compare full packages. The RIDGID Mini, compact and larger Milwaukee or DeWalt formats represent different accessory decisions rather than successive levels in a simple ranking.'},{heading:'Plan service as part of ownership',body:'Attachment condition and the tool’s documented inspection and maintenance requirements belong in the ownership budget. Check the current manual, service arrangements and included equipment before ordering. We have not measured cycle life, leak rates or field speed; this assessment uses the published platform and system requirements.'}])
];
