import {category as c,tool as t} from './plumber-category-builder';
import {job} from './plumber-catalog-types';
const r='https://www.ridgid.com/us/en/',m='https://www.milwaukeetool.com/';
export const plumberDrainCategories=[
c('best-drain-snakes-for-plumbers','Best Drain Snakes for Plumbers: Sink, Tub and Service-Call Machines','Drain Cleaning & Inspection',
'Milwaukee 2571-20 is the battery-based small-drain pick. RIDGID PowerClear and K-45AF offer corded alternatives; PowerSpin+ is the manual/drill-driven format. Milwaukee 2772A-21 changes the platform and cable reach. Choose by drain diameter and access before power source.',
'Small-drain snakes are not mainline root-removal machines or toilet augers. Cable diameter, head and length must suit the drain. Do not route a generic snake through a toilet bowl just because the cable reaches.',
[{title:'Drain and cable must match',body:'Identify pipe diameter, access point, bends and likely obstruction. Use the manufacturer’s cable and cutter recommendations. A longer cable does not make a small machine appropriate for larger mainline work.'},{title:'Contain the dirty work',body:'Plan cable handling, splash protection and transport before choosing handheld or floor-supported equipment. Compare the actual drum, shield and feed arrangement. We have not measured cleanup time or ease of operation.'},{title:'Tool-only versus ready kit',body:'The battery, charger, cable, cutter and storage package determine whether the purchase is ready for the intended job. Check replaceable cables and service parts as well as the initial machine.'}],
[{q:'Can a small drain snake clear roots?',a:'Do not assume that. Mainline and root work requires suitable professional equipment and cutters. Check the machine’s stated application limits.'},{q:'Can I use these in a toilet?',a:'Use an appropriate protected toilet auger for bowl access. These small-drain machines are a separate category.'},{q:'Does 2571-20 include a cable?',a:'Milwaukee lists a 5/16-inch by 25-foot bulb cable and storage bucket with the tool-only machine. Battery and charger are separate.'}],
[job.service,job.drain,job.van],[
t('milwaukee-2571-20','Milwaukee','2571-20 M12 Drain Snake','Battery small-drain service pick',m+'2571-20','small-drain service work for an existing M12 user.','Choose a mainline machine for larger lines or root work.',[['Cable supplied','5/16 in × 25 ft bulb'],['Published drain application','Through 2-1/2 in'],['Configuration','No battery or charger']],['Shielded drum with floor support','Cable and bucket listed in package'],['Limited to small-drain applications','Power equipment separate']),
t('ridgid-powerclear','RIDGID','PowerClear 55808 Drain Cleaning Machine','Corded small-drain alternative',r+'powerclear','small sink, tub and shower drains with suitable access.','This is not a mainline machine.',[['Power','Corded'],['Catalog','55808'],['Format','Small-drain drum machine']],['AUTOFEED arrangement','Self-contained corded machine'],['Power outlet and cord management','Limited drain-size application']),
t('ridgid-k45af','RIDGID','K-45AF Sink Machine','Professional handheld corded format',r+'k45af-sink-machine','frequent small-drain work that justifies a serviceable handheld machine.','Select the correct cable and exact AUTOFEED package.',[['Power','Corded'],['Format','Handheld sink machine']],['Professional small-drain platform','Available AUTOFEED configuration'],['Package variants need comparison','Not mainline equipment']),
t('ridgid-powerspin','RIDGID','PowerSpin+ 57043 Drain Auger','Manual or drill-driven occasional option',r+'powerspin-plus','occasional small-drain clearing with a manual or approved drill-driven format.','Repeated professional work may justify a powered dedicated machine.',[['Catalog','57043'],['Drive','Manual or compatible drill']],['No dedicated battery system','Small portable format'],['Separate compatible drill for powered operation','Not a full professional drum machine']),
t('milwaukee-2772a-21','Milwaukee','2772A-21 M18 FUEL Drain Snake Kit','M18 small-drain alternative',m+'2772A-21','small-drain work with a matched M18 battery, charger and cable kit.','Do not confuse this with the larger SWITCH PACK sectional drum system.',[['Platform','M18'],['Configuration','2772A-21 kit'],['Cable','5/16-inch × 35-foot'],['Power included','CP2.0 battery and multi-voltage charger']],['M18 battery ecosystem','Powered small-drain format'],['Existing M18 owners may already have power gear','Verify cable suitability for the drain'])],
[{heading:'Where the M12 machine belongs',body:'2571-20 is a service-bag or van option for suitable small drains. Its shielded drum and flat support distinguish it from a loose hand auger, while the supplied bulb cable and bucket make the package easier to understand. The tool-only label refers to the missing battery and charger; it does not mean the listing should omit the cable shown in the manufacturer’s equipment list.'},{heading:'Let the drain decide the machine',body:'Identify the opening and pipe size before choosing cordless convenience. Tight bends, obstruction type and cable selection can make a different small-drain machine more suitable. A toilet needs a protected bowl-access tool, and a mainline needs a machine appropriate to that duty. This comparison does not turn the M12’s small-drain range into a claim about clearing every blockage.'},{heading:'Replacement cable and cleanup matter',body:'A working service purchase includes the correct replacement cable options, transport and cleaning arrangement. Follow the machine’s manual for cable condition, operating method and protective equipment. We have not tested clearing speed, jam behavior or cable life, so the verdict rests on configuration and the intended application.'}]),
c('best-toilet-augers-for-plumbers','Best Toilet Augers for Plumbers: Protected Bowl Access and Six-Foot Reach','Drain Cleaning & Inspection',
'RIDGID K-6P is the six-foot dual-powered service choice. K-3 is the shorter manual alternative; Milwaukee 2576-20 adds an M12 TRAPSNAKE driver. Compare its manual 49-16-2576 assembly or General T6FL when a hand-driven six-foot auger is the preferred format.',
'Bowl protection does not guarantee a scratch-free result. These augers address appropriate toilet obstructions; a cable that reaches six feet does not survey or clear the whole building drain.',
[{title:'Protected bowl access',body:'Choose a tool made for toilet access and follow its insertion and handling instructions. The protective guide is relevant to porcelain contact. Do not assume a bare sink cable offers the same protection.'},{title:'Three versus six feet',body:'Reach describes cable length rather than a guaranteed cleared distance. Consider the toilet geometry and obstruction location. A persistent or downstream issue may need fixture removal, camera work or another drain-access point.'},{title:'Manual and powered packages',body:'A hand-driven assembly, a driver-only offer and a full powered kit are different purchases. Confirm the auger attachment, power source and exact model suffix in the retailer’s contents list.'}],
[{q:'Is six feet always better than three?',a:'It provides more available cable, but the obstruction and access determine whether that is useful. It is not a substitute for downstream drain equipment.'},{q:'Does an auger guarantee no porcelain damage?',a:'No. Use the protective guide and the manufacturer’s handling procedure. Incorrect contact can still mark a fixture.'},{q:'Does 2576-20 include an M12 battery?',a:'The -20 configuration does not include battery and charger. Check the attachment and driver contents separately.'}],
[job.service,job.drain,job.bath,job.apprentice],[
t('ridgid-k6p','RIDGID','K-6P Six-Foot Toilet Auger','Six-foot dual-powered pick',r+'closet-augers','toilet service where protected access and six-foot reach are useful.','This is not equipment for an entire downstream sewer line.',[['Cable length','6 ft'],['Drive','Manual or compatible drill'],['Type','Toilet auger']],['Protected bowl-access format','Manual and drill-driven options'],['Correct handling still matters','Limited reach beyond the fixture']),
t('ridgid-k3','RIDGID','K-3 Three-Foot Toilet Auger','Short manual option',r+'closet-augers','routine toilet obstructions within a shorter cable reach.','Choose a longer or different access method for a farther obstruction.',[['Cable length','3 ft'],['Drive','Manual']],['Simple manual mechanism','Toilet-specific guide'],['Shorter reach','Not downstream drain-clearing equipment']),
t('milwaukee-2576-20','Milwaukee','2576-20 M12 TRAPSNAKE Six-Foot Toilet Auger','M12-powered format',m+'2576-20','frequent toilet service for an existing M12 owner.','Verify driver and attachment contents; battery and charger are separate.',[['Platform','M12'],['Reach','6 ft'],['Configuration','2772A-21 kit'],['Cable','5/16-inch × 35-foot'],['Power included','CP2.0 battery and multi-voltage charger']],['Powered TRAPSNAKE system','Toilet-specific attachment'],['Power equipment separate','More equipment than a manual auger']),
t('milwaukee-49162576','Milwaukee','49-16-2576 TRAPSNAKE Six-Foot Toilet Auger','Manual TRAPSNAKE assembly',m+'products/details/trapsnake-6-toilet-auger/49-16-2576','buyers wanting the auger assembly without a powered M12 package.','Do not mistake an assembly listing for a driver-and-battery kit.',[['Reach','6 ft'],['Configuration','Auger assembly']],['Manual operating option','TRAPSNAKE system attachment'],['Check included driver configuration','No battery kit implied']),
t('general-t6fl','General Pipe Cleaners','T6FL Teletube Flexicore Toilet Auger','Six-foot manual professional alternative','https://drainbrain.com/products/closet-augers-pro/','manual toilet service with an extendable Teletube format.','Confirm T6FL rather than the shorter T4FL variant.',[['Model','T6FL'],['Cable','Flexicore'],['Reach','6 ft']],['Extendable manual format','Published replacement cable support'],['Manual operation','Exact cable variant matters'])],
[{heading:'Why K-6P is a practical service comparison',body:'K-6P combines the toilet-specific guide with a six-foot cable and the choice of manual or compatible drill operation. Those are the documented reasons to consider it instead of a generic sink snake. It still depends on the obstruction being reachable from the bowl, and the guide must be used correctly.'},{heading:'Decide whether powered operation is worth the equipment',body:'A frequent service route may justify a powered format; occasional calls may be better served by a simpler manual auger. Milwaukee’s tool and attachment configurations make that distinction especially important. Price the driver, auger assembly and power equipment together when comparing with K-6P.'},{heading:'Recognize when the problem is farther downstream',body:'Repeated blockage or a suspected drain-line defect changes the equipment requirement. A longer toilet auger is not a replacement for a push-rod camera or suitable downstream cleaning machine. This is a buying guide for fixture access, not a diagnosis or a promise that a particular auger will clear the complaint.'}]),
c('best-professional-drain-machines-for-plumbers','Best Professional Drain Machines for Plumbers: Drum, Sectional and FlexShaft','Drain Cleaning & Inspection',
'RIDGID K-400 is the cart-mounted drum comparison for suitable everyday lines. K-60SP uses sectional cable, K-750 targets larger drain work, Milwaukee SWITCH PACK separates the drive and drum for transport, and K9-204+ uses a different enclosed-shaft cleaning method.',
'These are expensive specialist tools, not automatic upgrades to a sink snake. K-400 is explicitly not designed to remove root blockages. Cable, cutter, pipe condition and operating training determine suitability.',
[{title:'Different mechanisms, different applications',body:'Conventional rotating cable, sectional cable and a sheathed FlexShaft system operate differently. Select the manufacturer’s approved pipe range, cable and cleaning head for the obstruction; do not rank them simply by price or reach.'},{title:'Transport and working space',body:'Compare complete working weight, cart, separate drum or cable sections, rear guide requirements and available setup room. Machine-only weight understates the equipment carried to the job.'},{title:'Own, hire or subcontract',body:'Repeated paid drain work can justify ownership. Occasional mainline jobs may justify rental or a specialist subcontract instead. Budget replacement cables, heads, inspection equipment, cleaning and documented maintenance.'}],
[{q:'Can K-400 remove roots?',a:'RIDGID explicitly says it is not designed for root blockages. Use equipment, cutters and methods approved for that duty.'},{q:'Is FlexShaft the same as a drain snake?',a:'No. It uses a flexible shaft inside a sheath and compatible cleaning heads. Its setup and operating requirements differ from exposed rotating cable.'},{q:'Should a first-year apprentice buy a mainline machine?',a:'Usually the employer and actual work should determine that purchase. These are specialist business investments with training, transport and maintenance requirements.'}],
[job.drain,job.van],[
t('ridgid-k400','RIDGID','K-400 52363 Drum Machine with 3/8-Inch × 75-Foot Cable','Everyday cart-mounted drum comparison',r+'k400-drum-machine','suitable drain work with the 52363 115V cable package.','RIDGID says K-400 is not designed for root blockages.',[['Catalog','52363'],['Supplied cable','3/8 in × 75 ft C-32 IW'],['Power','115V corded']],['Integrated transport cart','Published cable and package options'],['Not intended for root removal','Working package is heavier than bare machine']),
t('ridgid-k60sp','RIDGID','K-60SP Sectional Machine','Sectional-cable alternative',r+'k60-sectional-machine','professional work that justifies a sectional cable system.','Check US voltage and complete cable, guide and cutter package.',[['Format','Sectional cable'],['Model','K-60SP']],['Separate cable sections','Professional replacement parts support'],['More setup components','Package and voltage variants']),
t('ridgid-k750','RIDGID','K-750 Drum Machine','Larger drain-duty comparison',r+'k750-drum-machine','larger drain work within the published cable and cutter application.','Not a convenient substitute for a small fixture-drain machine.',[['Format','Large drum machine'],['Model','K-750']],['Larger-duty cable platform','Cart-based transport'],['Substantial transport burden','Exact cable and cutter package matters']),
t('milwaukee-2775b211','Milwaukee','2775B-211 M18 FUEL SWITCH PACK 3/8-Inch Kit','Separate-drive-and-drum cordless system',m+'products/details/m18-fuel-switch-pack-sectional-drum-machine-with-3-8-cable/2775b-211','professional drain work where separate drive and drum transport fits the operation.','Check whether the CABLE DRIVE feed accessory is included in the selected package.',[['Platform','M18'],['Configuration','2775B-211 3/8-in kit']],['Drive and drum separate for transport','Cordless professional platform'],['Feed accessory package needs checking','Drum and cable add carrying bulk']),
t('ridgid-k9204plus','RIDGID','K9-204+ FlexShaft Machine','Enclosed-shaft cleaning alternative',r+'k9-204p-flexshaft-machine','approved cleaning jobs that justify the FlexShaft method and compatible heads.','A suitable drill and correct cleaning-head setup are required; follow the manual.',[['Mechanism','Flexible shaft in sheath'],['Model','K9-204+']],['Different enclosed-shaft format','Compatible cleaning-head options'],['Separate drive and head requirements','Specialist application and technique'])],
[{heading:'K-400 is a business purchase for a defined job range',body:'Catalog 52363 specifies the 115V K-400 package with a 3/8-inch by 75-foot C-32 IW cable and tool set. It is a concrete configuration to compare instead of a vague machine-family listing. The cart is relevant to transport, but the complete package is much heavier than the machine-only figure.'},{heading:'The limitation that must shape the purchase',body:'RIDGID explicitly excludes root blockages from the K-400’s intended duty. That restriction matters more than a long cable or attractive headline price. A buyer regularly dealing with larger lines, roots or different deposits should evaluate an approved larger cable system or another cleaning method with the appropriate heads.'},{heading:'Compare ownership with your workload',body:'Cable replacement, transport, cleaning, maintenance and operator training are part of the investment. A machine that earns its place on a drain specialist’s route may sit unused in a general repair van. We have not measured clearing performance or payback; these are configuration-based comparisons to support a business purchase.'}])
];
