import {guides,hubs} from './data';
import type {Workflow,WorkflowTool} from './workflows';
import {job} from './plumber-catalog-types';
type KitPick=[string,string,string,WorkflowTool['priority']];
function kit(slug:string,title:string,summary:string,stages:Workflow['stages'],picks:KitPick[],notes:string[]):Workflow {
 const tools=picks.map(([id,stage,why,priority])=>{
  const guide=guides.find(g=>g.trade==='plumbers'&&g.products.some(p=>p.productId===id||p.reviewSlug===`${id}-review`));
  const p=guide?.products.find(p=>p.productId===id||p.reviewSlug===`${id}-review`);
  if(!guide||!p) throw new Error(`Missing plumbing workflow product ${id}`);
  return {stage,type:guide.title.replace(/^Best /,'').replace(/ for Plumbers.*/,''),name:`${p.brand} ${p.model}`,why,priority,amazonUrl:p.url,guideUrl:`/plumbers/${guide.slug}/`,reviewUrl:p.reviewSlug?`/reviews/${p.reviewSlug}/`:undefined};
 });
 return {trade:'plumbers',tradeName:'Plumbers',slug,title,keyword:title.toLowerCase(),meta:summary,summary,heroImage:hubs.find(h=>h.slug==='plumbers')!.image,stages,tools,notes,
 faqs:[{q:'Do I need to buy the whole kit at once?',a:'No. Start with the core tools required for the work you are trained and authorized to perform. Useful and upgrade picks are conditional purchases, not a requirement to own every item.'},{q:'Are these complete retail packages?',a:'Check each product assessment. Tool-only machines may need batteries, heads, jaws, monitors or hoses. The job kit is a buying plan rather than a single retail bundle.'},{q:'How should I choose between alternatives?',a:'Use the linked category guide to compare the approved application, size, access and complete equipment requirements. Existing batteries matter after the tool has been matched to the job.'}]};
}
export const plumberWorkflows:Workflow[]=[
kit(job.service,'Plumber Residential Service Call Tool Kit: Diagnose, Repair and Clean Up','Build a practical plumbing service kit for first inspection, under-sink access, small repairs and cleanup. Keep larger specialist equipment in the van until the diagnosis justifies it.',
[{name:'1. Inspect and contain',description:'Establish the complaint, inspect the area and plan water containment before opening a connection.'},{name:'2. Gain access',description:'Use suitable light, gripping tools and faucet access equipment without damaging finished fittings.'},{name:'3. Repair the identified system',description:'Match cutters and connection tools to the actual pipe material and approved fittings.'},{name:'4. Check and clean up',description:'Verify the repair with the required system checks and leave the work area clean.'}],
[['ridgid-micro-ca25','Inspect','A local camera can help view accessible cavities and nearby fittings; it is not a long-run sewer survey system.','Useful'],['klein-56062','Gain access','Hands-free nearby light helps see the actual fitting and tool contact under a sink.','Core'],['knipex-8701250','Gain access','A compact toothed gripper for appropriate pipe and fittings; use a smooth-jaw alternative for visible finishes.','Core'],['ridgid-2017','Gain access','A dedicated basin-wrench approach for mounting nuts that match its head and capacity.','Useful'],['ridgid-40617','Repair','A close-quarters cutter for suitable small copper tubing when access is restricted.','Core'],['ridgid-rc1625','Repair','A separate ratchet cutter for compatible plastic pipe within its published capacity.','Core'],['ridgid-k6p','Drain complaint','Carry a toilet-specific auger when bowl obstructions are a regular service task.','Useful'],['milwaukee-0880-20','Clean up','Small cordless wet/dry cleanup for an existing M18 owner, with the correct wet-use setup.','Useful'],['veto-tpxl','Carry','Keep the selected daily tools visible and leave larger or contaminated equipment separately stored.','Useful']],
['The kit does not include every fitting or repair material; stock those for the systems you actually service.','Choose one suitable connection system from the pipe-repair guide rather than buying every crimp, expansion and press tool.']),
kit(job.leak,'Plumber Leak Detection Tool Kit: Inspect, Compare and Confirm','Choose complementary leak-investigation tools: visible inspection, relative moisture screening and surface-temperature clues. Confirm the plumbing source before recommending a repair.',
[{name:'1. Inspect the complaint',description:'Record the affected location and visible evidence; establish what changed and when.'},{name:'2. Map the indicators',description:'Use the proper material mode and reference area for moisture screening.'},{name:'3. Investigate access',description:'Use local camera or thermal clues to guide further checks rather than claim hidden-object visibility.'},{name:'4. Confirm and record',description:'Confirm the plumbing cause with an appropriate test and retain clear location notes.'}],
[['klein-et140','Map moisture','Non-invasive relative screening across its listed materials supports an investigation.','Core'],['protimeter-bld5375','Confirm indicators','Dual pin and non-invasive methods are an upgrade when more detailed moisture work is recurring.','Upgrade'],['flir-c5','Map temperature','A standalone capture workflow can document surface patterns; it does not prove a leak.','Upgrade'],['ridgid-micro-ca25','Investigate access','Local viewing through appropriate openings can support a visible inspection.','Useful'],['klein-56062','Inspect','Useful near-task lighting for the location and instrument readings.','Core'],['milwaukee-2771-20','Contain water','Hose-transfer equipment is conditional on the permitted liquid and the chosen discharge route.','Useful'],['ridgid-hd06001','Cleanup','Corded cleanup after the cause has been addressed, using the correct wet-pickup arrangement.','Useful']],
['Thermal patterns and moisture readings do not identify the leak source by themselves.','Keep the material mode, reference area and physical location with any recorded reading.']),
kit(job.drain,'Plumber Drain Clearing Tool Kit: Toilet, Small Drain and Mainline Decisions','Choose drain equipment by fixture access, pipe diameter and obstruction type. Separate toilet augers, small-drain snakes, professional machines and camera systems.',
[{name:'1. Identify the line',description:'Establish the fixture, pipe route, access point and suspected obstruction before choosing equipment.'},{name:'2. Choose the correct method',description:'Select a toilet-specific, small-drain or professional machine within its documented application.'},{name:'3. Inspect when justified',description:'A suitable camera system can inform recurring or unclear drain complaints.'},{name:'4. Verify and contain',description:'Check the result and clean, contain and transport dirty equipment separately.'}],
[['ridgid-k6p','Toilet access','Protected toilet-specific guide and six-foot available cable reach.','Core'],['milwaukee-2571-20','Small drains','M12 powered small-drain work within the documented cable and pipe application.','Core'],['ridgid-k400','Larger suitable lines','A conditional professional drum purchase; K-400 is not designed for roots.','Upgrade'],['ridgid-k9204plus','Specialist cleaning','A different enclosed-shaft method for approved cleaning tasks, not a universal snake replacement.','Upgrade'],['ridgid-microreel-essentials','Inspect','A complete-system comparison for a recurring professional survey workload.','Upgrade'],['klein-56062','Setup','Near-task light to see access, equipment and cable contact.','Core'],['ridgid-hd06001','Cleanup','Liquid cleanup using the specified wet-pickup setup.','Useful']],
['Professional machines are business investments; ownership depends on workload, training and maintenance.','Use the machine manual’s prescribed operating method and protective equipment. Keep contaminated cable equipment separate from clean tools.']),
kit(job.bath,'Plumber Bathroom Installation Tool Kit: Faucet Access, Pipe Prep and Finish Protection','Plan a bathroom-installation kit around fixture access, protected gripping, correct pipe cuts and the selected approved connection system.',
[{name:'1. Plan access',description:'Check mounting nuts, supply fittings, pipe materials and the fixture installation instructions.'},{name:'2. Remove and prepare',description:'Use an appropriate access tool and avoid serrated contact on finishes that need protection.'},{name:'3. Cut and connect',description:'Cut the actual pipe material with a suitable tool and use the approved connection system.'},{name:'4. Verify and finish',description:'Perform required system checks, inspect the fixture and clean the area.'}],
[['ridgid-2017','Fixture access','A dedicated basin wrench when the mounting nut and approach suit it.','Core'],['ridgid-ezchange','Fixture access','An alternative multi-function interface set for compatible faucet parts.','Useful'],['knipex-8603250','Finish protection','Smooth parallel jaws serve suitable flats without serrated tooth contact.','Core'],['ridgid-40617','Copper preparation','Close-quarters cutting for suitable copper tubing.','Core'],['ridgid-rc1625','Plastic preparation','A dedicated cutter within the plastic material and size limits.','Core'],['iwiss-iws1234w','Selected PEX connection','Copper-ring crimping only when that approved system is the installation choice.','Useful'],['milwaukee-2532-20','Alternative expansion system','Choose instead for approved ProPEX expansion; heads and power equipment need checking.','Upgrade'],['klein-56062','Visibility','Hands-free nearby light for contact and connection checks.','Core'],['milwaukee-0880-20','Cleanup','Portable wet/dry cleanup for local work.','Useful']],
['Crimp and expansion tools represent different approved systems. The kit is not an instruction to use both on the same connection.','Protect finished fittings with the correct gripping tool and fixture-maker guidance.']),
kit(job.pipe,'Plumber Pipe Repair Tool Kit: Copper, Plastic, PEX and Press Connections','Choose a pipe-repair kit by material and approved connection method. Combine complementary gripping and cutting tools, then add the joining system your recurring work requires.',
[{name:'1. Identify and prepare',description:'Confirm material, nominal size, approved repair method and access before cutting.'},{name:'2. Hold and cut',description:'Support the work and use the cutter or gripping method intended for that material.'},{name:'3. Make the approved connection',description:'Use the system-specific rings, heads or jaws and its documented preparation checks.'},{name:'4. Inspect and test',description:'Complete the inspection and testing required for the installed system.'}],
[['ridgid-31020','Hold','Conventional 14-inch wrench for appropriate round threaded pipe with enough swing space.','Core'],['knipex-8701250','Hold','Complementary adjustable toothed gripper for appropriate service fittings.','Core'],['ridgid-40617','Cut copper','Close-quarters small-tube preparation.','Core'],['ridgid-rc1625','Cut plastic','Separate material-appropriate cutting tool.','Core'],['iwiss-iws1234w','Copper-ring PEX system','Select for approved 1/2- and 3/4-inch copper crimp rings.','Useful'],['milwaukee-2532-20','Expansion system','Select for approved ProPEX work with the correct heads.','Upgrade'],['milwaukee-2473-20','Press system','Select only with compatible approved jaws, fittings and sizes.','Upgrade'],['milwaukee-2771-20','Water handling','Conditional hose-transfer equipment for permitted liquid and head requirements.','Useful']],
['Choose joining tools from the system compatibility requirements first. Battery preference comes afterwards.','A finished connection still needs the inspection and verification specified for that system.']),
kit(job.heater,'Plumber Water Heater Service Tool Kit: Drain, Access and Connection Choices','Plan equipment for permitted water transfer, fitting access, pipe preparation and cleanup. Match every tool to the heater instructions and the authorized service task.',
[{name:'1. Establish the service task',description:'Follow the equipment instructions for isolation, cooling and permitted work before opening the system.'},{name:'2. Manage the liquid',description:'Choose hoses, pump and discharge arrangement within the liquid and temperature limits.'},{name:'3. Access and repair',description:'Use suitable gripping and connection tools for the actual pipe and fitting system.'},{name:'4. Restore and verify',description:'Complete the heater and connection checks required by the manufacturer and clean the area.'}],
[['milwaukee-2771-20','Transfer','Cordless hose-transfer format when the liquid temperature and application are permitted.','Useful'],['liberty-331','Transfer alternative','A corded transfer option; choose one suitable pump arrangement rather than both by default.','Useful'],['ridgid-31020','Fitting access','Suitable round threaded-pipe work where the tool has room.','Core'],['knipex-8603250','Fitting access','Smooth-jaw handling of suitable flats and finished fittings.','Core'],['ridgid-40617','Pipe preparation','Copper cutter within its stated size and material range.','Core'],['milwaukee-2473-20','Approved press connection','Conditional on fitting approval and the correct compact jaws.','Upgrade'],['flir-c5','Surface checks','Temperature patterns can support investigation; the camera does not replace required heater checks.','Upgrade'],['ridgid-hd06001','Cleanup','Wet/dry cleanup after the repair with the correct setup.','Useful']],
['Do not assume a pump is suitable for hot heater water. Check its liquid and temperature limits and the heater’s service procedure.','Gas, combustion and electrical service have their own qualification and equipment requirements beyond this plumbing buying kit.']),
kit(job.apprentice,'Plumber Apprentice Starter Kit: Core Hand Tools Before Specialist Machines','Start with the tools your employer requires: suitable gripping, pipe cutting, faucet access, nearby lighting and manageable storage. Add costly machines only when the actual work justifies them.',
[{name:'1. Confirm the required list',description:'Check your employer’s tools, approved systems and what equipment is supplied.'},{name:'2. Cover common access',description:'Build a small set of complementary gripping, lighting and faucet-access tools.'},{name:'3. Add material-specific cutting',description:'Buy for the pipe and connection methods you actually use.'},{name:'4. Organize and maintain',description:'Keep the kit usable, clean and checked; expand it from experience.'}],
[['knipex-8701250','Grip','One adjustable toothed gripper for appropriate work; choose an alternative from the comparison if budget demands.','Core'],['ridgid-31020','Threaded pipe','Add a conventional wrench when suitable threaded round pipe is part of the role.','Core'],['ridgid-40617','Copper cutting','A small close-quarters cutter when copper tubing work is required.','Core'],['ridgid-rc1625','Plastic cutting','A separate cutter when the employer’s plastic pipe matches its approved range.','Core'],['milwaukee-48227001','Faucet access','A basin wrench suited to the employer’s recurring mounting nuts.','Useful'],['klein-56062','Visibility','Near-task hands-free lighting for careful work.','Core'],['klein-554161014','Carry','A compact open tote for a selected daily hand-tool kit.','Useful'],['iwiss-iws1234w','Employer-selected system','Buy only if the role requires this approved copper-ring connection method.','Useful']],
['The apprentice kit is a starting buying plan, not an instruction to perform unfamiliar work independently.','Do not spend on a press machine, sewer camera or professional drain machine before confirming whether your employer supplies it.']),
kit(job.van,'Plumber Van and Tool Bag Setup: Daily Carry, Specialist Kits and Dirty Equipment','Organize a plumbing van around a clean daily carry, separately protected diagnostic equipment, complete specialist packages and contained dirty drain tools.',
[{name:'1. Define daily carry',description:'Keep the ordinary service tools together without filling the bag with every machine.'},{name:'2. Group complete specialist kits',description:'Store the tool with its compatible heads, jaws, batteries, monitor or hoses.'},{name:'3. Separate dirty equipment',description:'Contain wet drain equipment away from clean instruments and household-facing tools.'},{name:'4. Replenish and check',description:'Inspect tool condition, charge suitable batteries and replace used consumables.'}],
[['veto-tpxl','Daily carry','A compact closable bag for the selected house-visit kit.','Useful'],['veto-techmct','Alternative daily carry','Choose an enclosed two-sided layout if it fits the actual tool list better.','Useful'],['milwaukee-48228321','Storage system','Conditional on an existing PACKOUT organization plan and appropriate tool fit.','Useful'],['milwaukee-2473-20','Press kit','Keep the correct approved jaws and power equipment with the press tool.','Upgrade'],['ridgid-microreel-essentials','Camera kit','Keep the complete viewing, power and recording arrangement together.','Upgrade'],['milwaukee-2571-20','Drain kit','Maintain a separate containment and cleaning arrangement for the cable machine.','Useful'],['milwaukee-0970-20','Cleanup','A PACKOUT-compatible local vacuum when that storage system fits the van.','Useful'],['klein-et140','Diagnostics','Store clean instruments away from wet contaminated equipment.','Useful']],
['The three bag/tote picks are layout alternatives, not a requirement to purchase all of them.','A storage-system interface does not establish safe vehicle restraint. Use an appropriate transport and securing arrangement.'])
];
