import {category as c,tool as t} from './plumber-category-builder';
import {job} from './plumber-catalog-types';
const r='https://www.ridgid.com/us/en/';
export const plumberDiagnosticCategories=[
c('best-sewer-cameras-for-plumbers','Best Sewer Cameras for Plumbers: Push-Rod Systems and Complete Packages','Drain Cleaning & Inspection',
'RIDGID microREEL Essentials is the all-in-one purchase comparison. Compact M40 and C40 are reel-based systems with different cable behavior; microDrain APX serves shorter small-line access. Milwaukee 2974-22 is a larger 200-foot pipeline package for a different workload.',
'A reel-only listing is not a complete camera system. Compare the monitor, recording, locator compatibility, cable diameter, guides and cleaning arrangements. A sonde transmits a location signal; it is not a locator receiver.',
[{title:'Pipe size and bends first',body:'Check the camera head, push cable and guides against the pipe and access route. More cable length can be less useful than a smaller system that negotiates the required bends. Never assume every reel can inspect every residential branch.'},{title:'Price the complete system',body:'Add a compatible monitor, power equipment and any separately required locator. Recording and report export depend on the monitor and configuration, not just the camera head’s advertised image quality.'},{title:'Specialist return on investment',body:'A camera is justified by repeated diagnostic work and a usable recording process. Check service support for damaged push cable and heads. We have not measured image quality or cable navigation in real drains.'}],
[{q:'Does Compact M40 include a screen?',a:'A reel-only Compact M40 listing does not. Check the exact package for a compatible SeeSnake monitor and power equipment.'},{q:'Does a sonde replace a locator?',a:'No. The camera’s transmitter and a compatible locating receiver are separate parts of a locating setup.'},{q:'Is a four-foot borescope a sewer camera?',a:'No. Local inspection cameras are useful for nearby access; a push-rod drain survey requires a purpose-built system.'}],
[job.drain,job.leak,job.van],[
t('ridgid-microreel-essentials','RIDGID','SeeSnake microREEL Essentials','All-in-one system comparison',r+'microreel-essentials','buyers who want a defined integrated viewing package for suitable smaller lines.','Check the exact package; this is not the same purchase as a reel-only microREEL.',[['Push cable','100 ft'],['Published pipe application','1.5–4 in'],['Package','Essentials integrated system']],['All-in-one purchase format','Smaller-line application'],['Not a universal bend or pipe solution','Exact package determines recording equipment']),
t('ridgid-compact-m40','RIDGID','SeeSnake Compact M40 Reel 63673','Mid-flex push-cable option',r+'seesnake-compact-m40','professional buyers matching mid-flex cable behavior to their drain work.','A compatible monitor and power equipment must be priced separately in a reel-only offer.',[['Catalog','63673 reel'],['System','SeeSnake Compact M40']],['Compact reel layout','Published monitor compatibility'],['Reel alone is incomplete','Cable navigation depends on the line']),
t('ridgid-compact-c40','RIDGID','SeeSnake Compact C40','Different cable behavior in compact format',r+'seesnake-compact-c40-camera-system','buyers comparing the C40 push-cable design with M40 for their access routes.','Do not assume a C40 and M40 listing includes the same viewing package.',[['System','SeeSnake Compact C40'],['Configuration','Verify reel/monitor package']],['Compact transport format','Purpose-built drain camera'],['Monitor package must be checked','Application limits matter']),
t('ridgid-microdrain-apx','RIDGID','SeeSnake microDrain APX','Shorter small-line system',r+'seesnake-microdrain-apx-with-trusense-technology','small-line access that suits the microDrain head and cable.','Choose a longer appropriate system for larger or longer sewer surveys.',[['System','microDrain APX'],['Push cable','65 ft']],['Small-line system format','Purpose-built guided cable'],['Shorter survey reach','Compatible monitor required']),
t('milwaukee-2974-22','Milwaukee','2974-22 M18 200-Foot Stiff Pipeline Inspection Kit','Larger pipeline package','https://www.milwaukeetool.com/2974-22','professional pipeline work that suits the stiff-cable 200-foot system.','This larger system is not the default for small, tight residential branches.',[['Cable length','200 ft'],['Published pipe application','3–10 in'],['Platform','M18']],['Long-run pipeline package','M18 platform'],['Substantial equipment investment','Larger-line application'])],
[{heading:'Compare Essentials as a complete purchase',body:'microREEL Essentials makes a useful starting comparison because the integrated package is easier to assess than a reel advertised without its viewing equipment. Check the precise included components and the published pipe range. Its 100-foot cable is available reach, not a guarantee that it will travel every bend or inspect a full run in any pipe.'},{heading:'A monitor changes what the camera can deliver',body:'Recording, sharing and inspection records depend on the selected viewing system. Compare a customer-ready package with another customer-ready package, including power, storage and export. A reel photograph that shows a screen nearby is not evidence that the screen is supplied.'},{heading:'Locating and maintenance are separate costs',body:'A sonde-equipped camera still needs the right locating receiver when tracing position matters. Push-cable and camera-head service also belong in the ownership decision. This assessment does not claim measured image quality or navigation performance; it explains the documented package and application distinctions.'}]),
c('best-moisture-meters-for-plumbers','Best Moisture Meters for Plumbers: Relative Scans and Pin Measurements','Leak Detection & Diagnostics',
'Klein ET140 is the pinless screening pick for its listed building materials. Protimeter BLD5375 and Extech MO55 combine pin and pinless methods. General MMD4E is a pin-based option; Wagner Orion 910 is deliberately the wood-focused alternative.',
'A moisture reading does not identify the leak source. Relative drywall or masonry scales must not be interpreted as a universal percent water content. Compare affected areas with appropriate reference areas and confirm the plumbing cause separately.',
[{title:'Material and measurement method',body:'Pinless scanning can map relative changes without pin holes; pins measure at their contact points. Wood-focused instruments and relative building-material scales answer different questions. Read the manual’s material and depth limitations.'},{title:'Screen, then investigate',body:'Moisture readings can help define an affected area but do not establish the cause or whether a pipe is leaking. Construction layers, metal and material changes can affect interpretation. Use the instrument within its documented limits.'},{title:'Record comparable readings',body:'Use a consistent material mode and suitable reference location when recording a trend. A display percentage alone is not a transferable measurement across different materials or instruments.'}],
[{q:'Can a meter find the leaking pipe?',a:'It can help map moisture indicators, but it does not identify the source by itself. Confirm the plumbing condition using an appropriate diagnostic method.'},{q:'Is a drywall reading a true percent water content?',a:'Do not assume that. Relative scales and calibrated material modes must be interpreted according to the instrument’s manual.'},{q:'Why include a wood meter?',a:'Wood moisture can matter after a leak. Orion 910 is included for that task, not as a general masonry or drywall meter.'}],
[job.leak,job.service,job.bath],[
t('klein-et140','Klein Tools','ET140 Pinless Moisture Meter','Pinless building-material screening pick','https://www.kleintools.com/catalog/environmental-testers/pinless-moisture-meter','relative scans of the listed drywall, masonry, hardwood and softwood materials.','Do not interpret every displayed value as absolute moisture content.',[['Method','Pinless'],['Listed sensing depth','Up to 3/4 in'],['Modes','Drywall, masonry, hardwood, softwood']],['No pin holes for scanning','Listed building-material modes'],['Relative interpretation required','Does not identify the leak source']),
t('protimeter-bld5375','Protimeter','BLD5375 Surveymaster','Current dual-method professional option','https://www.protimeter.com/surveymaster-2024-model','professional moisture investigation needing both pin and non-invasive modes.','This is the current BLD5375 version, not the older blueprint’s BLD5365.',[['Model','BLD5375'],['Methods','Pin and non-invasive']],['Two measurement methods','Current Surveymaster platform'],['More investment than a basic screen','Material-specific interpretation']),
t('general-mmd4e','General Tools','MMD4E Pin-Type Moisture Meter','Basic pin-contact alternative','https://generaltools.com/pin-type-lcd-moisture-meter','buyers who need a basic pin-based reading at accessible contact points.','Pins leave marks and do not provide a broad non-invasive scan.',[['Method','Pin contact'],['Model','MMD4E']],['Simple pin-based format','Separate wood/building-material use guidance'],['Pin marks','Point measurement rather than broad scan']),
t('extech-mo55','Extech','MO55 Combination Moisture Meter','Pin and pinless portable alternative','https://www.extech.com/en-eu/products/mo55/','buyers comparing pin contact with non-invasive screening in one instrument.','Follow the material scales; do not treat both modes as equivalent absolute measurements.',[['Methods','Pin and pinless'],['Model','MO55']],['Combined measurement modes','Portable instrument format'],['Scales need correct interpretation','No independent source diagnosis']),
t('wagner-orion910','Wagner Meters','Orion 910 Deep Pinless Wood Moisture Meter','Wood-focused leak-follow-up option','https://shop.wagnermeters.com/products/orion-910-deep','wood-moisture assessment within the instrument’s calibrated material range.','Choose a building-material meter for general drywall and masonry screening.',[['Material','Wood'],['Method','Pinless'],['Model','Orion 910']],['Wood-specific measurement design','Non-invasive wood scanning'],['Not a universal wall meter','Species and setup matter'])],
[{heading:'ET140 is a screening tool for listed materials',body:'The ET140’s pinless format is useful when mapping relative moisture indicators across the materials Klein lists. Its material mode and sensing-depth limitations must shape the result. Use it to support an investigation, not to claim that a display reading identifies a hidden pipe or proves the source of a leak.'},{heading:'Choose pin contact when the question calls for it',body:'Pin and pinless methods access the material differently. A dual-method instrument can add flexibility, while a basic pin instrument may meet a narrower requirement. The tradeoff includes surface marks, material calibration and reading depth rather than a simple higher-price-means-more-accurate ranking.'},{heading:'Keep the interpretation with the record',body:'Record material mode, location and an appropriate comparison area with the reading. Relative values from drywall should not be presented as universal percent moisture or directly compared with calibrated wood readings from another instrument. We have not performed laboratory accuracy tests; the recommendation is based on method and documented material fit.'}]),
c('best-thermal-cameras-for-plumbers','Best Thermal Cameras for Plumbers: Leak Clues, Hot-Water Lines and Documentation','Leak Detection & Diagnostics',
'FLIR C5 is the standalone documentation candidate. HIKMICRO B01 offers a different standalone detector/display package; Klein TI250 emphasizes simple viewing. TOPDON TC001 requires a compatible Android device; FLIR TG165-X is a spot-checking format.',
'Thermal cameras see surface-temperature patterns, not through walls. A cool or warm patch is a diagnostic clue, not proof of moisture or the exact location of a hidden pipe. Confirm findings with suitable moisture or plumbing checks.',
[{title:'Surface pattern versus diagnosis',body:'Surface temperature depends on several conditions, including heating, airflow and material. Use a thermal image to guide further checks. It cannot by itself prove a leak, identify hidden pipe depth or establish that a wall is dry.'},{title:'Phone attachment or standalone',body:'TC001 depends on supported Android hardware and software. Standalone tools avoid that dependency but have their own storage and export workflows. Check the complete recording process before buying for customer reports.'},{title:'Native detector and context',body:'Compare the native thermal detector, field of view, focus and image export. Display pixel count is not thermal resolution. Visual-image blending provides context but does not add hidden-object visibility.'}],
[{q:'Can a thermal camera see a pipe through a wall?',a:'No. It shows surface-temperature patterns that may reflect a nearby heating or cooling influence. Other evidence is needed to establish a pipe’s route or a leak.'},{q:'Does TC001 work with an iPhone?',a:'This TC001 recommendation is for compatible Android devices. Check TOPDON’s current compatibility requirements; do not assume every USB-C phone is supported.'},{q:'Do I still need a moisture meter?',a:'Often yes. Thermal patterns and moisture indicators answer different questions. Confirm the suspected condition using suitable checks.'}],
[job.leak,job.heater,job.van],[
{...t('flir-c5','FLIR','C5 Compact Thermal Imaging Camera','Standalone documentation candidate','https://www.flir.com/products/c5','surface-temperature investigation with a standalone capture workflow.','It does not see through walls or prove moisture.',[['Native thermal detector','160 × 120'],['Format','Standalone']],['MSX visual context','Standalone image capture'],['Premium purchase for occasional use','Surface-pattern interpretation required']),reviewSlug:'flir-c5-review'},
{...t('hikmicro-b01','HIKMICRO','B01 Handheld Thermal Camera','Standalone thermal-detail comparison','https://www.hikmicrotech.com/en_us/industrial-products/b-series-handheld-thermal-imager/','buyers comparing standalone thermal detector and display formats.','Verify current regional model and recording specifications.',[['Format','Standalone'],['Model','B01']],['Standalone thermal viewing','No phone attachment required'],['Check export workflow','Regional model details matter']),reviewSlug:'hikmicro-b01-review'},
{...t('klein-ti250','Klein Tools','TI250 Rechargeable Thermal Imager','Simple standalone alternative','https://www.kleintools.com/catalog/thermal-imagers/rechargeable-thermal-imager','quick surface-pattern checks with a simple dedicated device.','Choose a recording-oriented model if the needed documentation workflow is not supported.',[['Format','Standalone'],['Power','Rechargeable']],['Dedicated thermal display','Simple viewing format'],['Check recording requirements','Not hidden-object imaging']),reviewSlug:'klein-ti250-review'},
{...t('topdon-tc001','TOPDON','TC001 Thermal Imaging Camera for Android','Android attachment alternative','https://www.topdon.com/products/tc001','compatible Android users wanting a phone-based thermal workflow.','Phone hardware, connection and app support are required.',[['Format','Phone attachment'],['Compatibility','Supported Android devices']],['Uses compatible phone display','App-based workflow'],['Phone dependency','Not every USB-C device is compatible']),reviewSlug:'topdon-tc001-review'},
{...t('flir-tg165x','FLIR','TG165-X MSX Thermal Camera','Spot-check format','https://www.flir.com/products/tg165-x','buyers wanting the TG165-X spot-measurement and thermal-context layout.','Compare the detector and capture workflow with broader survey cameras.',[['Format','Standalone spot-check imager'],['Model','TG165-X']],['Thermal context around a spot check','MSX visual detail'],['Different survey workflow from C5','Not proof of a leak']),reviewSlug:'flir-tg165x-review'}],
[{heading:'Why documentation changes the purchase',body:'A plumbing investigation may need an image that can be explained to a customer and kept with the job record. C5 is a standalone candidate for that workflow. Check the actual capture and export method, and keep a conventional photograph and location notes with thermal evidence when they help establish context.'},{heading:'Confirm the finding with another method',body:'Temperature differences can have several causes. A thermal pattern may guide a moisture reading or plumbing investigation, but it is not proof that a pipe leaks or that the instrument can see through a wall. The camera should support a diagnostic process rather than supply a definitive conclusion from color alone.'},{heading:'A phone accessory has a different ownership cost',body:'TC001 can make sense for a supported Android owner, but compatibility and app support are part of the purchase. A standalone device removes the phone dependency and adds its own charging and storage requirements. We have not measured thermal accuracy or detection performance on plumbing jobs.'}])
];
